Add Script Commands: largest-cpu-process, largest-ram-process
raycast/script-commands pull request #101
Opened 2020-11-22 17:36 UTC by crstauf

## Description

Please write a short summary for this change. If it's a new script command, explain what it does.

## Type of change

- [x] New script command

## Screenshot

<img width="768" alt="Screen Shot 2020-11-22 at 12 35 46 PM" src="https://user-images.githubusercontent.com/4573033/99910966-48ff5200-2cbf-11eb-9522-a98d9735cf4d.png">

## Dependencies / Requirements

- `ps` command
- `awk` command

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2020-11-22 23:36 UTC, thomaspaulmann requested changes
Nice one! I added some suggestions to improve the visual representation of the numbers.

2020-11-22 23:36 UTC, thomaspaulmann commented on commands/system/largest-ram-process.sh
> +gigabytes=$(echo "scale=3; $bytes / 1024 / 1024" | bc -l)
I assume `scale` are the digits after the decimal point? Let's make it 1. This should be enough and aligns with how the Activity Monitor displays it.
```suggestion
gigabytes=$(echo "scale=1; $bytes / 1024 / 1024" | bc -l)
```

2020-11-22 23:36 UTC, thomaspaulmann commented on commands/system/largest-cpu-process.sh
> +cmd=$(echo "$cmd" | awk '{$1=$1};1')
So does this remove the leading whitespace or not? 🙃

2020-11-22 23:36 UTC, thomaspaulmann commented on commands/system/largest-ram-process.sh
> +gigabytes=$(echo "scale=3; $bytes / 1024 / 1024" | bc -l)
I would also suggest to show process that consume less than 1 GB of RAM as megabytes, e.g. 834.6 MB. This would align with the Activity Monitor. 

Something along these lines:
```suggestion
if [ $bytes -le 1024 ]; then
  scaled_bytes=...
el
  scaled_bytes=...
fi

formatted_bytes=$(echo "scale=1; $scaled_bytes" | bc -l)
```
  formatted_bytes=$(echo "scale=1; $bytes / 1024 " | bc -l)
  formatted_bytes=$(echo "scale=1; $bytes / 1024 / 1024" | bc -l)

```

2020-11-22 23:51 UTC, crstauf commented on commands/system/largest-cpu-process.sh
> +cmd=$(echo "$cmd" | awk '{$1=$1};1')
It does, I don't understand why it's needed here and not in the RAM one.

2020-11-23 02:08 UTC, crstauf commented on commands/system/largest-ram-process.sh
> +gigabytes=$(echo "scale=3; $bytes / 1024 / 1024" | bc -l)
@thomaspaulmann Updated; set to one decimal place for megabytes and two decimal places for gigabytes (to match Activity Monitor https://cloudup.com/coGkuBW6PUb).

2020-11-23 16:55 UTC, merged