Add Script Command: search-github
raycast/script-commands pull request #106
Opened 2020-11-23 19:09 UTC by crstauf

## Description

Search GitHub.

## Type of change

- [x] New script command

## Screenshot

<img width="770" alt="Screen Shot 2020-11-23 at 2 08 51 PM" src="https://user-images.githubusercontent.com/4573033/100004408-73234380-2d95-11eb-9dcf-8b9c1eca1951.png">

## Dependencies / Requirements

- `open`

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2020-11-23 19:15 UTC, unnamedd commented on commands/web-searches/search-github.sh
> +open "https://cdnjs.com/libraries?q=${1// /%20}"
@crstauf I guess you got some confusion here...

2020-11-23 19:20 UTC, crstauf commented on commands/web-searches/search-github.sh
> +open "https://cdnjs.com/libraries?q=${1// /%20}"
Agh, I've been trying Nova lately, and it doesn't open the new file when duplicating an existing file. I've done this sort of thing at least a dozen times.

2020-11-24 07:51 UTC, fe9lix requested changes
Could you update the logo? It's hardly visible in light mode (you can change the appearance in Raycast preferences for testing).

2020-11-24 13:25 UTC, crstauf commented
@fe9lix I was directed by @thomaspaulmann (https://github.com/raycast/script-commands/pull/31#issuecomment-723248908) to use icons for dark theme until support for both themes is available.

2020-11-24 17:48 UTC, fe9lix commented
@crstauf Alright, then let's keep it and add another version when we ship theming support.

2020-11-24 17:48 UTC, fe9lix approved these changes

2020-11-24 17:49 UTC, merged