feat(System): caffeinate
raycast/script-commands pull request #141
Opened 2020-12-02 03:27 UTC by maximkrouk

## Description

Prevents devices from sleeping

## Type of change

- [x] New script command

## Screenshot

<p align="center">
<img width="862" alt="Screen Shot 2020-12-02 at 06 24 56" src="https://user-images.githubusercontent.com/40476363/100824387-1d226000-3467-11eb-8c45-a116eba98c5a.png">

<img width="862" alt="Screen Shot 2020-12-02 at 06 25 16" src="https://user-images.githubusercontent.com/40476363/100824407-27445e80-3467-11eb-92f7-8961cda2a81a.png">

<img width="257" alt="Screen Shot 2020-12-02 at 06 25 29" src="https://user-images.githubusercontent.com/40476363/100824422-2e6b6c80-3467-11eb-96ca-9b85a2a647a1.png">

<img width="862" alt="Screen Shot 2020-12-02 at 06 25 58" src="https://user-images.githubusercontent.com/40476363/100824464-3fb47900-3467-11eb-8f60-426c790a6bf5.png">

<img width="92" alt="Screen Shot 2020-12-02 at 06 26 13" src="https://user-images.githubusercontent.com/40476363/100824484-480cb400-3467-11eb-929e-6391551dbb86.png">
</p>

## Dependencies / Requirements

None

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2020-12-02 03:37 UTC, maximkrouk commented
I also have a draft for tracking these processes

```bash
#!/bin/zsh

# @raycast.schemaVersion 1
# @raycast.title Caffeinate
# @raycast.mode inline
# @raycast.author Maxim Krouk
#
# @raycast.authorURL https://github.com/maximkrouk
# @raycast.description Displays active caffeinates.
# @raycast.icon ☕️
# @raycast.packageName System
# @raycast.refreshTime 15s

result=$(ps aux | grep caffeinate | awk '{print $9 " " $14}') # Output example - "5:32PM 1231"

# todo : calculate time
regex='^[0-9]+$'
if ! [[ $result =~ $regex ]] ; then
  echo "No caffeine here"
else
  echo "Won't sleep for" $result "seconds"
fi
```

2020-12-03 12:29 UTC, PitNikola requested changes
Really handy one! Btw, thanks for providing such nice screenshots, love it!

I have only minor suggestion (due to our recent improvement in 1.3.0).

2020-12-03 12:29 UTC, PitNikola commented on commands/system/start-caffeinate.sh
> +  echo "Provide a number, please  ❌"
@maximkrouk, in latest version (1.3.0) we improved error reporting in silent and compact mode. Now if you exit with non-zero status, we'll display warning emoji with last output line. Like this:

![CleanShot 2020-12-03 at 12 21 45@2x](https://user-images.githubusercontent.com/4332171/101017554-247a6400-3562-11eb-913f-c0aa430d3ae7.png)

Shall we leverage it here? Something like:
```
echo "Provide a number please"
exit 1
```

2020-12-03 12:55 UTC, maximkrouk commented on commands/system/start-caffeinate.sh
> +  echo "Provide a number, please  ❌"
Ok, I'll fix it soon

2020-12-03 12:56 UTC, maximkrouk commented on commands/system/start-caffeinate.sh
> +  echo "Provide a number, please  ❌"
Btw ty 4 the compliment, maybe it worth adding cmd+5 screenshots to contribution guidelines 😅

2020-12-03 13:44 UTC, unnamedd commented on commands/system/start-caffeinate.sh
> +  echo "Provide a number, please  ❌"
> @maximkrouk, in latest version (1.3.0) we improved error reporting in silent and compact mode. Now if you exit with non-zero status, we'll display warning emoji with last output line. Like this:
> 
> ![CleanShot 2020-12-03 at 12 21 45@2x](https://user-images.githubusercontent.com/4332171/101017554-247a6400-3562-11eb-913f-c0aa430d3ae7.png)
> 
> Shall we leverage it here? Something like:
> 
> ```
> echo "Provide a number please"
> exit 1
> ```

@PitNikola it will be nice if you move this comment/documentation to the README. What do you think?

2020-12-03 14:35 UTC, maximkrouk commented
Also I'd like to implement custom output for longest-caffeinate command, I don't know how to implement it in bash, may I do it in Swift?

I can get a sorted array of caffeinate start times and optional numbers of seconds with
```bash
#input
ps aux | grep '\d caffeinate' | sort -k14 | awk '{print $9 " " $14}'

#output
4:48PM 
4:48PM 
4:48PM 
4:56PM 1000
4:57PM 1100
```
I need to detect if there is an output without a timeout parameter and get amount of seconds from midnight plus duration for each parameter in this array.

Also I think it worth opening another PR for that command if u still want to see it implemented in bash

2020-12-03 15:50 UTC, PitNikola commented on commands/system/start-caffeinate.sh
> +  echo "Provide a number, please  ❌"
@unnamedd, good point. Added to Error Handling section in README

2020-12-06 18:23 UTC, maximkrouk commented on commands/system/start-caffeinate.sh
> +  echo "Provide a number, please  ❌"
Fixed error handling, made an argument optional, but now the script doesn't work as expected 😢
Note:
- `&` operator does not work in `caffeinate -u -t $1 &` expression, so the command blocks the execution and the message doesn't show up.
- Also I added a basic script for the longest active caffeinate command
- I updated screenshots 👆🙂

2020-12-07 09:53 UTC, PitNikola commented on commands/system/start-caffeinate.sh
> +  echo "Provide a number, please  ❌"
> & operator does not work in caffeinate -u -t $1 & expression, so the command blocks the execution and the message doesn't show up (but it works fine in terminal).

I'm gonna take a look into it.

2020-12-08 11:01 UTC, PitNikola commented
I can confirm that the process doesn't exit when using `&`, which makes this particular script a bit tricky. I'm gonna need to put this PR on hold until we find a way to deal with this. Sorry for inconvenience.

2021-01-27 14:02 UTC, thomaspaulmann commented
I'm gonna close this PR for now since we don't support it properly. We can pick it up as soon as we have support for async execution. This way we keep the PR review pipeline clean.

2021-01-27 14:02 UTC, closed without merging

2021-06-23 09:07 UTC, PitNikola commented
@maximkrouk, it seems like there is a way to resolve the async execution issue by adding `&>/dev/null` when executing caffeinate as was discovered in [this PR](https://github.com/raycast/script-commands/pull/481) 🎉