Add gitlab commands
raycast/script-commands pull request #149
Opened 2020-12-06 18:46 UTC by tonka3000

## Description

This PR adds following [GitLab](https://about.gitlab.com) commands:
- GitLab ToDo List
- Merge requests List
- GitLab Issue List 

## Type of change

- [x] New script command

## Screenshot

![GitLabRaycastCommands](https://user-images.githubusercontent.com/3163807/101289164-0d09d800-37fb-11eb-9aa5-542db22c0a7c.gif)

## Dependencies / Requirements

python3 like the sentry command

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

I've added multiple files. 3 Commands an 2 helper files. Both helper files don't have the `-` convention to be importable from a python script. The `gitlabconfig.py` contains the config which should be change by the user, so I'm not quite sure which file I should mark as template, can you give me some advise here please.

2020-12-07 20:18 UTC, thomaspaulmann requested changes
That's a wonderful addition. Could you please add a comment that folks should also copy the helper and config to make the separate command work?

2020-12-07 20:18 UTC, thomaspaulmann commented on commands/developer-utils/gitlab/gitlab-issues.template.py
> +# @raycast.mode fullOutput
We don't show the product name as part of the command. 
```suggestion
# @raycast.title Issues
# @raycast.mode fullOutput
```

2020-12-07 20:18 UTC, thomaspaulmann commented on commands/developer-utils/gitlab/gitlab-issues.template.py
> +
This doesn't have any effect when it's a `fullOutput` command.
```suggestion
```

2020-12-07 20:18 UTC, thomaspaulmann commented on commands/developer-utils/gitlab/gitlab-mergerequests.template.py
> +
Same as above
```suggestion

```

2020-12-07 20:18 UTC, thomaspaulmann commented on commands/developer-utils/gitlab/gitlab-mergerequests.template.py
> +# @raycast.title GitLab Merge requests List
Same as above.

```suggestion
# @raycast.title Merge Requests
```

2020-12-07 20:18 UTC, thomaspaulmann commented on commands/developer-utils/gitlab/gitlab-todos.template.py
> +
Same here
```suggestion
# @raycast.title To-Dos
# @raycast.mode fullOutput

```

2020-12-07 20:18 UTC, thomaspaulmann commented on commands/developer-utils/gitlab/gitlab-issues.template.py
> +# well as the GitLab instance url if it is not gitlab.com
Let's add something here that explains that you also need to copy the helper. This might be not clear for n00bs. Please apply this also to the other commands.

2020-12-07 20:20 UTC, thomaspaulmann commented
@tonka3000 thanks for this great addition. I went ahead and adjusted the command titles to our guidelines and removed the GitLab mentioning. It's the package name and shows up as the subtitle.

2020-12-07 20:30 UTC, tonka3000 commented on commands/developer-utils/gitlab/gitlab-issues.template.py
> +# well as the GitLab instance url if it is not gitlab.com
Hey, I've added the comment in line 29, but this should be moved up to "how to use the script" section. I will change that tomorrow.

2020-12-07 21:24 UTC, thomaspaulmann commented on commands/developer-utils/gitlab/gitlab-issues.template.py
> +# well as the GitLab instance url if it is not gitlab.com
Ah, I missed it in line 29. Yes, let's move it to the same section. It's easier to parse.

2020-12-08 12:38 UTC, tonka3000 commented on commands/developer-utils/gitlab/gitlab-issues.template.py
> +# well as the GitLab instance url if it is not gitlab.com
hey @thomaspaulmann , I've moved the config description to the `How to use this script?` section

2020-12-08 14:16 UTC, thomaspaulmann commented on commands/developer-utils/gitlab/gitlab-mergerequests.template.py
> +# Optional parameters:
```suggestion

# Optional parameters:
```

2020-12-08 14:17 UTC, thomaspaulmann commented
Thanks for the quick fixes @tonka3000 👏

2020-12-08 14:17 UTC, merged