Add Script Command: play-movie
raycast/script-commands pull request #164
Opened 2020-12-10 21:41 UTC by crstauf

## Description

Play specified movie in TV.

## Type of change

- [x] New script command

## Screenshot

<img width="770" alt="Screen Shot 2020-12-10 at 4 40 32 PM" src="https://user-images.githubusercontent.com/4573033/101833101-785aef00-3b06-11eb-9047-14496903c977.png">

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2020-12-11 00:12 UTC, thomaspaulmann requested changes
I tried the AppleScript but it didn't work for me. I fixed the syntax error but get an execution error that I can't decrypt. Any idea how to make it work?

2020-12-11 00:12 UTC, thomaspaulmann commented on commands/media/apple-tv/apple-tv-play-movie.applescript
> +end run
This script doesn't seem to work. Changing it to the following makes it run but I get the following execution error: `TV got an error: Can’t make some data into the expected type. (-1700)`

```suggestion
on run argv
  tell application "TV"
    play track (item 1 of argv)
  end tell
end run
```

2020-12-11 00:12 UTC, thomaspaulmann commented on commands/media/apple-tv/apple-tv-play-movie.applescript
> +## Contributions welcome to also play TV shows.
Lets remove this. Not sure if that is really needed.

2020-12-11 00:43 UTC, crstauf commented on commands/media/apple-tv/apple-tv-play-movie.applescript
> +## Contributions welcome to also play TV shows.
Not needed, but wanted.

2020-12-11 00:45 UTC, crstauf commented
I'll double check that it matches my local version, which I know works. Don't know why they wouldn't match, but I'll double check.

2020-12-11 00:52 UTC, crstauf commented
@thomaspaulmann The movie name you typed in... was it one word or multiple?

2020-12-11 01:17 UTC, crstauf commented
Hmm, after playing with it, I can't get it back to working. 😕 

If I can't stabilize it within the next week I'll close.

2020-12-11 01:25 UTC, crstauf commented on commands/media/apple-tv/apple-tv-play-movie.applescript
> +end run
@thomaspaulmann I just tried every movie in my library, and every single one worked:
- single word titles
- multi-word titles
- titles with special characters

(I was honestly surprised when `Mission: Impossible - Ghost Protocol` started playing.)

Can you please provide the movie titles you entered that failed?

2020-12-11 15:53 UTC, thomaspaulmann commented on commands/media/apple-tv/apple-tv-play-movie.applescript
> +end run
I entered `pulp fiction` and it returned the error. Might be worth to do a try-catch-block around the play method and give a nicer error message, e.g. "Move not found" and exit with status code 1. 

This would give the user a better result. Also, I don't use Apple TV heavily :-)

2020-12-11 15:53 UTC, thomaspaulmann commented
> @thomaspaulmann The movie name you typed in... was it one word or multiple?

Added a comment on our discussion.

2020-12-12 11:54 UTC, thomaspaulmann commented
Thanks for adding the try-catch-block. It's a much nicer user-facing error message that the underlying error provides.

2020-12-12 11:54 UTC, merged