Add Script Command:Search in Zhihu,Search in Baidu,Bear,Dash
raycast/script-commands pull request #168
Opened 2020-12-27 03:39 UTC by Jax0rz

Signed-off-by: JY <ithinkinx7@gmail.com>

## Description

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

## Dependencies / Requirements

## Checklist

- [ ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2020-12-28 15:33 UTC, unnamedd requested changes
Hi @Jax0rz, thanks a lot for your contribution.

2020-12-28 15:33 UTC, unnamedd commented on commands/navigation/trash-downloads.applescript
> +   do shell script "rm -fR " & quoted form of (POSIX path of myItem)
It is very dangerous to use `rm -fR` here, because `rm` commands to not send any file to the trash can, making it impossible to recover some file in case of accident. I suggest you to find a way to delete the files from `~/Downloads` sending them to the Trash can.

2020-12-28 15:33 UTC, unnamedd commented on commands/system/dark-mode-toggle.applescript
> +#!/usr/bin/osascript
This script command already exist in this repository, you can check it out here: https://github.com/raycast/script-commands/blob/master/commands/system/toggle-system-appearance.applescript

2020-12-28 15:33 UTC, unnamedd commented on commands/web-searches/bear.sh
> +open "bear://x-callback-url/search?term=${1// /%20}&show_window=yes&token=979709-0C37A6-F84D4D"
As your are not web searching anything in this Script Command, I suggest you to follow the way used before and move it to `Navigation`, where you will be able to find a similar Script Command which will open an app in the system in case of the user have it installed. Check it out this Script Command: https://github.com/raycast/script-commands/blob/master/commands/navigation/open-desktop-url-from-clipboard.swift

And of course, do not forget to add the metatag `@raycast.packageName` to `Navigation`.

2020-12-28 15:33 UTC, unnamedd commented on commands/web-searches/duck-duck-go.sh
>  open "https://duckduckgo.com/?q=${1// /%20}"
If you are going to add the `percentEncoded` to the argument, you will need to change the `open` instruction to:
```suggestion
open "https://duckduckgo.com/?q=$1"
```

2020-12-28 15:33 UTC, unnamedd commented on commands/developer-utils/dash.sh
> +#!/bin/bash
Personally speaking, I guess this is more related to `Navigation` than `Developer Utils`. What do you think @thomaspaulmann and @PitNikola?

2020-12-28 15:33 UTC, unnamedd commented on commands/web-searches/google-search.sh
>  open "https://www.google.com/search?q=${1// /%20}"
```suggestion
open "https://www.google.com/search?q=$1"
```

2020-12-28 15:33 UTC, unnamedd commented on commands/web-searches/search-in-baidu.sh
> +open "https://www.baidu.com/s?wd=${1// /%20}"
```suggestion
open "https://www.baidu.com/s?wd=$1"
```

2020-12-28 15:33 UTC, unnamedd commented on commands/web-searches/search-in-taobao.sh
> +open "https://s.taobao.com/search?q=${1// /%20}"
```suggestion
open "https://s.taobao.com/search?q=$1"
```

2020-12-28 15:33 UTC, unnamedd commented on commands/web-searches/search-in-zhihu.sh
> +open "https://www.zhihu.com/search?type=content&q=${1// /%20}"
```suggestion
open "https://www.zhihu.com/search?type=content&q=$1"
```

2020-12-28 15:33 UTC, unnamedd commented on commands/web-searches/youtube.sh
>  open "https://www.youtube.com/results?search_query=${1// /%20}"
```suggestion
open "https://www.youtube.com/results?search_query=$1"
```

2020-12-28 19:12 UTC, thomaspaulmann commented on commands/navigation/trash-downloads.applescript
> +   do shell script "rm -fR " & quoted form of (POSIX path of myItem)
You can also use the `needsConfirmation` parameter to show an alert before executing the script. This helps to raise awareness that this is a destructive action.

2020-12-29 08:50 UTC, Jax0rz commented on commands/system/dark-mode-toggle.applescript
> +#!/usr/bin/osascript
thanks,I've removed the duplicated script

2020-12-29 09:17 UTC, Jax0rz commented on commands/navigation/trash-downloads.applescript
> +   do shell script "rm -fR " & quoted form of (POSIX path of myItem)
I've rewrite a script.

2020-12-29 09:20 UTC, Jax0rz commented on commands/web-searches/bear.sh
> +open "bear://x-callback-url/search?term=${1// /%20}&show_window=yes&token=979709-0C37A6-F84D4D"
Resolved.

2020-12-29 11:44 UTC, unnamedd commented on commands/navigation/new-file.applescript
> +end tell
Move this one to System, it will fit better there than here in Navigation.

2020-12-29 11:45 UTC, unnamedd commented on commands/navigation/trash-downloads.applescript
> +end tell
Move also this one to System.

2020-12-29 12:37 UTC, unnamedd commented on commands/navigation/bear.sh
> +open "bear://x-callback-url/search?term=${1// /%20}&show_window=yes&token=979709-0C37A6-F84D4D"
@Jax0rz we have one last thing to do here

**What to do:**
```suggestion
open "bear://x-callback-url/search?term=$1&show_window=yes&token=979709-0C37A6-F84D4D"
```


As the user will need to it's own token, you will have to follow the instructions defined in the guideline. Check it out here: https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-additional-modification

2020-12-29 12:38 UTC, unnamedd commented on commands/system/trash-downloads.applescript
> +   move allDownloads to trash
Great solution! Thanks 🙂

2020-12-30 12:19 UTC, PitNikola requested changes
Thanks for your contribution! Quite a lot of commands here 😅
Generally I would suggest splitting it into multiple PRs in the future to make it easier to review.

2020-12-30 12:19 UTC, PitNikola commented on commands/navigation/bear.sh
> +open "bear://x-callback-url/search?term=$1&show_window=yes&token=979709-0C37A6-F84D4D"
Seems like this script requires additional modification in order to run. That means it should be a template, please refer to [this section of the guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-additional-modification) to see how to handle these kinds of scripts.

Here's an example of template script: https://github.com/raycast/script-commands/blob/master/commands/communication/slack/clear-slack-status.template.sh

2020-12-30 12:19 UTC, PitNikola commented on commands/navigation/bear.sh
> +# @raycast.title Bear
```suggestion
# @raycast.title Search in Bear
```

2020-12-30 12:19 UTC, PitNikola commented on commands/navigation/bob.applescript
> +# @raycast.title Bob
```suggestion
# @raycast.title Translate in Bob
```

2020-12-30 12:19 UTC, PitNikola commented on commands/navigation/dash.sh
> +# @raycast.title Dash
```suggestion
# @raycast.title Search in Dash
```

2020-12-30 12:19 UTC, PitNikola commented on commands/navigation/dash.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "Keyword" }
I would assume this argument needs percentEncoding as well?

2020-12-30 12:19 UTC, PitNikola commented on commands/system/trash-downloads.applescript
> +# @raycast.packageName System
Let's add  `@raycast.needsConfirmation true`, it's rather destructive operation and you wouldn't want it to run accidentally.

2020-12-30 12:19 UTC, PitNikola commented on commands/system/new-file.applescript
> +# @raycast.title New File
```suggestion
# @raycast.title Create New File in Finder
```

2020-12-30 12:19 UTC, PitNikola commented on commands/system/new-file.applescript
> +# @raycast.title New File
Could you please add a description for this script so it's clear to others what exactly it does.

2020-12-30 12:19 UTC, PitNikola commented on commands/navigation/bear.sh
> +# @raycast.title Bear
Here and in other commands I'm suggesting more descriptive names that follow Raycast's style of naming.
I would also recommend renaming files, e.g. `bear.sh` to `search-in-bear.sh`

2020-12-30 12:19 UTC, PitNikola commented on commands/system/trash-downloads.applescript
> +# @raycast.title Trash Downloads
```suggestion
# @raycast.title Move Downloads to Trash
```

2020-12-30 13:48 UTC, Jax0rz commented on commands/navigation/bear.sh
> +open "bear://x-callback-url/search?term=$1&show_window=yes&token=979709-0C37A6-F84D4D"
the token is not required ,I've removed it.

2020-12-30 17:02 UTC, PitNikola commented
@Jax0rz, seems like there are some conflicts. Would you mind rebasing on master first before I merge it?

2020-12-30 17:04 UTC, Jax0rz commented
> @Jax0rz, seems like there are some conflicts. Would you mind rebasing on master first before I merge it?

never mind

2020-12-30 18:38 UTC, unnamedd commented on commands/navigation/bear.sh
> +open "bear://x-callback-url/search?term=$1&show_window=yes&token=979709-0C37A6-F84D4D"
@Jax0rz, you don't have to remove the `@raycast.description`. It will be better if you add it back.

2021-01-01 12:30 UTC, Jax0rz reviewed
updated

2021-01-04 08:09 UTC, PitNikola commented
@Jax0rz, could you please rebase your branch on top of Raycast's master to resolve conflicts?

2021-01-04 08:10 UTC, PitNikola requested changes
@Jax0rz, could you please rebase your branch on top of Raycast's master to resolve conflicts?

2021-01-04 15:45 UTC, closed without merging