Add command to sample a colour from the screen (#166)
raycast/script-commands pull request #172
Opened 2021-01-04 23:15 UTC by jesse-c

## Description

Add command to check if a website is up or not.

## Type of change

- [x] New script command

## Screenshot

<img width="782" alt="image" src="https://user-images.githubusercontent.com/1405676/103589154-b5868700-4ee2-11eb-8e3d-0dee91c1b1a7.png">

## Dependencies / Requirements

N/A

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-05 12:36 UTC, thomaspaulmann requested changes
Script looks good. I've added some inline comments, nothing major. Most importantly, is it necessary to execute the script from `~`? This could be different on user machines but I also don't see anything that would prevent somebody to execute it from somewhere else. If not, I would remove the `currentWorkingDirectory` parameter.

2021-01-05 12:36 UTC, thomaspaulmann commented on commands/developer-utils/is-it-up.sh
> +
Let's add a hint that this script uses a dependency as described in the contribution guidelines even though `jq` is a rather common one.
```suggestion

# Dependency: This script requires `jq` cli installed: https://stedolan.github.io/jq/
# Install via homebrew: `brew install jq`

```

2021-01-05 12:36 UTC, thomaspaulmann commented on commands/developer-utils/is-it-up.sh
> +# @raycast.mode compact
Could also be neat to have as an `inline` script for specific websites that you want to keep observing.

2021-01-05 12:36 UTC, thomaspaulmann commented on commands/developer-utils/is-it-up.sh
> +# @raycast.needsConfirmation false
The default value is `false`. You can remove the parameter.

```suggestion
```

2021-01-05 12:36 UTC, thomaspaulmann commented on commands/developer-utils/is-it-up.sh
> +# @raycast.currentDirectoryPath ~
Is this necessary? I assume that the script works from every directory?

2021-01-05 13:42 UTC, jesse-c commented on commands/developer-utils/is-it-up.sh
> +# @raycast.needsConfirmation false
Done.

2021-01-05 13:42 UTC, jesse-c commented on commands/developer-utils/is-it-up.sh
> +# @raycast.currentDirectoryPath ~
It would! I've removed it.

2021-01-05 13:43 UTC, jesse-c commented on commands/developer-utils/is-it-up.sh
> +# @raycast.mode compact
It would! I guess people could copy the script and remove the argument?

2021-01-06 09:17 UTC, thomaspaulmann commented on commands/developer-utils/is-it-up.sh
> +# @raycast.mode compact
Yeah, let them be creative 🎨

2021-01-06 09:18 UTC, merged