Slack: set Spotify song as slack status
raycast/script-commands pull request #174
Opened 2021-01-05 20:13 UTC by alongat

## Description

I ported a script I had that set Slack status to the current song playing in Spotify, 
plus since we're all WFH these days when it clears the status, it sets the status_emoji to either :office: or :house_with_garden: according to the WiFi name.

## Type of change

- [X] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

![Kapture 2021-01-05 at 22 03 54](https://user-images.githubusercontent.com/12812096/103693538-1fb23100-4fa2-11eb-8689-777406c3b986.gif)

## Dependencies / Requirements

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-05 20:19 UTC, alongat commented
Looks like I needed to use `inline` and not `compact` for refreshTime to work (so the gif is showing the `compact` mode)

2021-01-07 11:23 UTC, thomaspaulmann commented
Thanks for the script command. That's quite an advanced one! Cool idea to let your co-workers know about your music taste :-) I was wondering if it makes sense to split the command into two. One for the status update of the song and the other for the Wifi handling. The separate commands seem more applicable to more users. What do you think?

2021-01-07 16:36 UTC, alongat commented
@thomaspaulmann Sure! sounds reasonable :) will do.

2021-01-07 21:25 UTC, thomaspaulmann commented
Cool! Looking forward to the split commands.

2021-01-07 23:41 UTC, thomaspaulmann requested changes
As discussed, let's split this command into multiple ones to make it more suitable for wider adoption.

2021-01-16 20:13 UTC, alongat commented
@thomaspaulmann updated as discussed 💪 indeed much cleaner

2021-01-17 18:26 UTC, thomaspaulmann requested changes
Thanks for splitting. Much better now that the functionality is decoupled. I left some minor comments to make the commands stand out. I would suggest adding a Slack logo to the repo that you can reference.

2021-01-17 18:26 UTC, thomaspaulmann commented on commands/communication/slack/set-slack-status-spotify.sh
> +# @raycast.icon ../../media/images/spotify-logo.png
Tricky. I was wondering if we should rather take the Slack logo here since it changes the Slack status. Then you can also reference it easier. If not, you might want to copy the Spotify logo closer to the script to make sure that it's easy for others to copy.

2021-01-17 18:26 UTC, thomaspaulmann commented on commands/communication/slack/set-slack-wfh-status.sh
> +# @raycast.packageName Slack
Let's set an icon to make sure that the command looks nice :-) Since this is Slack, I would use the Slack logo. Alternatively you can just use an emoji? Maybe 🏡?

2021-01-24 20:51 UTC, alongat commented on commands/communication/slack/set-slack-wfh-status.sh
> +# @raycast.packageName Slack
added slack logo on both 💪 
(sorry for the long response cycle too much work during the week 😅 )

2021-01-25 13:28 UTC, thomaspaulmann commented on commands/communication/slack/set-slack-wfh-status.sh
> +# @raycast.packageName Slack
All good. Happy that we got it sorted.

2021-01-25 13:28 UTC, thomaspaulmann approved these changes

2021-01-25 13:39 UTC, merged