Add commands to quickly change the default browser
raycast/script-commands pull request #175
Opened 2021-01-06 15:49 UTC by marcklingen

## Description

Quickly change the default browser via script command. Opted for a single script per browser to make switches faster.

## Type of change

- [x] New script command

## Screenshot

https://user-images.githubusercontent.com/2834609/103788054-b46a6c80-503e-11eb-935b-ff2efcd91af2.mov

## Dependencies / Requirements

Requires [defaultbrowser](https://github.com/kerma/defaultbrowser/), available via homebrew (`brew install defaultbrowser`)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-06 16:30 UTC, unnamedd commented
Hi @marcklingen, thanks for your contribution. 

As we have a bot to create a nice documentation for the Script Commands, I need to ask you: any special reason to not use the metatags `@raycast.author <Your Name>` and `@raycast.authorURL <your URL>`?

2021-01-06 16:39 UTC, marcklingen commented
Thanks for the hint @unnamedd. Just added the metatags as there wasn't a special reason

2021-01-06 16:42 UTC, unnamedd commented
You're welcome @marcklingen! :D

2021-01-06 17:38 UTC, unnamedd commented on commands/browsing/default-browser-chrome.sh
> +defaultbrowser chrome
@marcklingen based on this guideline’s section “[Scripts that require installation of runtimes and dependencies](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-runtimes-and-dependencies)”, would you please add the validation for the `defaultbrowser` in all scripts?

```suggestion
if ! command -v defaultbrowser &> /dev/null; then
    echo "defaultbrowser command is required (https://github.com/kerma/defaultbrowser).";
    exit 1;
fi 

defaultbrowser chrome
```

2021-01-06 17:41 UTC, unnamedd commented
One last thing before I forget, all your Script Commands will fit better inside of `system` folder instead of `browsing`.

2021-01-06 21:45 UTC, thomaspaulmann requested changes

2021-01-06 21:45 UTC, thomaspaulmann commented on commands/browsing/default-browser-chrome.sh
> +defaultbrowser chrome
Looking into the dependency it doesn't do much. Might be easy to build the same in Swift as a script command. Not a requirement though.

https://github.com/kerma/defaultbrowser/blob/master/src/main.m

2021-01-12 23:53 UTC, marcklingen commented on commands/browsing/default-browser-chrome.sh
> +defaultbrowser chrome
Thank you @unnamedd and @thomaspaulmann for your feedback.

I added the validation (sorry for that) and moved the scripts to the `system` directory. I had a look at the dependency as well as it is rather simple. Unfortunately, I have no experience with Swift to replace it. Maybe this can be done by someone else if the script is useful for others.

2021-01-27 14:04 UTC, thomaspaulmann commented
Oh totally missed he updates. For next time, @marcklingen make sure to re-request a review. All things look good and I'm gonna merge the commands. Thanks again for the changes!

2021-01-27 14:04 UTC, merged