feat: add Wi-Fi and Bluetooth toggle script
raycast/script-commands pull request #177
Opened 2021-01-07 22:26 UTC by vincentdoerig

## Description

Adds two system scripts, one that turns your wifi on/off based on 

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

Wi-Fi:
![image](https://user-images.githubusercontent.com/24668338/103951691-76a13d00-513f-11eb-813c-80b335ac4983.png)
Bluetooth:
![image](https://user-images.githubusercontent.com/24668338/103951789-9b95b000-513f-11eb-8ff6-00642130339e.png)

## Dependencies / Requirements

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-07 23:40 UTC, thomaspaulmann requested changes
Hey @vincentdoerig, thanks a lot for the contribution. Especially the bluetooth command will make @pacocoursey happy :-) Unfortunately, the command doesn't work on macOS Big Sur. Any chance you could fix it to make sure that it works for users on the latest OS? If there is something to manually adjust, e.g. naming of some processes, I recommend to extract those to properties and add a comment for users to simply adopt it to their local setup.

I added some inline comments. Could you also re-name the script files to `toggle-bluetooth` and `toggle-wifi`? It makes clearer what the commands do and leave room for other wireless connection related commands.

Thanks again for this great contribution! 🎉

2021-01-07 23:40 UTC, thomaspaulmann commented on commands/system/bluetooth.applescript
> +    set BluetoothSwitch to checkbox "Bluetooth" of group 1 of window "Control Centre"
Mmh... Looks like this line makes trouble on macOS Big Sur:

```
execution error: System Events got an error: Can’t get group 1 of window "Control Centre" of process "ControlCenter". Invalid index. (-1719)
```

Any idea on how to fix this?

2021-01-07 23:40 UTC, thomaspaulmann commented on commands/system/bluetooth.applescript
> +    set BluetoothSwitch to checkbox "Bluetooth" of group 1 of window "Control Centre"
There is also the possibility to reverse-engineer how [blueutil](https://github.com/toy/blueutil/blob/master/blueutil.m) works and write a short Swift script that toggles Bluetooth.

2021-01-07 23:40 UTC, thomaspaulmann commented on commands/system/wifi.applescript
> +# @raycast.title Wi-Fi
Let's be consistent with the naming of the command for Bluetooth and others in this repo.
```suggestion
# @raycast.title Toggle Wi-Fi
```

2021-01-07 23:40 UTC, thomaspaulmann commented on commands/system/wifi.applescript
> +# @raycast.argument1 { "type": "text", "placeholder": "on/off" }
I would drop this input and make it toggle, similar to the Bluetooth one. It's usually simpler to execute it.

2021-01-07 23:40 UTC, thomaspaulmann commented on commands/system/wifi.applescript
> +    do shell script "networksetup -setairportpower en1 off"
Is it always `en1`? If not, I would recommend extracting this as a property and add a comment how to find out what to put there. This way it's easy for others to adjust the script to their local setup.

2021-01-08 00:33 UTC, unnamedd commented on commands/system/bluetooth.applescript
> +    set BluetoothSwitch to checkbox "Bluetooth" of group 1 of window "Control Centre"
> Mmh... Looks like this line makes trouble on macOS Big Sur:
> 
> ```
> execution error: System Events got an error: Can’t get group 1 of window "Control Centre" of process "ControlCenter". Invalid index. (-1719)
> ```
> 
> Any idea on how to fix this?

There's a problem in this kind of approach and I already discussed it with Petr. It is related to the language. You're using the UK grammar (Control Centre) and Valentin configured the text using the US grammar (Control Center). Every user who decides to use those scripts will have to "translate" the strings to their own language, i.e: spanish, portuguese, italian and so on. The invalid index confirms that to me.

2021-01-08 00:35 UTC, unnamedd commented on commands/system/wifi.applescript
> +    do shell script "networksetup -setairportpower en1 off"
Not always Thomas. In my laptop, the WiFi is configured on `en0`.

2021-01-08 06:56 UTC, vincentdoerig commented on commands/system/bluetooth.applescript
> +    set BluetoothSwitch to checkbox "Bluetooth" of group 1 of window "Control Centre"
yes, @unnamedd is correct. The error is because of the different language localisations (I'm using british english, hence the _centre_). What's the best approach to inform the user to edit the script according to their language?

2021-01-08 07:26 UTC, vincentdoerig commented on commands/system/wifi.applescript
> +# @raycast.argument1 { "type": "text", "placeholder": "on/off" }
Right, I changed it to toggle, however I imagine we will run into localisation problems again, since we check if the response from `networksetup -getairportnetwork [interface]` contains the word "off".

2021-01-08 11:24 UTC, thomaspaulmann commented on commands/system/wifi.applescript
> +# @raycast.argument1 { "type": "text", "placeholder": "on/off" }
Not sure if the CLI tool `networksetup` is localized. I would expect that it always returns on/off.

2021-01-08 11:26 UTC, vincentdoerig commented on commands/system/wifi.applescript
> +# @raycast.argument1 { "type": "text", "placeholder": "on/off" }
Alright, great! Then it shouldn't be a problem.

2021-01-08 13:38 UTC, thomaspaulmann commented on commands/system/bluetooth.applescript
> +    set BluetoothSwitch to checkbox "Bluetooth" of group 1 of window "Control Centre"
Mmh... If we can't make it language-agnostic, I would vouch for extracting the strings as constants and add a comment that explains on how to get the names.

2021-01-09 11:03 UTC, vincentdoerig commented on commands/system/bluetooth.applescript
> +    set BluetoothSwitch to checkbox "Bluetooth" of group 1 of window "Control Centre"
I can't think of a command or something else that would return the names in a specific language. Any ideas?

2021-01-10 16:29 UTC, thomaspaulmann commented on commands/system/bluetooth.applescript
> +    set BluetoothSwitch to checkbox "Bluetooth" of group 1 of window "Control Centre"
Me neither. I think this script just needs a custom setup depending on the users locale. For this kind of script commands, we name them with `template` in the filename to make sure that folks need to configure them, e.g. `toggle-wifi.template.applescript`. Raycast doesn't show scripts that include `template` in the filename.

As mentioned, let's just extract the language-dependent bits of the script into constants at the top of the script and add a comment there that describes on how to find out what to put there.

2021-01-10 16:30 UTC, thomaspaulmann commented on commands/system/wifi.applescript
> +# Wi-Fi interface, should normally be either `en0` or `en1`
How do you find out if it's `en0` or `en1` or something else? Opening the `Network` preferences?

2021-01-10 17:23 UTC, vincentdoerig commented on commands/system/wifi.applescript
> +# Wi-Fi interface, should normally be either `en0` or `en1`
option click on the wifi icon in the menu bar shows it 
![image](https://user-images.githubusercontent.com/24668338/104130415-ed714c80-5370-11eb-9c9d-1d339a45c828.png)

2021-01-10 17:24 UTC, vincentdoerig commented on commands/system/bluetooth.applescript
> +    set BluetoothSwitch to checkbox "Bluetooth" of group 1 of window "Control Centre"
👍 will do in the next couple of days or so

2021-01-10 20:12 UTC, unnamedd commented on commands/system/wifi.applescript
> +# Wi-Fi interface, should normally be either `en0` or `en1`
The other way is running `ifconfig` on terminal and checking which interface has any IP (inet) defined.

2021-01-10 20:14 UTC, unnamedd commented on commands/system/wifi.applescript
> +# Wi-Fi interface, should normally be either `en0` or `en1`
Example: 
![image](https://user-images.githubusercontent.com/83694/104134239-adb65f00-5388-11eb-8189-5d11ccf698c7.png)
![image](https://user-images.githubusercontent.com/83694/104134252-bdce3e80-5388-11eb-880e-7b32095e3da4.png)

2021-01-10 23:26 UTC, thomaspaulmann commented on commands/system/wifi.applescript
> +# Wi-Fi interface, should normally be either `en0` or `en1`
Ok cool. Let's add one of those ways to check the name of the interface to the comment.

2021-01-11 23:12 UTC, thomaspaulmann approved these changes
Thanks for adding the comments and doing all the changes. Let's get this change landed.

2021-01-11 23:12 UTC, merged