Created AppleScript to automate toggling greyscale
raycast/script-commands pull request #178
Opened 2021-01-07 23:42 UTC by MattAlp

## Description

This script uses AppleScript automation to toggle the greyscale colour filter in accessibility settings.

## Type of change

- [x] New script command

## Screenshot

The greyscale colour change does not get picked up by software, but the automation flow is visible.

https://user-images.githubusercontent.com/19317416/103956822-4d6cb680-5117-11eb-89c0-9290e66884a8.mov

## Dependencies / Requirements

**N/A**

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-08 13:51 UTC, thomaspaulmann commented
Thanks @MattAlp for this first contribution. Is there any way to not run/show the `System Preferences` when executing the script? It kinda feels weird. I found [this project](https://github.com/rkbhochalya/grayscale-mode) that uses some C functions from Apple to toggle the grayscale mode. Maybe there is a way to write a script that uses this functions? Then this command would feel like magic :-)

2021-01-08 21:30 UTC, MattAlp commented
Yeah, I'll whip up the changes in a bit

On Fri, 8 Jan 2021 at 08:51, Thomas Paul Mann <notifications@github.com>
wrote:

> Thanks @MattAlp <https://github.com/MattAlp> for this first contribution.
> Is there any way to not run/show the System Preferences when executing
> the script? It kinda feels weird. I found this project
> <https://github.com/rkbhochalya/grayscale-mode> that uses some C
> functions from Apple to toggle the grayscale mode. Maybe there is a way to
> write a script that uses this functions? Then this command would feel like
> magic :-)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/raycast/script-commands/pull/178#issuecomment-756765475>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AETMFKFMWTS5BKKP5EDDVL3SY4EWBANCNFSM4VZWCBIQ>
> .
>

2021-01-10 16:26 UTC, thomaspaulmann commented
Cool, I wait for the second iteration and set the PR to "request changes". I've your done, just re-request a review from me and I'll take a second look. If it isn't possible without a AppleScript, we can also commit that one and maybe iterate on it.

2021-01-10 16:26 UTC, thomaspaulmann requested changes
As discussed, I request changes on this PR and and let @MattAlp work on a second iteration.

2021-01-27 14:05 UTC, thomaspaulmann commented
@MattAlp any updates on this?

2021-01-31 20:43 UTC, thomaspaulmann commented
I'm closing the PR for now because it got stale. @MattAlp feel free to re-open it as soon as you've looked into the bespoken changes.

2021-01-31 20:43 UTC, closed without merging