Completion messages for scripts in dev utils added
raycast/script-commands pull request #19
Opened 2020-10-31 13:24 UTC by japanese-goblinn

2020-10-31 15:26 UTC, crstauf commented
@japanese-goblinn Doesn't the script mode needs to be changed to `compact` in order for the completion message to be displayed?

2020-10-31 15:46 UTC, japanese-goblinn commented
> @japanese-goblinn Doesn't the script mode needs to be changed to `compact` in order for the completion message to be displayed?

I guess no, completion message is showing up. In `compact` mode `Raycast` window will not closed and in my opinion this is not an appropriate behavior for this kind of scripts.

<img width="363" alt="Screen Shot 2020-10-31 at 18 42 28" src="https://user-images.githubusercontent.com/33631005/97783495-42425b00-1ba9-11eb-966c-61f2943e5844.png">

2020-10-31 15:53 UTC, crstauf commented
> I guess no, completion message is showing up.

Oh cool!!! 😎 Didn't know that was possible.

2020-11-03 12:58 UTC, unnamedd requested changes
Changes on the metadata is needed, to make these changes effective.

2020-11-03 12:58 UTC, unnamedd commented on developer-utils/decode-base64.sh
> +echo "Decoded"
To make this echo be visible, you need to change the metatag `@raycast.mode` to `compact` instead of the current `silent`. 

This comment applies for the next two files (`encode-base64.sh` and `generate-uuid.sh`).

2020-11-03 13:44 UTC, japanese-goblinn commented
Are you sure about this? Don't you think that this change will break script workflow, because now user need to manually close window to paste the result?

2020-11-03 15:19 UTC, unnamedd commented
The only reason for me to suggest that is I used to expect the result on the same place. The HUD is amazing, for sure, but in my case, I use three huge monitors, so won’t be easy for me to see that HUD. At least, I will see result on the result box and if I decide to do anything else, Raycast is already opened.

2020-11-03 21:55 UTC, thomaspaulmann commented
I think we should keep the `silent` mode for these utility scripts. The `HUD` completion message is a neat addition to give the user the verification that the command was successful. `Compact` mode wouldn't be the right approach here because most likely you don't continue in Raycast after a conversion and rather go to some other tool, e.g. the terminal to paste in your decoded content. Gonna merge it and thanks to @japanese-goblinn for your first contribution. Super appreciated!

2020-11-03 21:55 UTC, merged