Improve Toolkit Documentation
raycast/script-commands pull request #191
Opened 2021-01-17 21:31 UTC by Matt-Gleich

## Description

Vastly improved the toolkit docs by giving an explanation of what the toolkit does and detailed steps on how to contribute.

## Type of change

- [ ] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [x] Documentation update
- [x] Toolkit change
- [ ] Other (Specify)

## Screenshot

N/A

## Dependencies / Requirements

N/A

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-17 21:32 UTC, Matt-Gleich commented
cc @unnamedd

2021-01-19 10:52 UTC, PitNikola commented
@unnamedd, leaving this one to you. Feel free to merge.

2021-01-19 10:59 UTC, unnamedd commented
> @unnamedd, leaving this one to you. Feel free to merge.

I'm still going to review it! ;)

2021-01-26 21:47 UTC, unnamedd requested changes
@Matt-Gleich thanks a lot for your improvement to our documentation! We all really appreciated!

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +Raycast's toolkit is a command-line program for automating certain repetitive tasks in this repo. At the moment the toolkit just automates the generation of the [README for the script-commands](../..
```suggestion
Raycast Toolkit is a command-line application for automating repetitive tasks in this repo. At the moment the Toolkit automates the generation of the [Awesome Script Commands](../../commands/README.md) and the  (extensions.json)[../../extensions.json] which contains information about each Script Command.
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +The Toolkit uses the [swift programming language](https://developer.apple.com/swift/), the [swift package manager](https://swift.org/package-manager/), and [Apple's argument parser for parsing argume
```suggestion
- (Swift)[https://developer.apple.com/swift] 5.3
- [Swift Package Manager](https://github.com/apple/swift-package-manager/)
- [Swift Argument Parser](https://github.com/apple/swift-argument-parser)
- [SwiftLint](https://github.com/realm/SwiftLint)
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +│   ├── Toolkit - Command-line tool that calls the ToolkitLibrary to automate certain tasks
```suggestion
│   ├── Toolkit - Command-line Interface tool that make calls to ToolkitLibrary. This is the interface used by the user or by the CI.
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +│   │   ├── Extensions - Custom swift extensions specific to the CLI
```suggestion
│   │   ├── Extensions - Custom Swift extensions specific to the CLI
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +│   │   └── SubCommands - Sub-commands such as version
```suggestion
│   │   └── SubCommands - Sub-commands are the interfaces that are exposed to the user
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +│   └── ToolkitLibrary - Most features of the toolkit
```suggestion
│   └── ToolkitLibrary - The main library
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +│       │   ├── Documentation - Documentation generation for markdown and JSON
```suggestion
│       │   ├── Documentation - Documentation generation for Markdown and JSON
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +│       │   └── Toolkit - Public and easy to use version of the Toolkit
```suggestion
│       │   └── Toolkit - Contains the public interface which will be consumed by the Toolkit CLI
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +│       ├── Errors - Errors for the toolkit
```suggestion
│       ├── Errors - Errors for the Toolkit
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +│       ├── Extensions - Custom swift extensions
```suggestion
│       ├── Extensions - Custom Swift extensions
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +│       └── Protocols - Custom swift protocols
```suggestion
│       └── Protocols - Custom Swift protocols
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/CONTRIBUTING.md
> +This will automatically install the swift packages for you.
```suggestion
Xcode will automatically download the Swift Packages for you.
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/README.md
> +The Toolkit runs on every push to master using [this GitHub action workflow](../../.github/workflows/documentation.yml). That workflow goes through the following process:
```suggestion
The Toolkit runs on every push to master using [this GitHub Action workflow](../../.github/workflows/documentation.yml). That workflow goes through the following process:
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/README.md
> +2. Build the toolkit into a binary located at the root of the repo
```suggestion
2. Build the Toolkit using the [Makefile](../../Makefile) located at the root of the repo
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/README.md
> +4. Pushes the changes to the master branch.
```suggestion
4. Pushes the changes to the master branch using Raycast Bot.
```

2021-01-26 21:47 UTC, unnamedd commented on Tools/Toolkit/README.md
> +We would love to have your contribution! Check out our [CONTRIBUTING.md file to get started](CONTRIBUTING.md).
```suggestion
We would love to have your contribution! Check out our [CONTRIBUTING.md](CONTRIBUTING.md) file to get started.
```

2021-01-27 14:00 UTC, thomaspaulmann requested changes
I'm putting this back in your queue @Matt-Gleich to address the comments from @unnamedd. Then, we can merge it.

2021-02-03 09:53 UTC, unnamedd approved these changes
@Matt-Gleich after your changes, the documentation looks great to me. 
Thanks a lot!

2021-02-03 09:53 UTC, unnamedd commented
@thomaspaulmann this PR is ready to be merged!

2021-02-03 22:10 UTC, merged

2021-02-03 22:11 UTC, thomaspaulmann commented
Merged and thanks for the great work both of you 👏 It's a pleasure having you as part of our community.