Add some documentation features
raycast/script-commands pull request #192
Opened 2021-01-17 22:16 UTC by Matt-Gleich

Signed-off-by: Matthew Gleich <email@mattglei.ch>

## Description

Added the following:

1. A fancy header to the main README.
2. A table of contents to the main README and the main CONTRIBUTING doc.
3. Refactored all markdown links to link to local files instead of the repo.

## Type of change

- [ ] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [x] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

Ohhh so fancy

![Screen Shot 2021-01-17 at 5 15 29 PM](https://user-images.githubusercontent.com/43759105/104857595-9d056c00-58e7-11eb-9495-b07fbedad90b.png)

## Dependencies / Requirements

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-26 16:53 UTC, PitNikola requested changes
Hey @Matt-Gleich, thanks so much for making this suggestion and sorry it took a while to review it. Generally looks great, I just have few suggestions:
- Since GitHub now support dark mode, using light variant of our logo might not look good there. Let's use our current app icon since it's theme agnostic. Here's png at 1024px. Feel free to resize to smaller size. I would also recommend making the logo a bit smaller.
![raycast-logo-1024](https://user-images.githubusercontent.com/4332171/105875967-5ce46e80-5ff6-11eb-9525-19c599f8b956.png)

- Let's remove first separator under the title, we think it would look cleaner.

Let me know what you think!

2021-01-26 17:19 UTC, unnamedd requested changes
From my perspective, the PR looks good, just need some adjusts in terms of cases.

2021-01-26 17:19 UTC, unnamedd commented on README.md
> +You can find a lot of [useful script commands built by our community](commands/) here.
```suggestion
You can find a lot of [useful Script Commands built by our community](commands/) here.
```

2021-01-26 17:19 UTC, unnamedd commented on README.md
> +To get started, download one of the sample commands in this repository or [write a custom script](#write-script-commands).
```suggestion
To get started, download one of the sample commands in this repository or [write a custom Script Command](#write-script-commands).
```

2021-01-26 17:19 UTC, unnamedd commented on README.md
> +To write your custom Script Commands, go over the following steps and follow the [troubleshooting section](#troubleshooting) if your script command does not show up in Raycast.
```suggestion
To write your custom Script Commands, go over the following steps and follow the [troubleshooting section](#troubleshooting) if your Script Command does not show up in Raycast.
```

2021-01-26 17:19 UTC, unnamedd commented on README.md
> +If nothing helps, try to go step by step from a [template](templates/script-command.template.sh) script command or use one of the examples in this repo.
```suggestion
If nothing helps, try to go step by step from a [template](templates/script-command.template.sh) Script Command or use one of the examples in this repo.
```

2021-01-26 17:19 UTC, unnamedd commented on CONTRIBUTING.md
> +Please make sure that your pull request makes it easy for the reviewer to understand what the change is about (fill in the pull request template) and keep your change focused (do not create a PR cont
```suggestion
Please make sure that your pull request makes it easy for the reviewer to understand what the change is about (fill in the pull request template) and keep your change focused (do not create a PR containing multiple complex Script Commands).
```

2021-01-31 22:25 UTC, Matt-Gleich commented
This is what the image looks like now:

![Screen Shot 2021-01-31 at 5 25 07 PM](https://user-images.githubusercontent.com/43759105/106399880-46b92280-63e9-11eb-972d-9a80c1244c94.png)

2021-02-01 01:15 UTC, unnamedd approved these changes
Looks good to me! Thanks for the changes @Matt-Gleich!

2021-02-01 07:03 UTC, PitNikola commented
Awesome, thanks @Matt-Gleich!

2021-02-01 07:03 UTC, merged