Add scripts
raycast/script-commands pull request #193
Opened 2021-01-18 05:01 UTC by tanaynistala

## Description

Adds 6 new script commands to work with the [Bear](https://bear.app) note-taking app:

- Add to Bear: Create a new note, either through an input or from clipboard (enter `yes` exactly to use clipboard)
- Open Note: Open the note with the specified title
- Open Tag: Open the tag with the specified name
- Search Bear: Search all notes in Bear by term and/or tag
- Open Today: Open the Today section in Bear with an optional search query
- Open Todo: Open the Todo section in Bear with an optional search query

## Type of change

- [x] New script command

## Screenshot

<img width="862" alt="image" src="https://user-images.githubusercontent.com/24990666/104874126-2795ac00-5978-11eb-955b-a8e942e4c958.png">

## Dependencies / Requirements

Requires the [Bear](https://apps.apple.com/us/app/bear-beautiful-writing-app/id1091189122) app to be installed.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-21 23:05 UTC, unnamedd requested changes
Hi @tanaynistala, thanks for your contribution and to bring Bear to our community. 
Even though I wrote many comments, all of them almost follow the same line of thought.  

Waiting for you next interation! 🤘

2021-01-21 23:05 UTC, unnamedd commented on commands/apps/bear/bear-open-tag.sh
> +# @raycast.argument1 { "type": "text", "placeholder": "Tag" }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Tag", "percentEncoded": true}
```

2021-01-21 23:05 UTC, unnamedd commented on commands/apps/bear/bear-open-tag.sh
> +open "bear://x-callback-url/open-tag?name=${1// /%20}"
```suggestion
open "bear://x-callback-url/open-tag?name=${1}"
```

2021-01-21 23:05 UTC, unnamedd commented on commands/apps/bear/bear-search.sh
> +# @raycast.title Search Bear
```suggestion
# @raycast.title Search
```

2021-01-21 23:05 UTC, unnamedd commented on commands/apps/bear/bear-search.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "Tag", "optional": true }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Term", "optional": true, "percentEncoded": true}
# @raycast.argument2 { "type": "text", "placeholder": "Tag", "optional": true, "percentEncoded": true}
```

2021-01-21 23:05 UTC, unnamedd commented on commands/apps/bear/bear-search.sh
> +open "bear://x-callback-url/search?term=${1// /%20}&tag=${2// /%20}"
```suggestion
open "bear://x-callback-url/search?term=${1}&tag=${2}"
```

2021-01-21 23:05 UTC, unnamedd commented on commands/apps/bear/bear-today.sh
> +# @raycast.argument1 { "type": "text", "placeholder": "Search Query", "optional": true }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Search Query", "optional": true, "percentEncoded": true}
```

2021-01-21 23:05 UTC, unnamedd commented on commands/apps/bear/bear-today.sh
> +open "bear://x-callback-url/today?search=${1// /%20}"
```suggestion
open "bear://x-callback-url/today?search=${1}"
```

2021-01-21 23:05 UTC, unnamedd commented on commands/apps/bear/bear-todo.sh
> +# @raycast.argument1 { "type": "text", "placeholder": "Search Query", "optional": true }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Search Query", "optional": true, "percentEncoded": true}
```

2021-01-21 23:05 UTC, unnamedd commented on commands/apps/bear/bear-todo.sh
> +open "bear://x-callback-url/todo?search=${1// /%20}"
```suggestion
open "bear://x-callback-url/todo?search=${1}"
```

2021-01-24 04:52 UTC, tanaynistala commented
Thanks for the suggestions, @unnamedd! I've applied your suggested changes to this iteration.

2021-01-24 19:58 UTC, merged