Update whois script
raycast/script-commands pull request #195
Opened 2021-01-18 19:48 UTC by ronanrodrigo

## Description
Just updating the `whois` script to use the macOS installed bin.

## Type of change
- [x] Improvement of an existing script

## Screenshot
![Screen Shot 2021-01-18 at 16 44 06](https://user-images.githubusercontent.com/421758/104957195-70675800-59ac-11eb-8fb9-2f63e942158b.png)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-18 20:00 UTC, unnamedd commented
Wow! Looks who is here! Thanks for you first contribution my dear friend @ronanrodrigo! 

Hope to see you on our [Slack](https://raycast.com/community)!

2021-01-18 20:05 UTC, unnamedd requested changes

2021-01-18 20:05 UTC, unnamedd commented on commands/developer-utils/whois.sh
> +    whois $1
As you added `whois` as dependency, I suggest you to take a look into our guidelines, specifically in this section [here](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-runtimes-and-dependencies). In case of adding dependencies to run a Script Command, worth add an instruction in the code.

![image](https://user-images.githubusercontent.com/83694/104958614-a0c0ed80-59d0-11eb-82ea-5a6c14a05059.png)

2021-01-18 20:41 UTC, ronanrodrigo commented on commands/developer-utils/whois.sh
> +    whois $1
Because the `whois` is already installed with OS, I ignored the dependency recommendations, sorry. But I will update my changes to conform to the requirements. :)

2021-01-18 20:44 UTC, unnamedd commented on commands/developer-utils/whois.sh
> +    whois $1
Oh true! I'm not sure if I knew about that. In any case, it's good to let who will read the script command to know about the existence of the software in the system.

2021-01-18 20:48 UTC, crstauf commented
@ronanrodrigo Nice!

Don't forget to add your author info as well!

2021-01-18 20:54 UTC, unnamedd commented
> @ronanrodrigo Nice!
> 
> Don't forget to add your author info as well!

He is not the author, this is just an update ;)

2021-01-18 21:05 UTC, unnamedd approved these changes
Looks good to me, thanks @ronanrodrigo!

2021-01-18 23:14 UTC, crstauf commented
> > @ronanrodrigo Nice!
> 
> > 
> 
> > Don't forget to add your author info as well!
> 
> 
> 
> He is not the author, this is just an update ;)

Given that I'm the author, seems like it should be up to me.

2021-01-20 19:47 UTC, ronanrodrigo commented
> > > @ronanrodrigo Nice!
> > 
> > 
> > > 
> > 
> > 
> > > Don't forget to add your author info as well!
> > 
> > 
> > He is not the author, this is just an update ;)
> 
> Given that I'm the author, seems like it should be up to me.

I don't mind putting my name. But since you want, I will add my name :)

2021-01-20 19:50 UTC, crstauf requested changes

2021-01-20 19:50 UTC, crstauf commented on commands/developer-utils/whois.sh
> +# @raycast.authorURL ronanrodrigo.dev
Rather than changing the existing author info, add yourself as an additional author, so we're both recognized for our contributions (the Toolkit supports multiple authors).

2021-01-20 19:58 UTC, crstauf commented
> I don't mind putting my name. But since you want, I will add my name :)

Contributors should always be recognized for their contributions.

2021-01-20 20:01 UTC, ronanrodrigo commented on commands/developer-utils/whois.sh
> +# @raycast.authorURL ronanrodrigo.dev
Cool. I will update :)

2021-01-20 20:27 UTC, crstauf approved these changes

2021-01-24 20:01 UTC, merged