Add multi-project Sentry unresolved issues script
raycast/script-commands pull request #197
Opened 2021-01-18 21:31 UTC by PSalant726

## Description

Adds a refactored version of [`sentry-unresolved-issues.template.py`](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/sentry/sentry-unresolved-issues.template.py), which accepts a `Project` argument, and outputs all unresolved issues in the last 24h.

## Type of change
- [X] New script command
- [X] ~Improvement~ Refactoring of an existing script

## Screenshots

### Input
<img width="862" alt="Screen Shot 2021-01-18 at 4 22 05 PM" src="https://user-images.githubusercontent.com/18120121/104964236-06e64a00-59aa-11eb-8816-fa8ce279693d.png">

### Output (private details redacted)
<img width="862" alt="Screen Shot 2021-01-18 at 4 22 11 PM" src="https://user-images.githubusercontent.com/18120121/104964519-870caf80-59aa-11eb-99d9-91d4cdeb28c2.png">

## Dependencies / Requirements

None

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-21 22:39 UTC, unnamedd requested changes
Minor comments. In general looks good to me! Thanks for the contribution @PSalant726!

2021-01-21 22:39 UTC, unnamedd commented on commands/developer-utils/sentry/sentry-unresolved-issues-by-project.template.py
> +# @raycast.title Sentry Unresolved Issues (By Project)
As you already set `Sentry` in the `packageName` we can avoid it here. 
```suggestion
# @raycast.title Unresolved Issues (By Project)
```

As I'm not a Sentry user, I do have a question here: do we need to have the `(By Project)` in the title? Is it possible in Sentry to have issues not related to a project? If the `By Project` is really needed, then it is better to remove the parenthesis.

2021-01-21 22:39 UTC, unnamedd commented on commands/developer-utils/sentry/sentry-unresolved-issues-by-project.template.py
> +# @raycast.authorURL https://github.com/thomaspaulmann
Our nice Toolkit is prepared to solve the "problem" of multiple authors gracefully. You just to repeat the tags for the number of authors of that script command. 

```suggestion
# @raycast.author Phil Salant
 # @raycast.authorURL https://github.com/PSalant726
# @raycast.author Thomas Paul Mann
# @raycast.authorURL https://github.com/thomaspaulmann
```

2021-01-21 23:21 UTC, PSalant726 commented on commands/developer-utils/sentry/sentry-unresolved-issues-by-project.template.py
> +# @raycast.title Sentry Unresolved Issues (By Project)
> do we need to have the `(By Project)` in the title?

From the perspective of the user, this is otherwise identical to the existing `sentry-unresolved-issues.template.py` script.

2021-01-21 23:24 UTC, unnamedd commented on commands/developer-utils/sentry/sentry-unresolved-issues-by-project.template.py
> +# @raycast.title Sentry Unresolved Issues (By Project)
Oh got it! Then, just remove the parenthesis and it will be okay ;)
(I remember to see people having problems with parenthesis in script command's title)

2021-01-23 23:08 UTC, unnamedd approved these changes
Thanks for the changes @PSalant726, it’s approved!

2021-01-24 19:23 UTC, thomaspaulmann approved these changes
Lovely addition to the @getsentry commands!

2021-01-24 19:23 UTC, merged