Add a script to visit a specific GitHub repo, pull request, or issue
raycast/script-commands pull request #198
Opened 2021-01-18 22:46 UTC by PSalant726

## Description

Do you already know which GitHub repo you want to open, and don't need to use the GitHub extension to search for a repository? Better yet, do you already know the specific pull request and/or issue by number? Then use this script command!

## Type of change

- [x] New script command

## Screenshot

### Visit a repo directly
<img width="862" alt="Screen Shot 2021-01-18 at 5 43 51 PM" src="https://user-images.githubusercontent.com/18120121/104968759-bfb18680-59b4-11eb-9225-e0aecd4f6350.png">

### Visit a PR directly
<img width="862" alt="Screen Shot 2021-01-18 at 5 42 35 PM" src="https://user-images.githubusercontent.com/18120121/104968781-cfc96600-59b4-11eb-9fae-e8ee5f40c431.png">

### Visit an Issue directly
<img width="862" alt="Screen Shot 2021-01-18 at 5 42 23 PM" src="https://user-images.githubusercontent.com/18120121/104968792-d6f07400-59b4-11eb-88f7-c49deb3208e6.png">

### Error state
Encountered when passing both a pull request # and an issue # at the same time.
<img width="862" alt="Screen Shot 2021-01-18 at 5 43 17 PM" src="https://user-images.githubusercontent.com/18120121/104968829-e8d21700-59b4-11eb-93da-f95d5c8ddc16.png">

## Dependencies / Requirements

None

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-21 22:25 UTC, unnamedd requested changes

2021-01-21 22:25 UTC, unnamedd commented on commands/developer-utils/github/open-gh-repo-pr-or-issue.sh
> +# @raycast.title GitHub Repository PRs & Issues
Phil, as Raycast uses the packageName to help in the search, you don't need to add `GitHub` here, then I suggest this: 
```suggestion
# @raycast.title Pull Requests & Issues
```

What do you think?

2021-01-21 22:25 UTC, unnamedd commented on commands/developer-utils/github/open-gh-repo-pr-or-issue.sh
> +  echo "Do not pass both a pull request and an issue."
Reading that instruction afterwards, I started to think that might be good if you split this script command in two, one to open Pull Requests and one another to open Issues. 

Having both options in the same script command, might lead the user to a confusion and as Script Commands must be simple, like a function, split in two may solve this problem, don't you think?

2021-01-21 23:17 UTC, PSalant726 commented on commands/developer-utils/github/open-gh-repo-pr-or-issue.sh
> +# @raycast.title GitHub Repository PRs & Issues
Yea, I can remove `GitHub` but I would like to leave `Repository`. Both the PR and Issue arguments are optional, and the real benefit of the script is that a repository's root page can be opened when they aren't passed. Maybe something like `Visit a Repository, PR, or Issue`? I'm intentionally saying "visit" instead of "open" so as not to imply that a new repo, issue, or PR can be created using this script.

2021-01-21 23:18 UTC, PSalant726 commented on commands/developer-utils/github/open-gh-repo-pr-or-issue.sh
> +  echo "Do not pass both a pull request and an issue."
The PR and Issue options are just nice-to-have features that were easy to tack on to the core functionality. For me, the real draw of this script is to be able to directly open a repository without first having to search, and so I prefer to keep everything combined.

To break them up would mean having all of the following:
1. A script that opens a repository, and has no additional functionality
1. A script that requires both an `organization/repository` string **and** an issue number be passed, and opens the issue
1. A script that requires both an `organization/repository` string **and** a PR number be passed, and opens the PR

I can refactor things accordingly, but IMO the latter two would rarely be used. I don't think a user would typically know these numbers (unless they _happen_ to know them, which is why I like having the feature at all).

It feels like a lot of bloat just to avoid a situation that I think is already easily avoidable, but I'm happy to make the change if that's the way you'd prefer to have it.

2021-01-21 23:41 UTC, subtlepseudonym commented on commands/developer-utils/github/open-gh-repo-pr-or-issue.sh
> +  echo "Do not pass both a pull request and an issue."
I believe it's worth keeping the pull-request / issue functionality in this script.

However, I'm not a fan of having two mutually-exclusive, optional arguments. We could alleviate this by combining them into a single argument. The address `github.com/repo/pull/$ISSUE_NUM` will take you to both pull requests and issues, so there should be relatively few code changes.

2021-01-22 00:27 UTC, unnamedd commented on commands/developer-utils/github/open-gh-repo-pr-or-issue.sh
> +# @raycast.title GitHub Repository PRs & Issues
Make completely sense keep the `Repository`, I don’t know why I suggested that, after all, the pull requests and the issues belong to a repository! haha

2021-01-22 00:35 UTC, unnamedd commented on commands/developer-utils/github/open-gh-repo-pr-or-issue.sh
> +  echo "Do not pass both a pull request and an issue."
@PSalant726 I don’t think will be needed to split the script command in two anymore. Even if I new, I completely forgot about the address which serve both PRs and Issue and fortunately, @subtlepseudonym just came here to bring that amazing information for us.

I don’t like either mutually-exclusive arguments, they tend to lead us to confusion. 

What we can have here, is a simplification of the code and in the argument, instead of two, we can have only one and in the placeholder, set something like “PR # or Issue #”, it will work for both anyway, doesn’t mean that it needs to be complex. What do you think?

2021-01-23 23:08 UTC, PSalant726 commented
Without the need for error handling, this script now executes in `silent` mode.

2021-01-23 23:12 UTC, unnamedd commented
> Without the need for error handling, this script now executes in `silent` mode.

Great changes! Thanks a lot! Approved!

2021-01-23 23:12 UTC, unnamedd approved these changes

2021-01-24 20:09 UTC, merged