Actually enforce and use SwiftLint for the toolkit
raycast/script-commands pull request #199
Opened 2021-01-19 04:59 UTC by Matt-Gleich

## Description

Actually, enforce and use swiftlint for the Toolkit.

## Type of change

- [ ] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [x] Toolkit change
- [ ] Other (Specify)

## Screenshot

N/A

## Dependencies / Requirements

N/A

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-19 05:00 UTC, Matt-Gleich commented
cc @unnamedd

2021-01-19 05:01 UTC, Matt-Gleich commented
In the future, lets add CI for this and Xcode support

2021-01-26 16:25 UTC, thomaspaulmann commented
Leaving it to @unnamedd to review since he's the master of the toolkit. Generally looks good to me.

2021-01-26 16:26 UTC, unnamedd commented
Sorry guys, I didn't had much time to review it, but I promise I will do it today! 🙏😅

2021-01-28 11:25 UTC, unnamedd requested changes
@Matt-Gleich thanks a lot for your work here. 

There are some changes that need rollback or improvements. When you finished to address them, please, let me know and I will re-review them!  :)

2021-01-28 11:25 UTC, unnamedd commented on Tools/Toolkit/.swiftlint.yml
>  trailing_comma:
This file must not be moved out of the repo’s root. To use it, we need to:
1) set the path when we call SwiftLint
or
2) copy from the root to the current folder and then delete after

we don’t want to maintain two files, one in the Toolkit’s folder and one in the root

2021-01-28 11:25 UTC, unnamedd commented on Tools/Toolkit/Makefile
> +lint:
These instructions here, must live in the main Makefile (in the root). We need to concentrate all the building/generation/validation process from there.

2021-01-28 11:25 UTC, unnamedd commented on Tools/Toolkit/Sources/ToolkitLibrary/Core/Documentation/Documentation.swift
> +    if !group.scriptCommands.isEmpty {
I prefer to keep `.count > 0` or `.isEmpty == false` to keep the good readability.

2021-01-28 11:25 UTC, unnamedd commented on Tools/Toolkit/Sources/ToolkitLibrary/Core/Toolkit/Toolkit+ReadContent.swift
> +      let value = self.content(of: valueRange, on: content) {
Please, keep the space.

2021-01-28 11:25 UTC, unnamedd commented on Tools/Toolkit/Sources/ToolkitLibrary/Core/Toolkit/Toolkit+ReadContent.swift
>        dictionary["authors"] = extractAuthors(from: content, using: results)
The same comment I from above: to keep a good readability, please use `.count > 0` or `.isEmpty == false` for the three changes made near to this comment.

2021-01-31 20:42 UTC, thomaspaulmann requested changes
Looks like @unnamedd requested some changes. I put this back in your queue @Matt-Gleich. Just request another review when everything is ready.

2021-01-31 21:33 UTC, unnamedd commented
@thomaspaulmann, Matthew told me this week he didn’t has time to work on this PR due to school. Then, let’s wait him finish all his tasks. I am in touch with him! :)

2021-01-31 22:06 UTC, thomaspaulmann commented
Cool, I wasn't aware of it and that's totally fine by me. Just wanted to make sure that the PR is in the proper state. @Matt-Gleich whenever you feel this is ready, give it another spin. Gonna look forward to get the toolkit properly linted :-)

2021-02-01 01:04 UTC, Matt-Gleich commented on .swiftlint.yml
> +  - indentation_width
This is the only way to have that one line to be indented 3 spaces instead of 2.

2021-02-01 01:05 UTC, Matt-Gleich commented on Makefile
> +	cd $(TOOLKIT_PATH) && swiftlint --config $(SWIFTLINT_CONFIG_PATH) autocorrect
For some strange reason `--path $(TOOLKIT_PATH)` was not working for me so this is a workaround.

2021-02-03 09:31 UTC, unnamedd commented on .swiftlint.yml
> +  - indentation_width
3 spaces? Raycast standard is 2 spaces. Where did you see 3 spaces?

2021-02-03 09:32 UTC, unnamedd commented on Makefile
> +	cd $(TOOLKIT_PATH) && swiftlint --config $(SWIFTLINT_CONFIG_PATH) autocorrect
I will clone your branch and make some tests here, I don't think that change the directory is a good solution. I will let you know later.

2021-02-25 01:08 UTC, unnamedd commented
As discussed privately with @Matt-Gleich, we agreed to close this issue. All the changes he'd be done here will be embedded in my improvements for the Toolkit.

2021-02-25 01:08 UTC, closed without merging

2021-02-26 23:43 UTC, thomaspaulmann commented
Ok cool. Thanks for keeping us in the loop and great to know that we have a well formatted codebase for the toolkit.