feat: add dig command
raycast/script-commands pull request #201
Opened 2021-01-19 18:48 UTC by tom139

## Description

This command perform a `dig` with the specified name and an optional second argument (usually the type).

## Type of change

- [x] New script command

## Screenshot

![image](https://user-images.githubusercontent.com/8103786/105072103-bc3a0000-5a85-11eb-9e4b-85d670dad6b8.png)

## Dependencies / Requirements

This step depends solely on the _dig_ command, which comes with the standard developer tools. I think this dependency is expected and unavoidable.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-19 19:57 UTC, unnamedd requested changes
I made two simple suggestions, which you can solve right here without need to  commit anything locally.

Thanks for your PR, @tom139. 🙂

2021-01-19 19:57 UTC, unnamedd commented on commands/developer-utils/dig.sh
> +# @raycast.description "Perform a dig command with the specified options"
```suggestion
# @raycast.description Perform a dig command with the specified options
```

2021-01-19 19:57 UTC, unnamedd commented on commands/developer-utils/dig.sh
> +# @raycase.authorURL "https://github.com/tom139"
```suggestion
# @raycase.authorURL https://github.com/tom139
```

2021-01-20 14:48 UTC, tom139 commented
Thank you for how quickly you responded to this PR, and thank you for the great product you are creating.
I really appreciate all the effort you are putting in creating an active community around Raycast. 💪🏽

2021-01-23 08:22 UTC, tom139 reviewed
I addressed changes, hope everything is fine for merging, otherwise let me know. :)

2021-01-24 20:11 UTC, merged