added toggle airpods script
raycast/script-commands pull request #209
Opened 2021-01-27 14:33 UTC by itsnwa

## Description

Connects/disconnects a bluetooth device, in this case AirPods

## Type of change

- [x] New script command

## Screenshot

## Dependencies / Requirements

Add your devices MAC address on line 20, you can find this address by opt + clicking the bluetooth menu:
<img width="309" alt="CleanShot 2021-01-27 at 15 29 55@2x" src="https://user-images.githubusercontent.com/19958806/106005557-a1364400-60b4-11eb-9963-8805a1253960.png">

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-01-27 18:51 UTC, unnamedd requested changes
Finally your contribution is here @itsnwa! 🎉  
Nothing major, but two comments! :D

2021-01-27 18:51 UTC, unnamedd commented on commands/system/toggle-airpods.template.swift
> +        exit(-2)
@itsnwa here you can use `exit(1)` (fail) and `exit(0)` (success), this is a pattern in the CLI world! ;)
```suggestion
        exit(1)
```

2021-01-27 18:51 UTC, unnamedd commented on commands/system/toggle-airpods.template.swift
> +        exit(-4)
The same here
```suggestion
        exit(1)
```

2021-01-27 23:27 UTC, thomaspaulmann approved these changes
Lovely one! Added a comment to get the device address for folks to get started with the command.

2021-01-27 23:27 UTC, thomaspaulmann commented on commands/system/toggle-airpods.template.swift
> +    guard let bluetoothDevice = IOBluetoothDevice(addressString: "Your AirPods MAC address") else {
Let's extract the address to a constant and add a comment how to get it.

```suggestion

// Get your device's MAC address by option (⌥) + clicking the bluetooth icon in the menu bar
let deviceAddress = ""

func toggleAirPods() {
    guard let bluetoothDevice = IOBluetoothDevice(addressString: deviceAddress) else {
```

2021-01-27 23:28 UTC, merged

2021-01-31 20:55 UTC, itsnwa commented
Sweet, thanks @thomaspaulmann @unnamedd 👍