spotify current track genre finder (chosic.com)
raycast/script-commands pull request #220
Opened 2021-02-05 15:36 UTC by quelhasu

## Description

capture the current song played on spotify and search for its genre on chosic.com via favorite browser.

## Type of change

- [x] New script command

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-02-05 16:20 UTC, unnamedd requested changes
Hi @quelhasu, thanks for your first contribution in our repository.

Please, take a look into my comments and as soon you finish them, please, let me know for a second request.

It's really nice to have you here with us!

2021-02-05 16:20 UTC, unnamedd commented on commands/web-searches/chosic-genre-finder.applescript
> +# @raycast.title Chosic Genre Finder
```suggestion
# @raycast.title Search Genre in Chosic
```

2021-02-05 16:20 UTC, unnamedd commented on commands/web-searches/chosic-genre-finder.applescript
> +# @raycast.packageName Spotify
If you are in the `web-searches` folder, makes more sense here to use the `Web Searches` in the `packageName`.
```suggestion
# @raycast.packageName Web Searches
```

2021-02-05 16:20 UTC, unnamedd commented on commands/web-searches/chosic-genre-finder.applescript
> +# @raycast.icon https://cdn.iconscout.com/icon/free/png-512/spotify-11-432546.png
Here, the Spotify logo doesn't fit well. The best logo to use here is the Chosic logo, also, I'd like to ask you to submit the Chosic logo to the `image` folder under `web-searches`.

2021-02-05 16:20 UTC, unnamedd commented on commands/web-searches/chosic-genre-finder.applescript
> +# @raycast.description Find the genre of the current Spotify track
```suggestion
# @raycast.description Find the current Spotify track's gender in Chosic
```

2021-02-05 16:20 UTC, unnamedd commented on commands/web-searches/chosic-genre-finder.applescript
> +#!/usr/bin/osascript
Renaming the file to `search-gender-in-chosic.applescript` may fit better.

2021-02-05 20:15 UTC, quelhasu commented
Thank you for your review, do I need to submit another PR?

2021-02-05 21:26 UTC, unnamedd commented
> Thank you for your review, do I need to submit another PR?

Nope, as you already submitted your changes, I will review it again later on and let you know! Thanks a lot for your changes @quelhasu!

2021-02-06 11:46 UTC, unnamedd approved these changes
Thanks for the changes @quelhasu! 

Your PR is approved!

2021-02-07 11:28 UTC, quelhasu commented
do I need to close this PR ?

2021-02-07 13:38 UTC, unnamedd commented
> do I need to close this PR ?

No, you don't need. It will be merged as soon as possible. But, I need you to ask to rollback the addition of the new Script Command for Color Conversion. Would you please, create a second PR exclusive for that script command, please?

2021-02-10 14:34 UTC, unnamedd approved these changes
This PR is ready to be merged! 
@thomaspaulmann @PitNikola @fe9lix

2021-02-11 21:15 UTC, PitNikola commented
Seems like there are some conflicts. @quelhasu, could you please rebase on latest master and then I'll merge it?

2021-02-11 21:16 UTC, PitNikola requested changes
Putting back to your queue for now

2021-02-12 07:56 UTC, quelhasu commented
Are there other conflicts now?

2021-02-12 09:17 UTC, unnamedd commented
Yes @quelhasu, you need to rebase `master` branch here and also need to remove Script Commands that doesn't belong to this pull request. 

Here is the list of files that must be removed from your pull request to have it merged:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/83694/107749741-57d42e80-6d1b-11eb-90c5-4544e434cbd0.png">

2021-02-12 10:40 UTC, unnamedd commented
Hi @quelhasu, I'm afraid you've made a mistake here. You deleted some files that must not be deleted. I'm checking the `master` branch in your fork and I can't see the files. 

As you made a `force push`, would you mind to explain a bit what you did to have the need to use the `force push`? A simple merge from our `master` branch to yours is definitely enough without have to delete any existing file.

2021-02-12 10:52 UTC, quelhasu commented
I totally messed up with git on my two computers, hence the use of `force push` by mistake.

2021-02-12 11:01 UTC, unnamedd approved these changes
It's all good @quelhasu , thanks for act on it so quickly! 
@PitNikola, we are good to go again!

2021-02-12 11:28 UTC, PitNikola commented
Cheers!

2021-02-12 11:28 UTC, merged