Color Conversion command
raycast/script-commands pull request #224
Opened 2021-02-07 16:54 UTC by quelhasu

## Description

Converts colors to a desired format.

## Type of change

- [x] New script command

## Screenshot

https://ibb.co/bBf0YJ4
https://ibb.co/n6nBngV

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-02-07 18:24 UTC, crstauf commented
Note: partial duplicate of scripts added in #24.

2021-02-07 19:45 UTC, quelhasu commented
Not really, you can convert a color to (rgb, rgba, hex) and vice versa.

2021-02-07 19:46 UTC, crstauf commented
Hence the use of the word "partial".

2021-02-08 14:22 UTC, unnamedd requested changes
Hi @quelhasu, despite the fact that part of your Script Command is duplicated, I liked it. 

The review is done, nothing really special. 
Thanks for your submission.

2021-02-08 14:22 UTC, unnamedd commented on commands/conversions/color-conversion.sh
> +# @raycast.currentDirectoryPath ~
As you are not acting in any specific directory, this meta tag isn't useful.

2021-02-08 14:22 UTC, unnamedd commented on commands/conversions/color-conversion.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "New format (e.g. RGB)" }
I was wondering here, how the user might know which options are available? Here I will do a suggestion. You don't have to accept this one, but will be nice if you check if that placeholder will have a nice width and then decide to apply or not. What do you think?

```suggestion
# @raycast.argument2 { "type": "text", "placeholder": "New format (e.g. RGB | RGBA | HEX)" }
```

2021-02-08 14:22 UTC, unnamedd commented on commands/conversions/color-conversion.sh
> +  echo "Select a correct format!"
Here, will be nice if you inform which formats are available. Maybe following my suggestion in the argument2.

2021-02-08 14:28 UTC, quelhasu commented on commands/conversions/color-conversion.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "New format (e.g. RGB)" }
Yes it's a good idea, on the other hand we should do the same for the first argument because the user can input other formats (hex, rgb, rgba).

2021-02-08 15:28 UTC, unnamedd commented on commands/conversions/color-conversion.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "New format (e.g. RGB)" }
Indeed, I liked the idea! 
Somewhere in time, we should have in the argument a kind a list with pre-defined items and this kind of workaround won't be needed anymore, but until there, I guess this solution should solve the "problem".

2021-02-08 15:30 UTC, unnamedd commented on commands/web-searches/search-gender-in-chosic.applescript
> +#!/usr/bin/osascript
Don't forget to delete this file @quelhasu. It belongs to another PR.

2021-02-08 18:28 UTC, unnamedd approved these changes
Thanks for the changes @quelhasu, it’s approved. ✅ 
cc @thomaspaulmann  @PitNikola @fe9lix

2021-02-11 21:14 UTC, PitNikola commented
🎨 🎉

2021-02-11 21:14 UTC, merged