add script for baidu-translate, google-translate, jingdong
raycast/script-commands pull request #230
Opened 2021-02-13 13:50 UTC by sunbufu

## Description

1. search in Jingdong
2. translate with Baidu
3. translate with Google

## Type of change

- [ x ] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

## Dependencies / Requirements

## Checklist

- [ x ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-02-15 16:15 UTC, unnamedd requested changes
Hi @sunbufu,

I made some comments here, please as soon you address them, please let me know for a second review!  
Thanks for your contribution!

2021-02-15 16:15 UTC, unnamedd commented on commands/web-searches/translate-with-google.sh
> +open "https://translate.google.cn/?sl=auto&tl=zh-CN&text=$1&op=translate"
As we are a global community, doesn't make much sense to set Google Translator website for a specific language or even the translation language to Chinese. Will be more inclusive if we use the most used language and those who want, define themselves the language wished. Hence my suggestion:

```suggestion
# Most common acronyms
# en = English
# es = Spanish
# fr = French
# pt = Portuguese
# zh-CN = Chinese
# more to come

# For the source language, you can also use "auto", for automatic detection
source = "" # Source language acronym
destination = "" # Destination language acronym 

open "https://translate.google.com/?sl=$source&tl=$destination&text=$1&op=translate"
```

2021-02-15 16:15 UTC, unnamedd commented on commands/web-searches/translate-with-google.sh
> +#!/bin/bash
As I suggested for some extra configuration in this file, I also suggest you to rename it to `translate-with-google.template.sh`, this will encourage the user to make some personal changes before the first use.

2021-02-16 09:53 UTC, sunbufu commented on commands/web-searches/translate-with-google.sh
> +open "https://translate.google.cn/?sl=auto&tl=zh-CN&text=$1&op=translate"
Thanks for your suggestion.

2021-02-16 09:53 UTC, sunbufu commented on commands/web-searches/translate-with-google.sh
> +#!/bin/bash
OK

2021-02-16 14:31 UTC, unnamedd approved these changes
Hi @sunbufu,

really nice to see that you not only enjoyed my suggestion but also replicated it to your `Translate with Baidu` script command! 

Your pull request looks very good to me. It's approved!
@thomaspaulmann @PitNikola @fe9lix

2021-02-18 16:42 UTC, PitNikola commented
👍

2021-02-18 16:42 UTC, merged