New Script: Set Front Most as Default Browser
raycast/script-commands pull request #253
Opened 2021-02-23 13:59 UTC by ybbond

## Description

I see the "Switch Default Browser to ..." in the script list by @marcklingen, and would like to add my personal script that I've been using for 2 years. I created this back when I use Firefox, Brave, Safari and Safari Technology Preview(now not included in the script).

The implementation is similar, so I added:
- "... `defaultbrowser` needed" disclaimer
- "@raycast.packagename Browsing"

for the sake of consistency.

## Type of change

- [x] New script command
- [x] Improvement of an existing script

## GIF Demo

![GIF of the script's demo](https://user-images.githubusercontent.com/25895873/108853087-e6e51e80-7618-11eb-97c2-07f2922be38f.gif "GIF of the script's demo")

## Dependencies / Requirements

Requires `defaultbrowser` utility (https://github.com/kerma/defaultbrowser/). Install via Homebrew:
```sh
brew install defaultbrowser
```

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-02-23 21:35 UTC, thomaspaulmann requested changes
Great addition and since you're using the script for a while it clearly brings benefit. I added a few suggestions to make it more Raycasty :-) Also, the code looks duplicated. Any chance to introduce a method to reuse most chunk? This could simplify the script a lil bit.

2021-02-23 21:35 UTC, thomaspaulmann commented on commands/system/set-frontmost-as-default-browser.applescript
> +						display notification appName & space & "set as default browser"
Instead of showing a notification, you can simply log the message and Raycast shows a nice toast on the bottom of the screen with the command icon.

```suggestion
						log appName & space & "set as default browser"
```

2021-02-23 21:35 UTC, thomaspaulmann commented on commands/system/set-frontmost-as-default-browser.applescript
> +# @raycast.packageName Browsing
Let's add an icon here. How about the globe emoji?
```suggestion
# @raycast.packageName Browsing
# @raycast.icon 🌐
```

2021-02-23 21:35 UTC, thomaspaulmann commented on commands/system/set-frontmost-as-default-browser.applescript
> +						display notification appName & space & "set as default browser"
Same as above.

```suggestion
						log appName & space & "set as default browser"
```

2021-02-23 21:35 UTC, thomaspaulmann commented on commands/system/set-frontmost-as-default-browser.applescript
> +						display notification appName & space & "set as default browser"
Same

```suggestion
						log appName & space & "set as default browser"
```

2021-02-23 21:35 UTC, thomaspaulmann commented on commands/system/set-frontmost-as-default-browser.applescript
> +						display notification appName & space & "set as default browser"
Same

```suggestion
						log appName & space & "set as default browser"
```

2021-02-24 07:25 UTC, ybbond commented on commands/system/set-frontmost-as-default-browser.applescript
> +# @raycast.packageName Browsing
I will use compass emoji 🧭, for consistency sake with the existing "Set Default Browser to..." script.

That okay?

2021-02-24 07:25 UTC, ybbond commented on commands/system/set-frontmost-as-default-browser.applescript
> +						display notification appName & space & "set as default browser"
thanks! implemented!

2021-02-24 07:26 UTC, ybbond commented on commands/system/set-frontmost-as-default-browser.applescript
> +						display notification appName & space & "set as default browser"
thanks! implemented!

2021-02-24 07:28 UTC, ybbond commented
@thomaspaulmann Thank you for the great feedbacks!

I have edited the script and renamed it for consistency sake. The script just got better for myself, and I hope getting better when used by others. There is some task I'd like to implement first:

- [ ] Add documentation / list to the README
- [ ] Check if `defaultbrowser` exists, else log something like "You should install shell command `defaultbrowser` first!"

2021-02-24 08:41 UTC, ybbond commented
I already added documentation and improve on the script.

The repetition of handler on [!253 L48 - L54](https://github.com/raycast/script-commands/pull/253/files#diff-1c57f1ef1ad22c0a638f7fa827837acf0e9008efdc2b83c74d5bb5e1d71606fdR48-R54) and [!253 L58 - L64](https://github.com/raycast/script-commands/pull/253/files#diff-1c57f1ef1ad22c0a638f7fa827837acf0e9008efdc2b83c74d5bb5e1d71606fdR58-R64) is necessary. If I put that into a function, the handler somehow doesn't work.

Please re-review 🙇. Thank you.

2021-02-24 09:24 UTC, unnamedd commented
Hi @ybbond, please do not edit  the files `commands/README.md` or `commands/extensions.json` they are auto generated.

2021-02-24 09:45 UTC, ybbond commented
> Hi @ybbond <https://github.com/ybbond>, please do not edit the files commands/README.md or commands/extensions.json they are auto generated.

Whoops, sorry. I reverted that commit.

Thank you for the heads-up!

2021-02-24 10:08 UTC, unnamedd commented
> Hi @ybbond <https://github.com/ybbond>, please do not edit the files commands/README.md or commands/extensions.json they are auto generated.
> Whoops, sorry. I reverted that commit. Thank you for the heads-up!

🤘 thank you for the revert! :D

2021-02-24 18:34 UTC, thomaspaulmann commented
Wow the script got a lot simpler to read. Great work @ybbond 🎉

2021-02-24 18:34 UTC, merged