feat: add undraw to web searches
raycast/script-commands pull request #254
Opened 2021-02-23 20:01 UTC by AsterYujano

## Description

Add undraw to the search folder: https://undraw.co/

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

none

## Dependencies / Requirements

none

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-02-23 21:29 UTC, thomaspaulmann requested changes
Putting back in your queue to check if you can pass a search query to the web search.

2021-02-23 21:29 UTC, thomaspaulmann commented on commands/web-searches/undraw.sh
> +open "https://undraw.co/search"
Thanks for the contribution @AsterYujano. Is there a way to specify a query parameter that you could pass to Undraw. Then the search could be more efficient and you would see result straigth away. This is how other web searches work.

2021-02-23 22:00 UTC, AsterYujano commented on commands/web-searches/undraw.sh
> +open "https://undraw.co/search"
Hello,

Sadly after a quick search, I don't think undraw allows a normal GET parameter to run a search.
The search is done by POST request with a payload "{query: "mysearch"}".

I don't think it is possible to pass parameters like the other searches, as it is not a GET.

What do you think?

2021-02-23 22:07 UTC, unnamedd commented on commands/web-searches/undraw.sh
> +open "https://undraw.co/search"
You’re right @AsterYujano. Before write any comments here, I was also checking how unDraw works and as they are not rendering the result based on the URL parameters, I don’t think will be possible to inject the value to trigger the search. So sad! :(

2021-02-28 11:36 UTC, thomaspaulmann commented
Since this web search doesn't take search query, it is simply a bookmark. We usually don't add simple bookmarks to this repository because there are too many and it would explode this repo. I hope that's understandable. @AsterYujano if you find a way to pass a query to the search, please feel free to re-open the PR.

2021-02-28 11:36 UTC, closed without merging