Add script to open in VS Code using z
raycast/script-commands pull request #255
Opened 2021-02-24 04:35 UTC by mjshashank

## Description

Use fuzzy names to open folders in VS Code with the help of the `z` utility.

## Type of change

- [x] New script command

## Screenshot

![fuzzy-open-in-vscode-with-z-demo](https://user-images.githubusercontent.com/16825130/108948042-b4bed580-7687-11eb-8c3e-922bf0679152.gif)

## Dependencies / Requirements

1. z (https://github.com/rupa/z)
2. Path to `z.sh` script may need to be modified if not installed using brew.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-02-24 09:21 UTC, unnamedd commented
Hi @mjshashank, unfortunately, a Script Command to open folder in VSCode is already available in our repository.

Please, check it out here: [https://github.com/raycast/script-commands/blob/master/commands/developer-utils/open-folder-in-vscode.applescript](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/open-folder-in-vscode.applescript).

2021-02-24 10:12 UTC, mjshashank commented
Hi @unnamedd! 

Thanks for looking at this PR. I saw the currently existing implementation as well but its functionality is very different from this PR's script command. 

The existing one just opens the current topmost directory in VSCode. This one takes name as an argument which can be partial or fuzzy and uses `z` to ascertain a matching directory and opens that in VS Code.

This actually implements the feature expressed in this thread: https://raycastcommunity.slack.com/archives/C01D1B36344/p1610941724027900

Let me know if this makes sense or if this still looks like a duplicate.

2021-02-24 10:44 UTC, unnamedd commented
@mjshashank I understood the point. Being honest and bringing here a personal opinion (which doesn't invalidate your Script Command), I'd prefer the current one, because if I am working in some project, that need to be opened in VS Code, I will have two different ways open it: 
1) I will have it opened in Terminal (then I will have just run `code .`) or 
2) I will have it opened in the Finder and then just need to ask for the current script command to open the folder in VS Code.

I don't think that a fuzzy search here, will be fail proof, which may frustrate the user if the fuzzy couldn't find the directory specified in the argument.

Again, everything I wrote here, was only personal opinion.

2021-02-24 10:56 UTC, unnamedd requested changes
Despite my personal comments, the Script Command looks simple and good, however, will be nice if you make some small changes regarding the credits to you.

2021-02-24 10:56 UTC, unnamedd commented on commands/developer-utils/vs-code/open-in-vs-code.sh
> +# @raycast.icon images/vscode-logo.png
Please don't forget to make use of the meta tags to refer you as the author:
```suggestion
# @raycast.icon images/vscode-logo.png
# @raycast.author M J Shashank 
# @raycast.authorURL https://github.com/mjshashank
# @raycast.description <A nice description about your Script Command>
```

2021-02-24 10:56 UTC, unnamedd commented on commands/developer-utils/vs-code/open-in-vs-code.sh
> +# @raycast.title Open in VS Code
```suggestion
# @raycast.title Open Folder in VS Code
```

2021-02-28 11:40 UTC, thomaspaulmann requested changes
Hey @mjshashank, thanks for the contribution. Could you address the comments of @unnamedd and have a look in my comment? Generally we tend to make script commands as easy usable as possible and try to avoid custom setups.

2021-02-28 11:40 UTC, thomaspaulmann commented on commands/developer-utils/vs-code/open-in-vs-code.sh
> +source $(brew --prefix)/etc/profile.d/z.sh
@mjshashank Is it possible to get rid of this line? Maybe use `-l` with the shebang to load your login shell? We should try to avoid shell commands that need a custom setup, e.g. in this case have the `z.sh` in the specific directory.

2021-03-06 13:58 UTC, unnamedd commented
Hi @mjshashank, do you have any intention to work on this pull request?

2021-03-07 01:56 UTC, mjshashank commented
> Hi @mjshashank, do you have any intention to work on this pull request?

@unnamedd Apologies, was occupied at work, let me make the changes by today.

2021-03-25 21:16 UTC, fe9lix commented
I'm closing this due to inactivity.

2021-03-25 21:16 UTC, closed without merging