Feature: Add new email
raycast/script-commands pull request #257
Opened 2021-02-24 20:21 UTC by BrandonEscamilla

## Description
Opens default email application, and creates a new email with the given inputs.

## Type of change

- [X] New script command

## Screenshot

![gif_new_email](https://user-images.githubusercontent.com/21966716/109060766-6cb1aa00-76ab-11eb-9f4b-a7de40bbb62e.gif)

## Dependencies / Requirements

No dependencies.

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-02-24 22:47 UTC, thomaspaulmann requested changes
Thanks for adding the command. I added a few changes that makes the command faster to use. Let me know what you think.

2021-02-24 22:47 UTC, thomaspaulmann commented on commands/system/new-email.sh
> +# @raycast.argument3 { "type": "text", "placeholder": "Body", "optional": false, "percentEncoded": true }
Let's make all arguments optional. This way the user can choose what to fill and get's quickly to the email editor. 

```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "To:", "optional": true, "percentEncoded": true }
# @raycast.argument2 { "type": "text", "placeholder": "Subject", "optional": true, "percentEncoded": true }
# @raycast.argument3 { "type": "text", "placeholder": "Body", "optional": true, "percentEncoded": true }
```

2021-02-24 22:47 UTC, thomaspaulmann commented on commands/system/new-email.sh
> +# @raycast.title New Email
I would suggest to name this similarly to other forms, e.g. GitHub Create Pull Request. 

```suggestion
# @raycast.title Create Email
```

2021-02-24 22:47 UTC, thomaspaulmann commented on commands/system/new-email.sh
> +echo "Done"
Let's remove this message to not show a toast since the email program gets opened which is enough visual feedback. 

```suggestion
```

2021-02-24 23:25 UTC, BrandonEscamilla commented on commands/system/new-email.sh
> +echo "Done"
All looks great to me.

2021-02-24 23:25 UTC, BrandonEscamilla commented on commands/system/new-email.sh
> +echo "Done"
Thank you for the suggestions. 👍

2021-02-25 10:45 UTC, thomaspaulmann commented on commands/system/new-email.sh
> +# @raycast.argument1 { "type": "text", "placeholder": "To:", "optional": true, "percentEncoded": true }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "To", "optional": true, "percentEncoded": true }
```

2021-02-25 10:46 UTC, thomaspaulmann commented on commands/system/new-email.sh
> +echo "Done"
```suggestion
```

2021-02-25 10:47 UTC, merged