script to show and manage surfshark VPN connection
raycast/script-commands pull request #275
Opened 2021-03-04 22:18 UTC by jordicl

## Description

These 3 scripts are used to manage your Surfshark VPN connection. It can show the current status inline, connect and disconnect the VPN.

## Type of change

- [x] New script command

## Screenshot

<img width="862" alt="Screenshot 2021-03-04 at 23 00 31" src="https://user-images.githubusercontent.com/292306/110038149-a5065780-7d3f-11eb-9d23-148818d2cfcc.png">

## Dependencies / Requirements

This script depends on the `vpnutil` command line utility. This utility can be downloaded here: https://github.com/Timac/VPNStatus/releases/tag/1.0. Please make sure it's added to your `$PATH`.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-03-06 13:48 UTC, unnamedd requested changes
Hi @jordicl,

yesterday I reviewed a similar [pull request](https://github.com/raycast/script-commands/pull/277) and I made some suggestions there which fit here as well.

Please, check this [comment](https://github.com/raycast/script-commands/pull/277#pullrequestreview-605045848) I made.

Basically, I would like to you to create a new file a config file and move from each file you have, this piece of code to the new config file: 

let's for example, call it `surfshark.config.sh`:
```shell
# You can find the VPN name in the Network preference pane 
export SURFSHARK_VPN_NAME=""

if ! command -v vpnutil &> /dev/null; then
  echo "vpnutil command is required. Download here: https://github.com/Timac/VPNStatus/releases/tag/1.0";
  exit 1;
fi

if [ -z "$SURFSHARK_VPN_NAME" ]; then
  echo "\$SURFSHARK_VPN_NAME is empty. Please, set VPN name in \"surfshark.config.sh\".";
  exit 1;
 fi
```

and in each file, where we had the piece of code above, add this in replacement:
```shell
source surfshark.config.sh

VPN=$SURFSHARK_VPN_NAME
```

In my point of view, this will reduce the amount of duplicated code and concentrate the configuration of the Script Command on the same place and if, something goes wrong, the user will change only one file that's all.

Thanks for your contribution!

2021-03-06 13:48 UTC, unnamedd commented on commands/apps/surfshark/surfshark-vpn-start.sh
> +# @raycast.title Surfshark VPN connect TEST
```suggestion
# @raycast.title VPN Connect
```

2021-03-06 13:48 UTC, unnamedd commented on commands/apps/surfshark/surfshark-vpn-start.sh
> +# @raycast.packageName VPN
```suggestion
# @raycast.packageName Surfshark
```

2021-03-06 13:48 UTC, unnamedd commented on commands/apps/surfshark/surfshark-vpn-status.sh
> +# @raycast.packageName VPN
```suggestion
# @raycast.packageName Surfshark
```

2021-03-06 13:48 UTC, unnamedd commented on commands/apps/surfshark/surfshark-vpn-status.sh
> +# @raycast.title Surfshark VPN status TEST
```suggestion
# @raycast.title Surfshark VPN Status
```

2021-03-06 13:48 UTC, unnamedd commented on commands/apps/surfshark/surfshark-vpn-stop.sh
> +# @raycast.title Surfshark VPN disconnect TEST
```suggestion
# @raycast.title VPN Disconnect
```

2021-03-06 13:48 UTC, unnamedd commented on commands/apps/surfshark/surfshark-vpn-stop.sh
> +# @raycast.packageName VPN
```suggestion
# @raycast.packageName Surfshark
```

2021-03-06 16:42 UTC, unnamedd commented on commands/apps/surfshark/surfshark.config.sh
> +export SURFSHARK_VPN_NAME="Surfshark. IKEv2"
My suggestion for you is to let this string empty to force the user to configure its own VPN name, or does that the default name for the Surfshark VPN networks?

2021-03-06 16:47 UTC, jordicl commented on commands/apps/surfshark/surfshark.config.sh
> +export SURFSHARK_VPN_NAME="Surfshark. IKEv2"
I left it in as this is the default string generated by the Surfshark app.

2021-03-06 16:51 UTC, unnamedd commented on commands/apps/surfshark/surfshark.config.sh
> +export SURFSHARK_VPN_NAME="Surfshark. IKEv2"
I see. Then, looks that is everything okay! 🤘

2021-03-06 16:52 UTC, unnamedd approved these changes
Looks very good to me, with no duplicated code! It's approved! ✅ 
@thomaspaulmann @PitNikola

2021-03-08 15:54 UTC, grzegorzkrukowski commented
It looks good - @jordicl let's just update headers for all scripts, to include dependency information (`vpnutil`) according to our guidelines:
https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-runtimes-and-dependencies

and we will merge it.

2021-03-08 15:56 UTC, grzegorzkrukowski requested changes
Add dependency informations in headers for all scripts

2021-03-08 17:19 UTC, grzegorzkrukowski commented
All good - thanks for quite updates

2021-03-08 17:19 UTC, grzegorzkrukowski approved these changes

2021-03-08 17:19 UTC, merged