New Script: add-spacer-to-dock.sh
raycast/script-commands pull request #276
Opened 2021-03-05 00:20 UTC by Pondorasti

## Description

This is a simple utility script that adds an invisible icon to the Dock that acts as a spacer.

## Type of change

- [x] New script command

## Screenshot

https://user-images.githubusercontent.com/32957606/110048788-5fc53400-7d05-11eb-92ac-8e0d071bb660.mov

## Dependencies / Requirements

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-03-05 09:16 UTC, unnamedd requested changes
Nice addition @Pondorasti!

2021-03-05 09:16 UTC, unnamedd commented on commands/system/add-spacer-to-dock.sh
> +# @raycast.packageName System
I guess a packageName `Dock` should be better here. It will live inside of `system` folder, but should be easier to find also when the user type `dock` in the search.
```suggestion
# @raycast.packageName Dock
```

2021-03-05 09:16 UTC, unnamedd commented on commands/system/add-spacer-to-dock.sh
> +# @raycast.title Add spacer to Dock
```suggestion
# @raycast.title Add Spacer
```

2021-03-05 17:38 UTC, Pondorasti commented
@unnamedd Do you think I should create a `README.md` similar to this [one](https://github.com/raycast/script-commands/tree/master/commands/apps/things) to demonstrate its functionality?

2021-03-05 17:42 UTC, unnamedd commented
@Pondorasti I don't think it's needed because you already added here. In the case you mentioned, I talked to Thomas that I loved because that are many scripts inside of a folder and might be good to have such a document. Your case is just one Script Command, it's good to me! ;)

2021-03-08 00:46 UTC, thomaspaulmann commented on commands/system/add-spacer-to-dock.sh
> +echo "Spacer added!"
```suggestion
echo "Added spacer to dock"
```

2021-03-08 00:46 UTC, thomaspaulmann commented on commands/system/add-spacer-to-dock.sh
> +# @raycast.title Add Spacer
```suggestion
# @raycast.title Add Spacer to Dock
```

2021-03-08 00:46 UTC, thomaspaulmann commented on commands/system/add-spacer-to-dock.sh
> +# @raycast.packageName Dock
```suggestion
# @raycast.packageName System
```

2021-03-08 00:46 UTC, merged