bitwarden: fix clipboard copy error that may include newline
raycast/script-commands pull request #285
Opened 2021-03-08 17:49 UTC by qeude

## Description

This is fixing a bug that was adding a newline at the end of the copied password.

## Type of change

- [ ] Bug fix

## Checklist

- [ x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-03-12 16:46 UTC, PSalant726 requested changes
Thanks for these fixes! Just some suggestions for a cleaner implementation.

2021-03-12 16:46 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +echo $password | tr -d " \t\n\r" | pbcopy
Per the [`jq` documentation](https://stedolan.github.io/jq/manual/#Invokingjq), we should probably be using `--join-output` instead of `--raw-output` on L50, instead of trying to script the `\n` away like this. I didn't realize `--join-output` was an option when I originally wrote this script.

2021-03-12 16:46 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +if [[ -z $name || -z $password || ( $name == "null" && $password == "null") ]]; then
We should be able to use the `jq --exit-status` option and check the value on/after L49, instead of adding these additional conditions.

2021-03-13 12:23 UTC, qeude commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +echo $password | tr -d " \t\n\r" | pbcopy
I did investigate a bit, and I finally found that the added newline isn't caused by the `jq` command but by the `echo` one.
I think the following code would be the cleanest way to resolve this to avoid the added newline at the end from the `echo` command as documented [here](https://linuxcommand.org/lc3_man_pages/echoh.html).
```suggestion
echo -n $password | pbcopy
```

2021-03-13 12:58 UTC, qeude commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +if [[ -z $name || -z $password || ( $name == "null" && $password == "null") ]]; then
I fixed this by using `jq --exit-status` in [this commit](https://github.com/raycast/script-commands/pull/285/commits/91fa07beae98f396f604ec5e0f6fb50e75006e21). It make all the checking stuff cleaner.

2021-03-13 14:33 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +echo $password | tr -d " \t\n\r" | pbcopy
Good looks! Yes, let's go with `echo -n`.

2021-03-13 14:44 UTC, PSalant726 requested changes
Nice changes! Just a few quality-of-life suggestions and this should be good to merge!

2021-03-13 14:44 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +password=$(echo $item | jq -re ".password") || notFoundError
When available, it's always a best practice to use the long-form of command options when coding them into a script. This preserves clarity, and in this case there aren't enough options to require the commands to overflow onto additional lines.
```suggestion
name=$(echo $item | jq --exit-status ".name") || notFoundError
password=$(echo $item | jq --raw-output --exit-status ".password") || notFoundError
```

2021-03-13 14:44 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +unset password
Does this need to remain `$password`?

2021-03-13 14:44 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +exit 0
Please preserve the newline at the end of the file, to avoid superfluous diffs if/when others edit it.

2021-03-13 14:44 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +unset name
This shouldn't contain sensitive info, and the next line `exit`s the script, so it doesn't need to be `unset`.

2021-03-13 14:44 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +  echo -n "The query '$1' did not return a password."
Not a big deal, but since the next line will always exit the script, `-n` is unnecessary and just adds extra complexity.
```suggestion
  echo "The query '$1' did not return a password."
```

2021-03-13 14:54 UTC, qeude commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +unset password
It seems that with the `$` it doesn't unset properly the variable, which might be a non wanted behaviour.

2021-03-13 14:57 UTC, qeude commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +unset name
It seems more consistent to me to explicitly unset the var, even if it's not sensitive. But I'm ok to revert this change.

2021-03-13 16:41 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +unset password
Yes, my mistake. Good call.

2021-03-13 16:46 UTC, PSalant726 requested changes
Should be good after these changes. Thanks for sticking with it!

2021-03-13 16:46 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +notFound() {
Just a nitpick, but I'd like it if a blank line separated the documentation from the code here.
```suggestion

notFound() {
```

2021-03-13 16:46 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-password.sh
> +unset name
It's not a necessary line, so let's remove it for simplicity.

2021-03-13 19:36 UTC, qeude commented
Should be ok now @PSalant726 :)

2021-03-13 19:59 UTC, PSalant726 approved these changes
Looks good, thanks!

2021-03-16 06:29 UTC, merged