Metadata documentation
raycast/script-commands pull request #29
Opened 2020-11-05 17:17 UTC by unnamedd

In this PR I've added:
- the new metatags in the template files
- templates folder into the blocked list
- update README adding new metatags

2020-11-05 20:23 UTC, thomaspaulmann requested changes
Let's separate the parameters that are required for documentation purposes in the template.

2020-11-05 20:23 UTC, thomaspaulmann commented on Tools/Toolkit/Sources/ToolkitLibrary/Toolkit.swift
> +    blockedFolderList: [String] = [".git", "screenshots", "Tools", ".build", ".github", "templates"]
Neat!

2020-11-05 20:23 UTC, thomaspaulmann commented on templates/script-command.template.sh
> +# @raycast.authorURL An URL for one of your social medias
```suggestion
#
# Documentation:
# @raycast.description Write a nice and descriptive summary about your script command here 
# @raycast.author Your name
# @raycast.authorURL An URL for one of your social medias
```

2020-11-05 20:23 UTC, thomaspaulmann commented on templates/script-command.template.sh
> +# @raycast.authorURL An URL for one of your social medias
Let's separate the documentation specific parameters.

2020-11-05 20:23 UTC, thomaspaulmann commented on templates/script-command.template.swift
> +
Same here.
```suggestion
//
// Documentation:
// @raycast.description Write a nice and descriptive summary about your script command here
// @raycast.author Your name
// @raycast.authorURL An URL for one of your social medias

```

2020-11-05 20:54 UTC, unnamedd commented
All changes done @thomaspaulmann 🤘

2020-11-06 11:14 UTC, merged

2020-11-06 11:14 UTC, thomaspaulmann commented
Thanks for addressing the changes!