SideNotes: Add script to create a new note
raycast/script-commands pull request #296
Opened 2021-03-10 19:18 UTC by MarcelBochtler

## Description

This script creates a new [SideNotes](https://www.apptorium.com/sidenotes) note in the given folder.
If no folder is specified the note will be created in the open folder or in the first folder as a fallback.

## Type of change

- [x] New script command

## Screenshot

![SideNotes new script creation](http://g.recordit.co/KwKsvK2HPf.gif)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-03-10 22:12 UTC, grzegorzkrukowski requested changes
Hey @MarcelBochtler - thanks for your first contribution.

I tried to run the script, but it seems it has a Syntax Error problem: `Expected “then”, etc. but found property.`

2021-03-10 22:13 UTC, grzegorzkrukowski commented on commands/apps/sidenotes/sidenotes-create-note.applescript
> +			if current folder is missing value then
`Expected “then”, etc. but found property.`

2021-03-11 17:15 UTC, MarcelBochtler commented on commands/apps/sidenotes/sidenotes-create-note.applescript
> +			if current folder is missing value then
Hi @grzegorzkrukowski, that is strange, as it works for me.
I'll try to repoduce and fix the issue.

2021-03-25 21:09 UTC, fe9lix commented
Hi! Any updates here? (Draft status...)

2021-03-25 21:12 UTC, MarcelBochtler commented
> Hi! Any updates here? (Draft status...)

I'm waiting to receive my new MacBook and hope to be able to reproduce the mentioned issue then.
Afterwards I will update the PR.

2021-03-30 10:35 UTC, MarcelBochtler commented on commands/apps/sidenotes/sidenotes-create-note.applescript
> +			if current folder is missing value then
@grzegorzkrukowski Unfortunately I'm not able to reproduce your issue. It works for me on Catalina 10.15.7 (can't update right now)

2021-04-12 11:47 UTC, grzegorzkrukowski commented on commands/apps/sidenotes/sidenotes-create-note.applescript
> +			if current folder is missing value then
We tried it on the second machine with Catalina 10.15.7 - and it fails on the same line.

2021-04-12 11:50 UTC, MarcelBochtler commented on commands/apps/sidenotes/sidenotes-create-note.applescript
> +			if current folder is missing value then
How are you calling the script?
What parameters are you giving?
I'm also testing on Catalina 10.15.7. Thanks for your patience.

2021-04-12 11:54 UTC, grzegorzkrukowski commented on commands/apps/sidenotes/sidenotes-create-note.applescript
> +			if current folder is missing value then
I am running it in Raycast. I also tried opening it in default apple script editor and run it from there - it fails on the same line :(

2021-04-12 11:56 UTC, grzegorzkrukowski commented on commands/apps/sidenotes/sidenotes-create-note.applescript
> +			if current folder is missing value then
Here is preview from editor:

![image](https://user-images.githubusercontent.com/1301068/114390631-cc4e1100-9b96-11eb-9caa-deab912dd722.png)

2021-04-12 11:59 UTC, grzegorzkrukowski commented on commands/apps/sidenotes/sidenotes-create-note.applescript
> +			if current folder is missing value then
It seems that the reason was I didn't have `SideNotes` installed on my machine and this was causing compilation errors. After installing SideNotes it works. 

I wonder if we can do something about that case - I was expecting to get the message that I need to install it - I see you are handling that one above, but AppleScript is failing to even run for this case.

2021-04-12 12:02 UTC, grzegorzkrukowski commented
Another problem I found after installing SideNote is that it doesn't work if you don't have folders:
<img width="746" alt="CleanShot 2021-04-12 at 14 01 38@2x" src="https://user-images.githubusercontent.com/1301068/114391377-b7be4880-9b97-11eb-8b11-871d56728711.png">
<img width="747" alt="CleanShot 2021-04-12 at 14 01 47@2x" src="https://user-images.githubusercontent.com/1301068/114391384-b8ef7580-9b97-11eb-9f7b-13e687f2ffec.png">

2021-04-12 12:16 UTC, MarcelBochtler commented on commands/apps/sidenotes/sidenotes-create-note.applescript
> +			if current folder is missing value then
`current folder` is taken from SideNote's library. That's why the script won't compile when it's not installed.
The check is done the same way for Things which would then also fail if the application is not installed:
https://github.com/raycast/script-commands/blob/50bd467aa8938ade0a27f1a4eec24a934a41efff/commands/apps/things/things-current-todo.applescript#L18-L21

2021-04-12 12:18 UTC, grzegorzkrukowski commented on commands/apps/sidenotes/sidenotes-create-note.applescript
> +			if current folder is missing value then
Ok fair enough - we can leave it as it is - I didn't find a way to prevent it either. Resolving this issue, leaving one more on the main discussion. Sorry for my lack of AppleScript experience, I was not aware that's gonna fail so hard without app installed :)

2021-04-12 15:39 UTC, grzegorzkrukowski requested changes
The script is still failing to create a note when there is no folder created.

We should create a `New Folder` for that case probably or at least show a readable error for a user.

2021-04-12 15:44 UTC, MarcelBochtler commented
A new folder is now created if no folders exist.
However: If the user mistypes the folder's name the script falls back to add the note to the first folder.
Is this ok? Or should the script create the "mistyped" folder name and add the note in there?

2021-04-12 15:53 UTC, grzegorzkrukowski commented
> A new folder is now created if no folders exist.
> However: If the user mistypes the folder's name the script falls back to add the note to the first folder.
> Is this ok? Or should the script create the "mistyped" folder name and add the note in there?

I think if the user provides a "Folder Name" then it should be created if it doesn't exist.
This way we will provide more functionality - a user can create a Folder directly via script if needed.
If the folder name is not provided we can then simply use the first one from the list as you have it now.
I suggest to ignore miss-typing use case for now.

2021-04-12 16:15 UTC, MarcelBochtler commented
> I think if the user provides a "Folder Name" then it should be created if it doesn't exist.

Yes, that makes sense.
Changed the script to do that.

2021-04-12 17:39 UTC, grzegorzkrukowski approved these changes
Looks good now - thanks for your hard work.

2021-04-12 17:39 UTC, merged