Script to generate gitignore file
raycast/script-commands pull request #298
Opened 2021-03-11 12:37 UTC by rolandleth

## Description

Calls https://gitignore.io to generate a `.gitignore` file for the given technologies and copies the result to clipboard.

## Type of change

- [x] New script command

## Screenshot

<img width="791" alt="2021-03-11 at 02 36 04" src="https://user-images.githubusercontent.com/1858700/110788309-20ec2c80-8277-11eb-990c-df76c5ae9b55.png">
<img width="784" alt="Bildschirmfoto 2021-03-11 um 2 37 10 PM" src="https://user-images.githubusercontent.com/1858700/110788434-45e09f80-8277-11eb-89aa-f66b28c354f6.png">

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-03-11 22:46 UTC, grzegorzkrukowski commented
Thanks for the PR - that's interesting one ! 

I wonder - does it make sense to keep it as `fullOutput` mode ? It doesn't really allow user to edit anything there - also there is no information about everything being copied to clipboard - maybe having it as silent with toast could be enough for this one?

2021-03-12 06:47 UTC, rolandleth commented
My initial idea was to display the output and copy if _after_, with a second command, so the flow would've been "generate, check if it's what you want, copy it". Funnily enough, I realised just now, while writing this, that it's possible to do just that, which is why there's a copy in the script itself 😄

I was a bit torn about this, but you only really need to check it once; from then on, you might not know _what_ you're exactly getting, but you will know that it's what you need, since you verified it in the past.

So I'll change it to silent and handle the case where it returns nothing.

2021-03-12 11:33 UTC, grzegorzkrukowski requested changes

2021-03-12 11:33 UTC, grzegorzkrukowski commented on commands/developer-utils/generate-git-ignore.sh
> +# @raycast.mode fullOutput
@rolandleth I was about to merge it, but I see it's still `fullOutput` mode for this one - you mentioned in commend you want to make it silent - or you changed your mind ?

2021-03-12 12:19 UTC, grzegorzkrukowski requested changes

2021-03-12 12:19 UTC, grzegorzkrukowski commented on commands/developer-utils/generate-git-ignore.sh
> +
```suggestion

# List of available gitignore types: https://www.toptal.com/developers/gitignore/api/list

```

2021-03-12 12:19 UTC, grzegorzkrukowski commented on commands/developer-utils/generate-git-ignore.sh
> +# @raycast.mode fullOutput
```suggestion
# @raycast.mode silent
```

2021-03-12 12:19 UTC, grzegorzkrukowski commented on commands/developer-utils/generate-git-ignore.sh
> +# @raycast.argument1 { "type": "text", "placeholder": "Technologies (react,node,vscode)", "optional": true }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Type (react,node,vscode)", "optional": false }
```

2021-03-12 12:19 UTC, grzegorzkrukowski commented on commands/developer-utils/generate-git-ignore.sh
> +	params="react,node,vscode"
```suggestion
	echo "Missing params"
	exit 1
```

2021-03-12 12:19 UTC, grzegorzkrukowski commented on commands/developer-utils/generate-git-ignore.sh
> +	echo "The requested params couldn't be found"
```suggestion
	echo "Unsupported gitignore type"
```

2021-03-12 12:22 UTC, grzegorzkrukowski commented on commands/developer-utils/generate-git-ignore.sh
> +# @raycast.title Generate a .gitignore file
```suggestion
# @raycast.title Create .gitignore
```

2021-03-12 12:24 UTC, grzegorzkrukowski commented on commands/developer-utils/generate-git-ignore.sh
> +	params="react,node,vscode"
```suggestion
	echo "Missing params"
	exit 1
```

2021-03-12 12:26 UTC, grzegorzkrukowski commented on commands/developer-utils/generate-git-ignore.sh
> +# @raycast.argument1 { "type": "text", "placeholder": "Type (react,node,vscode)", "optional": false }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Types (react,node,vscode)", "optional": false }
```

2021-03-12 12:26 UTC, merged