another brew commands
raycast/script-commands pull request #299
Opened 2021-03-12 15:29 UTC by fate-7

My usual brew command

## Description

## Type of change

- [ ] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

## Dependencies / Requirements

## Checklist

- [ ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-03-12 15:29 UTC, fate-7 commented
add brew commands

2021-03-12 16:25 UTC, unnamedd requested changes
Hi @fate-7, thanks for your contribution.

I’ve made just two comments and basically I’m asking to change the `authorURL` to your social media, because that twitter there is mine! :D

2021-03-12 16:25 UTC, unnamedd commented on commands/developer-utils/brew/brew-update.sh
> +# @raycast.authorURL https://twitter.com/tholanda
@fate-7, please, change the value to your social media

2021-03-12 16:25 UTC, unnamedd commented on commands/developer-utils/brew/brew-list.sh
> +# @raycast.authorURL https://twitter.com/tholanda
@fate-7, please, change the value to your social media

2021-03-13 01:27 UTC, fate-7 reviewed
Change to my personal address

2021-03-19 01:37 UTC, unnamedd approved these changes
Looks good to me! 
It's approved! ✅

2021-03-19 16:38 UTC, merged