Collector tool
raycast/script-commands pull request #3
Opened 2020-10-01 14:30 UTC by unnamedd

# Collector Tool

The main goal of the `Collector` is to make it easier to generate a JSON file containing the information of every extension created for Raycast. 

The script is able to run through each directory of a predefined folder, reading the extension's metadata to build a huge JSON file, which should be used to any purpose.

## How to run
```shell
cd ~/
mkdir -p .raycast
cd .raycast
git clone https://github.com/raycast/script-commands.git extensions
cd extensions/Tools/Collector
swift run
```

## Result
A file called `raycast-extensions.json` will be generated at `~/.raycast/extensions`.

## Warning
This is a very first pitch of the implementation of this kind of tool, so this path is needed for now, but it will be improved soon to allow any different path.
 
If you want to discuss the evolution of this tool, please feel free to join the Raycast Community at https://raycastcommunity.slack.com

2020-10-02 17:12 UTC, thomaspaulmann commented
Thanks for putting up this PR 👏 

The tool looks great but lacks a specific use case at the moment. The JSON output is a little bit too generic. As mentioned in Slack, I thought about using the tool to generate an overview of all available Script Commands in this repository. The generated documentation is a great source for new Raycast users to see what's available. They can pick and choose the commands that fit their workflow.

To do this, I would propose the following:

1. Have an option to output Markdown. This could be an option of the command line tool. We would need to align on some sort of format. A table might be the best but I'm open for suggestions. 
2. Add some more Script Command parameters that are necessary to format a nice documentation. I'm thinking of a description for the command and maybe an author. We can add the validation of the parameters on our side.
3. Wire up the auto-generated Markdown file with the documentation. I can think of two options: One, update the README or two, check in a separate Markdown file that we link to from the README. Thoughts?
3. Set up a GitHub Action to automatically run the script so that the repository is always up-to-date. Ideally this would happen with every push to the master branch.
4. Since our internal codebase is 100% Swift and we aligned on some coding guidelines (e.g. linter), we would like to keep our OSS projects consistent with that. For this, I can add our lint rules and other guidelines to this repository and do a final formatting as soon as the above points are ready. 

Curious to hear your thoughts on this direction and happy to support in any way. I do think that this is a great way to make this repository a lot more useful for the masses. 

Big thanks again for putting this together ❤️

2020-10-15 20:29 UTC, unnamedd commented
Hi all,

after two busy weeks between pauses and implementations, here we are! The pull request is now ready for be reviewed. There are more things to be implemented and I left some "doors half opened" to help us in the future. 

Most of the requests made by @thomaspaulmann on his fist comment is covered, but if you'd like to check which notes guided me here, please, check it out this [GitHub Project](https://github.com/unnamedd/script-commands/projects/1). 

Soon, the notes we have in that GitHub Project should be also available here.

Hope you all like the contribution.

Cheers.

2020-10-18 18:58 UTC, thomaspaulmann requested changes
Thanks for this gorgeous tool! It will help a great deal to keep the documentation of the repository up-to-date. In general, everything looks good. There are a few things that we should finalize before merging the PR into master:

1. Seems that the linter wasn't applied yet (judging the 4 spaces instead of 2 ;-)). Let's do one final formatting before merging the PR.
2. Let's rename the CLI tool from "Collector" to "Toolkit". You already mention it in the documentation and the name fits better since it isn't a simple collector anymore, it's much more :-) 
3. Let's remove the commands that aren't implemented yet (I think it's only the create command). 

I set up the secret for the GitHub Action. Could you do a test and let me know if something doesn't work and I'll fix.

Thanks again for all the hard work. It's wonderful to see this tool come together <3

2020-10-18 18:58 UTC, thomaspaulmann commented on .github/workflows/documentation.yml
> +    branches: [ main, master, Extensions-Collector-Tool]
Please drop the branch of this PR before merging it.

2020-10-18 18:58 UTC, thomaspaulmann commented on .github/workflows/documentation.yml
> +    branches: [ main, master, Extensions-Collector-Tool]
Do we need that? I would assume that the master branch is always up-to-date when it comes to documentation. Separate branches don't necessarily need to trigger the autogeneration. What do you think?

2020-10-18 18:58 UTC, thomaspaulmann commented on .github/workflows/documentation.yml
> +        git add ../../raycast-extensions.md ../../raycast-extensions.json
How about dropping Raycast in the filename? Doesn't feel that it adds much value. I'm not sure if the JSON is necessary in the repository. I would probably leave it out or do you have any strong reason here?

```suggestion
        git add ../../extensions.md ../../extensions.json
```

2020-10-18 18:58 UTC, thomaspaulmann commented on .github/workflows/documentation.yml
> +        github_token: ${{ secrets.RAYCAST_BOT_ACCESS_TOKEN }}
I set up the secret in the repo. Maybe do a final test if it works. If not, please let me know.

2020-10-18 18:58 UTC, thomaspaulmann commented on README.md
> +Check the list of Script Commands [available here](raycast-extensions.md)
```suggestion
Check out the [list](raycast-extensions.md) of all available Script Commands.
```

2020-10-18 18:58 UTC, thomaspaulmann commented on Tools/Collector/Sources/Collector/Extensions/FileSystem+AbsolutePath.swift
> +
In our code style we don't add new lines here. Looks like the linter didn't catch them.

2020-10-18 18:58 UTC, thomaspaulmann commented on Tools/Collector/Sources/Collector/SubCommands/CreateScript.swift
> +            print("To be implemented")
Let's drop this sub command until it's properly implemented.

2020-10-18 18:58 UTC, thomaspaulmann commented on raycast-extensions.md
> +
Remove the empty line
```suggestion
```

2020-10-18 18:58 UTC, thomaspaulmann commented on system/toggle-desktop-icons.applescript
> +# @raycast.description A script command to show and hide icons of Desktop folder
I'm happy to provide descriptions for all other commands.

2020-10-18 19:17 UTC, unnamedd commented on .github/workflows/documentation.yml
> +    branches: [ main, master, Extensions-Collector-Tool]
We just need the `master` branch for now, but I strongly suggest to use `main` instead of `master`. In any case, we can use whatever name you prefer, the only thing I'd like to have is a Suggestion Change here and then I can just accept without have to change local and then push it here. :D

2020-10-18 19:18 UTC, unnamedd commented on .github/workflows/documentation.yml
> +        github_token: ${{ secrets.RAYCAST_BOT_ACCESS_TOKEN }}
If you already set up, we don't need to do anything else, as soon the PR is merged it will start to work.

2020-10-18 19:20 UTC, unnamedd commented on raycast-extensions.md
> +
Will do in the template to generate the this file.

2020-10-18 19:21 UTC, unnamedd commented on Tools/Collector/Sources/Collector/Extensions/FileSystem+AbsolutePath.swift
> +
Actually I had to remove the linter, but I will run it again now to fix this kind of issue.

2020-10-18 19:48 UTC, unnamedd commented on .github/workflows/documentation.yml
> +    branches: [ main, master, Extensions-Collector-Tool]
For sure, I will remove!

2020-10-19 11:53 UTC, thomaspaulmann commented on Tools/Toolkit/README.md
> +This is a shared place and we're always looking for new Script Commands or other ways to improve Raycast. If you have anything cool to show, please send us a pull request. If we screwed something up,
I created a redirect for the community. Let's use it instead of the hardcoded Slack invitation link.

```suggestion
This is a shared place and we're always looking for new Script Commands or other ways to improve Raycast. If you have anything cool to show, please send us a pull request. If we screwed something up, please report a bug. Join our [Slack community](https://www.raycast.com/community) to brainstorm ideas with like-minded folks.
```

2020-10-20 14:02 UTC, thomaspaulmann commented on extensions.json
> +[
@unnamedd it worked 🥳 The machines are taking over 🤖

2020-10-27 19:17 UTC, thomaspaulmann commented
Thanks for applying all the changes. The tool is ready to be merged. Can you fix the conflicts and then I'll merge it. Also, sorry for the delay.

2020-10-27 20:03 UTC, unnamedd commented
There was no conflicts to be resolved, just a merge from master to my branch which is also done @thomaspaulmann! ;)

2020-10-27 22:17 UTC, thomaspaulmann approved these changes
Ok, lets get it merged! Gonna be a great addition to the documentation and for n00bs to explore the commands in this repository 🎉

2020-10-27 22:18 UTC, merged