✨ Create rust crate
raycast/script-commands pull request #302
Opened 2021-03-13 22:30 UTC by Matt-Gleich

## Description

Added a new script command that will take a crate name and automatically search for it on crates.io.

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

https://user-images.githubusercontent.com/43759105/111051517-9dbb0a00-8421-11eb-83ef-25828049ef61.mov

## Dependencies / Requirements

Nothing is required

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-03-13 23:58 UTC, unnamedd requested changes

2021-03-13 23:58 UTC, unnamedd commented on commands/developer-utils/rust-crate.sh
> +# @raycast.needsConfirmation false
@Matt-Gleich both `currentDirectoryPath` and `needsConfirmation` isn’t needed here.

2021-03-13 23:58 UTC, unnamedd commented on commands/developer-utils/rust-crate.sh
> +#!/bin/bash
This Script Command must be in `web-searches`.

2021-03-13 23:58 UTC, unnamedd commented on commands/developer-utils/rust-crate.sh
> +# @raycast.packageName Rust
```suggestion
# @raycast.packageName Web Seaches
```

2021-03-14 00:45 UTC, Matt-Gleich commented
Thanks for the review! Just made those changes.

2021-03-14 01:00 UTC, unnamedd approved these changes
Great @Matt-Gleich! Looks good to me!

2021-03-14 22:01 UTC, thomaspaulmann commented on commands/web-searches/rust-crate.sh
> +# @raycast.argument1 { "type": "text", "placeholder": "name", "percentEncoded": true }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Name", "percentEncoded": true }
```

2021-03-14 22:01 UTC, merged