Add Script Command: github-unread-notifications
raycast/script-commands pull request #31
Opened 2020-11-06 01:23 UTC by crstauf

2020-11-06 13:55 UTC, thomaspaulmann commented
Top addition! I'll favorite that command in Raycast to see upcoming PRs from you ;-)

2020-11-06 13:56 UTC, thomaspaulmann commented on developer-utils/github-unread-notifications.sh
> +# @raycast.icon images/github-logo.png
Reminds me that we should have support for dark and light theme icons.

2020-11-06 13:58 UTC, thomaspaulmann requested changes
I think we can improve the title and message of the command to reduce the repetitive content. I left some suggestions inline. Also, could you add a screenshot of the command to the PR? This makes it easier to review. We should have probably a template for PRs that outlines this

2020-11-06 13:58 UTC, thomaspaulmann commented on developer-utils/github-unread-notifications.sh
> +# @raycast.title GitHub Unread Notifications
```suggestion
# @raycast.title Unread Notifications
```

We usually don't specify the extension name in the command, e.g. `My Open Pull Requests`.

2020-11-06 13:58 UTC, thomaspaulmann commented on developer-utils/github-unread-notifications.sh
> +	echo 'No unread notifications'
Should we keep this shorter? Seems like it's repeating the command name.

2020-11-06 14:14 UTC, crstauf commented
> could you add a screenshot of the command to the PR?

@thomaspaulmann Here you are! Having a PR template is a great idea!

![Screen Shot 2020-11-06 at 9 11 15 AM](https://user-images.githubusercontent.com/4573033/98375613-573b4600-2010-11eb-9a41-e0e98fa98397.png)
![Screen Shot 2020-11-06 at 9 11 32 AM](https://user-images.githubusercontent.com/4573033/98375616-573b4600-2010-11eb-8d0e-14bfa7baf789.png)
![Screen Shot 2020-11-06 at 9 11 47 AM](https://user-images.githubusercontent.com/4573033/98375618-57d3dc80-2010-11eb-976c-33b2ac0d9a38.png)

2020-11-06 19:04 UTC, thomaspaulmann commented
Let's remove the white border of the GitHub icon. You can use that one. @PitNikola, we should add support for light/dark theme icons for script commands to make them pretty.

Here is the icon (it's white ;-)): 
![github](https://user-images.githubusercontent.com/12066405/98404595-ccd00200-2062-11eb-9a1f-2af91bd5332a.png)

2020-11-06 19:33 UTC, crstauf commented
> here is the icon

@thomaspaulmann Won't this disappear for anyone using the light theme?

2020-11-06 19:42 UTC, thomaspaulmann commented
Unfortunately it will but looks better on dark theme. We'll add support for light/dark theme icons. Then we can address it across all commands in this repo.

2020-11-06 20:19 UTC, crstauf commented
@thomaspaulmann Okay; will update once #32 is merged.

2020-11-08 10:49 UTC, thomaspaulmann commented
Ok, so I guess we need to merge this one first then.

2020-11-08 10:49 UTC, merged

2020-11-08 14:17 UTC, crstauf commented
> Ok, so I guess we need to merge this one first then.

Actually I was planning to merge `master` into this branch, but this works too.