Add Session scripts
raycast/script-commands pull request #310
Opened 2021-03-17 16:50 UTC by jamesjlyons

## Description

Add commands to control Session app

## Type of change

- [x] New script command

## Screenshot

Cleanshot gif demo:
https://cln.sh/lkxhCO

## Dependencies / Requirements

Requires Session 2.1.6 https://www.stayinsession.com/

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-03-18 16:25 UTC, unnamedd requested changes
Hey @jamesjlyons, nice addition, even if I couldn't test in my Session version (I'm not Pro user).

Comments made, check it out when possible. If you need anything, please, let us know.

2021-03-18 16:25 UTC, unnamedd commented on commands/apps/session/session-start-new.sh
> +# @raycast.argument1 { "type": "text", "placeholder": "Intent", "optional": true }
This is something you don't need to use: `// /%20`. It is solved internally by Raycast just using a property here:
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Intent", "optional": true, "percentEncoded": true }
```

2021-03-18 16:25 UTC, unnamedd commented on commands/apps/session/session-start-new.sh
> +open "session:///start?intent=${1// /%20}&duration=${2}"
```suggestion
open "session:///start?intent=${1}&duration=${2}"
```

2021-03-18 16:25 UTC, unnamedd commented on commands/apps/session/session-start-new.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "Duration", "optional": true }
I'm not sure, but I guess the duration in Session accept minutes, right? I guess an indication here might be good.

```suggestion
# @raycast.argument2 { "type": "text", "placeholder": "Minutes duration", "optional": true }
```

2021-03-18 16:25 UTC, unnamedd commented on commands/README.md
>  #### Sip
This file is auto-generated. You don't need to change it.

2021-03-18 16:25 UTC, unnamedd commented on commands/apps/session/session-abandon.sh
> +# Note: Session X v2.1.6 required: https://www.stayinsession.com/
To keep the conformance with our current style to indicate that your Script Command has an external dependency, let change the above line and in the other files to the suggestion:

```suggestion
# Dependency: This script requires `Session X v2.1.6` installed: https://www.stayinsession.com/
```

2021-03-18 16:25 UTC, unnamedd commented on commands/apps/session/session-abandon.sh
> +open "session:///abandon"
This is the first time I see three slash bars in the URL Scheme. Question: is this working nicely? I've tried here, but this is a Pro feature and I could test if it is working properly or not.

2021-03-18 16:25 UTC, unnamedd commented on commands/extensions.json
> +          ]
This file is auto-generated, you don't need to modify it.

2021-03-18 16:42 UTC, jamesjlyons commented on commands/apps/session/session-start-new.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "Duration", "optional": true }
You would be right, good call!

2021-03-18 16:45 UTC, jamesjlyons commented on commands/README.md
>  #### Sip
I didn't manually change this file, it seems like it was generated when I initiated the pull request. Same with the 'commands/extensions.json' file. I received this email, if it's of any help:
<img width="679" alt="CleanShot 2021-03-18 at 09 44 25@2x" src="https://user-images.githubusercontent.com/4167843/111664013-95baeb80-87ce-11eb-9124-dfd9533256db.png">

2021-03-18 16:47 UTC, jamesjlyons commented on commands/apps/session/session-abandon.sh
> +open "session:///abandon"
Same, but it's working fine here! I pulled it from Session's docs.

2021-03-18 16:48 UTC, jamesjlyons commented on commands/extensions.json
> +          ]
See comment above on `commands/README.md`

2021-03-18 17:45 UTC, unnamedd commented on commands/README.md
>  #### Sip
Ahhh okay, I know what happened. The GitHub Actions runs in the `master` branch and your implementations was done in this branch, then the action was activated! If you have worked in a separated branch, this wouldn't happen. 

Thanks a lot for let me know of that!

2021-03-18 17:46 UTC, unnamedd commented on commands/apps/session/session-abandon.sh
> +open "session:///abandon"
Great! Thanks for the answer! :D

2021-03-18 23:37 UTC, jamesjlyons commented on commands/README.md
>  #### Sip
Got it! I'll go back to working from branches in the future. Do you need me to start a new pull request or can we ignore these files on merge?

2021-03-19 01:31 UTC, unnamedd commented on commands/README.md
>  #### Sip
Don't worry @jamesjlyons, it will be overwritten anyway!

2021-03-19 01:34 UTC, unnamedd commented
@jamesjlyons as we have conflicts with `extensions.json` you will have to merge merge the master branch from this repo to yours to solve the conflict before the Raycast team be able to merge your pull request here. You don't need to close this pull request and create another, just try to fix the problem and then they should merge soon.

2021-03-21 03:26 UTC, jamesjlyons commented
@unnamedd Alright, conflicts should be fixed. Thanks for the help 🙌

2021-03-25 21:08 UTC, fe9lix commented
Any updates here?

2021-03-28 04:12 UTC, jamesjlyons commented
> Any updates here?

I had the conflicts resolved but it looks like there's more now. I'll merge the main branch in again

2021-03-28 04:19 UTC, jamesjlyons commented
@fe9lix should be good to merge again

2021-03-29 17:46 UTC, fe9lix approved these changes

2021-03-29 17:46 UTC, merged