Draft scripts
raycast/script-commands pull request #311
Opened 2021-03-17 17:55 UTC by FSipiano

## Description

Draft script commands

## Type of change

- [ ] New script command

## Screenshot

## Dependencies / Requirements

## Checklist

- [ ☑️] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-03-17 22:50 UTC, thomaspaulmann requested changes
Wohoo, can't wait to have this scripts in the repository! I've added a bunch of comments. Mostly cosmetic changes to apply with our best practices for script commands.

2021-03-17 22:50 UTC, thomaspaulmann commented on GitHubPRsInline.rb
> +#!/usr/bin/env ruby
Seems like a left-over. Could you please remove the file to avoid duplicates.

2021-03-17 22:50 UTC, thomaspaulmann commented on GitHubpage.sh
> +#!/bin/bash
Same, also a duplicate. Can you please remove.

2021-03-17 22:50 UTC, thomaspaulmann commented on GithubPRsfullOutput.rb
> +#!/usr/bin/env ruby
And the third one :-) Pleas remove.

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/GitHub-PRs-Inline.rb
> +# @raycast.packageName GitHub
Let's be a good citizen and follow the sections of the parameters and move the two parameters down to the `Optional parameters`. I suggest to start with the `packageName`, then `icons`, then `refreshTime`. I sometimes create aanother section called `Conditional parameters` where I add the `refreshTime`.

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/GitHub-PRs-Inline.rb
> +# @raycast.needsConfirmation false
This is unnecessary because `false` is the default value.

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/GitHub-PRs-Inline.rb
> +end
I'd suggest to split constants that the user should configure and constants that you use in code. The ones that an user of the script needs to configure should be earlier and have a comment to describe how to get the information.

```suggestion
# Insert a personal access token (https://github.com/settings/tokens)
API_TOKEN = ''

if API_TOKEN.empty?
  puts 'No API token provided'
  exit(1)
end

RED = 31
GREEN = 32
YELLOW = 33
```

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/GitHub-PRs-Inline.rb
> +req.body = '{ "query": "query { viewer { pullRequests(first: 10, states:OPEN) { nodes { title number url } }}}" }'
Keeping the spacing consistent :-)
```suggestion
req.body = '{ "query": "query { viewer { pullRequests(first: 10, states:OPEN) { nodes { title number url } } } }" }'
```

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/GitHub-PRs-Inline.rb
> +    puts "\e[#{GREEN}m#{MESSAGE}\e[0m"
Since this is a local variable, it should be lowercase. Only constants are UPPERCASE in Ruby.

```suggestion
    message = "No open pull requests 🎉"
    puts "\e[#{GREEN}m#{message}\e[0m"
```

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/GitHub-PRs-Inline.rb
> +  end
I think you can avoid some duplicated code here.

```suggestion
  else
    color = (pull_requests.length <= 5) ? YELLOW : GREEN
    message = "You have #{pull_requests.length} open pull requests"
    puts "\e[#{color}m#{message}\e[0m"
    pull_requests.each do |pr|
      puts "##{pr['number']} #{pr['title']} (#{pr['url']})"
    end
  end
```

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/GitHub-open-page.sh
> +# @raycast.title Open PR page
Let's not use any abbreviations. You can still search for the command with `pr` in Raycast.

```suggestion
# @raycast.title Open Pull Requests Page
```

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/GitHub-open-page.sh
> +# @raycast.iconDark images/github-logo-iconDark.png
Please add the `packageName` here. We have a rule to always specify a package name for scripts in this repository. This makes it easier for others to copy the script locally. Technically the name isn't necessary and it would infer the package name from the parent directory.

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/Github-PRs-fullOutput.rb
> +# @raycast.packageName GitHub
Similar as before, please move the parameters to the according sections.

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/Github-PRs-fullOutput.rb
> +# @raycast.title Show all Pull Requests detail
We title-case all command titles. How about naming the command like this:

```suggestion
# @raycast.title Show Open Pull Requests
```

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/Github-PRs-fullOutput.rb
> +#!/usr/bin/env ruby
Please use lowercase for the command filename and mark it as a template: `github-pull-requests-details.template.rb`

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/GitHub-open-page.sh
> +#!/bin/bash
Please use lowercase for the script command filename to match the others: `github-open-pull-requests-page.sh`

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/GitHub-PRs-Inline.rb
> +#!/usr/bin/env ruby
Please lowercase the filename to match other scripts and add `.template.` to the name: `github-open-pull-requests.template.rb` The template indicates that you need to adjust some parameters in the script. It's explained in the README. Note: We don't show template scripts in Raycast until the `.template.` is removed from the script name.

2021-03-17 22:50 UTC, thomaspaulmann commented on commands/developer-utils/Github-PRs-fullOutput.rb
> +req.body = '{ "query": "query { viewer { pullRequests(first: 10 states: OPEN) { nodes {baseRepository {name} title number url} }}}" }'
```suggestion
req.body = '{ "query": "query { viewer { pullRequests(first: 10 states: OPEN) { nodes {baseRepository {name} title number url} } } }" }'
```

2021-03-18 08:10 UTC, FSipiano commented on commands/developer-utils/GitHub-PRs-Inline.rb
> +end
Really good idea with the comments in it, it makes sense for this to be off-the-shelf readable, and usable.

2021-03-18 08:54 UTC, unnamedd commented
@FSipiano please move the files to the `github` folder inside of `developer-utils`.

2021-03-18 09:09 UTC, unnamedd requested changes
Hi @FSipiano, welcome again and thanks for your first contribution!

I also realised that you added your files in the root of the `developer-utils`, but we do have a specific folder for GitHub, where your Script Commands will fit better.

2021-03-18 09:09 UTC, unnamedd commented on commands/developer-utils/github-open-pull-requests.template.rb
> +API_TOKEN = '20158b78b1882b438a787756898382b3c5bcea80'
You forgot you key here, I guess you will have to delete it in your account.

2021-03-18 09:09 UTC, unnamedd commented on commands/developer-utils/github-open-pull-requests-details.template.rb
> +req.body = '{ "query": "query { viewer { pullRequests(first: 10 states: OPEN) { nodes {baseRepository {name} title number url} } } }" }'
To keep the consistency suggested by Thomas, lets add some more spaces here.
```suggestion
req.body = '{ "query": "query { viewer { pullRequests(first: 10 states: OPEN) { nodes { baseRepository { name } title number url } } } }" }'
```

2021-03-18 09:09 UTC, unnamedd commented on commands/developer-utils/github-open-pull-requests-details.template.rb
> +# @raycast.icon images/github-logo.png
You're missing your credits here:
```suggestion
# @raycast.icon images/github-logo.png

# Credits
# @raycast.author Faye Sipiano
# @raycast.authorURL https://github.com/FSipiano
```

2021-03-18 09:09 UTC, unnamedd commented on commands/developer-utils/github-open-pull-requests-page.sh
> +
```suggestion

# Credits
# @raycast.author Faye Sipiano
# @raycast.authorURL https://github.com/FSipiano
```

2021-03-18 09:09 UTC, unnamedd commented on commands/developer-utils/github-open-pull-requests.template.rb
> +
```suggestion

# Credits
# @raycast.author Faye Sipiano
# @raycast.authorURL https://github.com/FSipiano
```

2021-03-18 10:20 UTC, FSipiano commented on commands/developer-utils/github-open-pull-requests.template.rb
> +API_TOKEN = '20158b78b1882b438a787756898382b3c5bcea80'
Ah that snuck in there while I was testing! Great spot, thank you, I had already deleted the key as it was just for testing, but I will look out for that next time, thanks!!

2021-03-18 10:23 UTC, FSipiano commented on commands/developer-utils/github-open-pull-requests-page.sh
> +
🥇

2021-03-18 10:26 UTC, FSipiano commented on commands/developer-utils/github-open-pull-requests-details.template.rb
> +req.body = '{ "query": "query { viewer { pullRequests(first: 10 states: OPEN) { nodes {baseRepository {name} title number url} } } }" }'
Thanks for the suggestions, you are right in that it makes it more consistent! I didn't know how Ruby deals with whitespace, but looks like it's fine and I agree that this makes it look a lot better

2021-03-18 10:36 UTC, thomaspaulmann commented on commands/developer-utils/github-open-pull-requests-details.template.rb
> +# @raycast.icon images/github-logo.png
@unnamedd oh good catch. Totally missed that one 🙈 We should also add the description parameter to give it a nice representation in the commands overview.

2021-03-18 10:39 UTC, unnamedd commented on commands/developer-utils/github-open-pull-requests-details.template.rb
> +# @raycast.icon images/github-logo.png
and I forgot the description @thomaspaulmann 🙈🤣!

2021-03-18 10:42 UTC, unnamedd commented on commands/developer-utils/github-open-pull-requests-details.template.rb
> +req.body = '{ "query": "query { viewer { pullRequests(first: 10 states: OPEN) { nodes {baseRepository {name} title number url} } } }" }'
Actually in this case isn't Ruby, but GraphQL. It's nice to have some spaces just to keep the query nice in the Script Command. It won't hurt any rule from Ruby, but as you added some spaces in other queries, looks nice to have them also here! 😄

2021-03-18 10:45 UTC, unnamedd commented on commands/developer-utils/github-open-pull-requests-details.template.rb
> +# @raycast.icon images/github-logo.png
Regarding the description, this is what you need yo add a nice description to your Script Command in our Awesome Script Commands README.

```ruby
# @raycast.description A nice description for your Script Command should be written here
```

2021-03-18 11:20 UTC, thomaspaulmann approved these changes
Nice! Gonna be some great additions to the GitHub scripts that we've already have. I recommend to add a description to each command. The description is shown in the commands overview.

2021-03-18 11:20 UTC, thomaspaulmann commented on commands/developer-utils/github/github-open-pull-requests-details.template.rb
> +API_TOKEN = ''
```suggestion
# Insert a personal access token (https://github.com/settings/tokens)
API_TOKEN = ''
```

2021-03-18 11:20 UTC, thomaspaulmann commented on commands/developer-utils/github/github-open-pull-requests.template.rb
> +#insert a personal access token (https://github.com/settings/tokens)
```suggestion
# Insert a personal access token (https://github.com/settings/tokens)
```

2021-03-18 11:20 UTC, thomaspaulmann commented on commands/developer-utils/github/github-open-pull-requests-details.template.rb
> +    else
```suggestion
  else
```

2021-03-18 11:20 UTC, thomaspaulmann commented on commands/developer-utils/github/github-open-pull-requests-page.sh
> +open https://github.com/pulls/
```suggestion
# @raycast.authorURL https://github.com/FSipiano

open https://github.com/pulls/
```

2021-03-18 15:56 UTC, unnamedd approved these changes
Looks great to me as well, nice job @FSipiano!

2021-03-18 17:45 UTC, merged