Rich text to markdown
raycast/script-commands pull request #328
Opened 2021-03-23 17:20 UTC by adam-zethraeus

1. pastes clipboard as html through applescript call
2. processes output with perl to plain text
3. uses pandoc to convert html to github flavoured markdown
4. puts result back on clipboard

## Type of change

- [ ] New script command

## Screenshot

![rtf2md](https://user-images.githubusercontent.com/509838/112059097-a940bc00-8b18-11eb-8d6d-9e94bb248689.gif)
 ^ now outputs github flavoured markdown instead.

## Dependencies / Requirements

Requires [pandoc](https://pandoc.org/).

`brew install pandoc`

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-03-23 17:38 UTC, unnamedd requested changes
Hi @adam-zethraeus, 
I made some small comments here to make your Script Command conformant to the guideline of this repository. As soon you have address them, please let me know for a second review.

Thanks for your contribution and welcome aboard!

2021-03-23 17:38 UTC, unnamedd commented on commands/system/rich-text-clipboard-to-markdown.sh
> +# @raycast.title rtf2md
> Title: Raycast's UI adopts title-cased strings for all command titles as per Apple's Human Interface Guidelines. Please make sure your command title follows this pattern to look good between other commands.  

Source: [Metadata conversion](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#metadata-convention)

```suggestion
# @raycast.title Rich Text to Markdown
```

2021-03-23 17:38 UTC, unnamedd commented on commands/system/rich-text-clipboard-to-markdown.sh
> +# @raycast.description Convert rich text clipboard data to github flavoured markdown using pandoc
```suggestion
# @raycast.description Convert rich text clipboard data to GitHub Flavoured Markdown using pandoc
```

2021-03-23 17:38 UTC, unnamedd commented on commands/system/rich-text-clipboard-to-markdown.sh
> +
As `pandoc` isn’t a software embedded by default in the system, it is important to follow the guideline of this repository and add indication of the need of the software used, please check this session in the guideline:
[Scripts that require installation of runtimes and dependencies](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-runtimes-and-dependencies)

```
# Dependency: This script requires `jq` cli installed: https://stedolan.github.io/jq/
# Install via homebrew: `brew install jq`
```

2021-03-23 17:38 UTC, unnamedd commented on commands/system/rich-text-clipboard-to-markdown.sh
> +export LC_CTYPE=UTF-8
We need to add a check for the availability of the dependency before the use, i.e: 

```shell

if ! command -v download &> /dev/null; then
  echo "download command is required (https://github.com/kevva/download-cli).";
  exit 1;
fi
```

2021-03-23 17:47 UTC, adam-zethraeus reviewed
@unnamedd done!

2021-03-25 21:06 UTC, fe9lix commented
Hi! Should we better move that script into the conversions folder (and packageName would be Conversions)?

2021-03-25 21:07 UTC, adam-zethraeus commented
happy to. (also y'all have the checkmark to just make edits and put it where you want if you'd prefer)

2021-03-25 21:18 UTC, fe9lix commented
Please go ahead...we'll merge after the change.

2021-03-25 21:23 UTC, adam-zethraeus commented
@fe9lix done

2021-03-25 21:52 UTC, merged