Add Base64 encode / decode, md5 encrypt, sha1 encrypt
raycast/script-commands pull request #333
Opened 2021-03-25 14:14 UTC by hzb

## Description

Add some script-commands: Base64 encode / decode, MD5 encrypt, SHA1 encrypt

## Type of change

- [X] New script command

## Screenshot

<img width="862" alt="base64" src="https://user-images.githubusercontent.com/535675/112486914-46b91b80-8db7-11eb-952f-5260a0438868.png">

## Dependencies / Requirements

SHA1 requires `md5sha1sum`, you can install via Homebrew. 

```
brew install md5sha1sum
```

I have wrote it on its description.

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-03-25 21:03 UTC, fe9lix requested changes
Hi! Some comments:

- We do already have base64 encode and decode scripts, please check: https://github.com/raycast/script-commands/tree/master/commands

- MD5 and SHA are hashing functions so I would remove "Encrypt" from the the title and descriptions

- Both md5 and shamus are built-in macOS functions, so there would be no need for a dependency

2021-03-25 23:10 UTC, hzb commented
@fe9lix 

- I saw those scripts and they are good. We each have their own advantages in use.

- Rename to `MD5 Hash` and `SHA Hash`, and the descriptions were also updated.

- Upgrade to use the built-in SHA function of macOS.

2021-03-26 03:58 UTC, hzb reviewed
Checked and WFM

2021-03-26 08:53 UTC, fe9lix approved these changes

2021-03-26 08:54 UTC, merged