New Script: Quit all Airdrop processes
raycast/script-commands pull request #344
Opened 2021-04-06 19:28 UTC by linus569

## Description

The script kills all AirDrop processes running on the Mac. I have the problem that AirDrop freezes from time to time and maybe I'm not the only one. This script makes it easy to quit all processes and use AirDrop again.

## Type of change

- [x] New script command

## Screenshot
![ezgif-1-d74516c215be](https://user-images.githubusercontent.com/29883712/113767237-be276d00-971e-11eb-8b8f-0a4e3f7a552c.gif)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-04-06 22:18 UTC, unnamedd requested changes
Hi @linus569, I made some small comments to keep the consistency in your Script Command.

Thanks for your first contribution and welcome aboard!

2021-04-06 22:18 UTC, unnamedd commented on commands/system/quit-airdrop-process.sh
> +# @raycast.title Quit AirDrop
```suggestion
# @raycast.title Kill AirDrop Processes
```

2021-04-06 22:18 UTC, unnamedd commented on commands/system/quit-airdrop-process.sh
> +# @raycast.description Quits all AirDrop processes
```suggestion
# @raycast.description Force kill all AirDrop processes
```

2021-04-06 22:18 UTC, unnamedd commented on commands/system/quit-airdrop-process.sh
> +#!/bin/bash
Will fit better if you rename this file to `kill-airdrop.processes.sh`.

2021-04-06 23:14 UTC, linus569 commented
Thanks for your help, improved it with your suggestions

2021-04-07 07:23 UTC, RSO approved these changes

2021-04-07 07:23 UTC, RSO commented
Looks good to me, thanks!

2021-04-07 07:23 UTC, merged