Add script command: Show disk usage of / (root)
raycast/script-commands pull request #375
Opened 2021-04-25 21:26 UTC by jesse-c

## Description

Adds an inline script command to display the disk usage of your / (root).

It can relatively easily be adapted to a different disk, or even multiple disks.

## Type of change

- [x] New script command

## Screenshot

<img width="732" alt="image" src="https://user-images.githubusercontent.com/1405676/116010131-bfa4d080-a60c-11eb-9095-cee4bbb865f7.png">

## Dependencies / Requirements

N/A

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-04-26 15:56 UTC, unnamedd approved these changes
Very nice addition @jesse-c!  👏 👏

2021-04-26 19:04 UTC, fe9lix requested changes
@jesse-c Cheers! Could you make a small change to the title? "Disk usage" -> "Disk Usage"

2021-04-26 23:23 UTC, jesse-c commented
> @jesse-c Cheers! Could you make a small change to the title? "Disk usage" -> "Disk Usage"

Done. :)

2021-04-27 06:02 UTC, fe9lix approved these changes

2021-04-27 06:02 UTC, merged