Add "Toggle Natural Scrolling" command
raycast/script-commands pull request #383
Opened 2021-04-28 20:24 UTC by wileymarques

## Description

Script Command to change natural trackpad/mouse scrolling setting.

The script reverts the setting value each time.

## Type of change

- [ ] New script command

## Screenshot

https://user-images.githubusercontent.com/1015148/116467698-5a3c2400-a846-11eb-96f7-d57f000c7c3f.mov

## Dependencies / Requirements

None.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-04-28 21:01 UTC, fe9lix reviewed
Hey @wileymarques – I'm curious what the use case for this script is? In what situations would you run the script?

2021-04-29 14:39 UTC, wileymarques commented
I often switch from trackpad and mouse while using my Mac. Natural scrolling isn't so "natural" for me on a mouse, so I keep turning this feature on and off during the day.

I think this is a thing for people coming from Windows. Since I have some colleagues at work that suffer from the same "issue".

2021-04-29 15:05 UTC, fe9lix approved these changes
Thanks for the explanation!

2021-04-29 15:05 UTC, merged

2021-04-29 15:59 UTC, unnamedd requested changes

2021-04-29 15:59 UTC, unnamedd commented on commands/system/toggle-natural-scrolling.applescript
> +# @raycast.description Script Command to change natural trackpad/mouse scrolling setting. Reverting the setting value each time.
```suggestion
# @raycast.description Change natural trackpad/mouse scrolling setting. Reverting the setting value each time.
```

2021-04-29 15:59 UTC, unnamedd commented on commands/system/toggle-natural-scrolling.applescript
> +delay 0.6
Why do you need this delay? Isn't it giving you the access to the trackpad settings right after you activate it?

2021-04-29 15:59 UTC, unnamedd commented on commands/system/toggle-natural-scrolling.applescript
> +    click checkbox 1 of tab group 1 of window "Trackpad"
If Apple decides to reorder the elements, your Script Command won't work correctly, am I right?