Batch modify file extension
raycast/script-commands pull request #390
Opened 2021-05-01 13:18 UTC by LokHsu

## Description

+ new script command:
+ commands/system/modify-extension.sh:
+ Batch modify the file in the current directory or the specified extension of the selected file
## Type of change

- [x] New script command

## Screenshot

![GIF1](https://user-images.githubusercontent.com/71050409/116782232-78aa5580-aaba-11eb-99b3-8799cd25c2a9.GIF)

![GIF2](https://user-images.githubusercontent.com/71050409/116782194-4ef12e80-aaba-11eb-9540-a331519ac412.GIF)

## Dependencies / Requirements

+ You must enter the search extension in 'Before' and the modified extension in 'After'

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-05-02 23:57 UTC, unnamedd requested changes
Hi @LokHsu, a really small change to be done here to keep your `title` in conformance to the repository’s guideline.

2021-05-02 23:57 UTC, unnamedd commented on commands/system/modify-extension.sh
> +# @raycast.title Modify extension
```suggestion
# @raycast.title Modify File Extension
```

2021-05-03 02:08 UTC, LokHsu commented
> @LokHsu，您好，这里要做的很小的更改是为了使您`title`与存储库的指南保持一致。

I have finished the change of this file according to your suggestion.

2021-05-03 13:46 UTC, dehesa commented
Pretty useful stuff, thanks @LokHsu

2021-05-03 13:46 UTC, merged