Add "Slack Good Morning in #general"
raycast/script-commands pull request #392
Opened 2021-05-01 17:21 UTC by farisaziz12

## Description

Script command that uses AppleScript to send a random good morning message (e.g. "Good Morning all!") to the `#general` chat. There are 3 optional arguments:
1. `channel` send the random good morning text to another specified channel (e.g. `#random`)
2. `message` send another message besides the random good morning message
3. `setActive` takes a `y/n` argument to optionally set yourself as active when sending the good morning text

**Note:** setting status as active only works when inactive. If the user is already active then the message is still sent (hence it being placed before the activation command) and Slackbot will throw an error only visible to you that it's an invalid command.

## Type of change

- [x] New script command

## Screenshot

## Dependencies / Requirements

N/A

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-05-02 23:52 UTC, unnamedd requested changes
Hello @farisaziz12,
please, take a look into my comments and after address them, please, let us know!

Thanks for your contribution!

2021-05-02 23:52 UTC, unnamedd commented on commands/communication/slack/send-channel-good-morning.applescript
> +# @raycast.packageName Slack Channel Good Morning
```suggestion
# @raycast.packageName Slack
```

2021-05-02 23:52 UTC, unnamedd commented on commands/communication/slack/send-channel-good-morning.applescript
> +#!/usr/bin/osascript
The file should be renamed to `send-slack-message.applescript` or `slack-send-message.applescript`.

2021-05-02 23:52 UTC, unnamedd commented on commands/communication/slack/send-channel-good-morning.applescript
> +# @raycast.title Slack Good Morning in #general
As you might expect the user to define (or not) which channel it is going to send the message (which can be “Good Morning” or not), then IMO we should remove `#general` of the title and use `Channel`:
```suggestion
# @raycast.title Send Message in Channel
```

2021-05-02 23:52 UTC, unnamedd commented on commands/communication/slack/send-channel-good-morning.applescript
> +# @raycast.description This script sends a random good morning text to the #general channel and sets active status (can be changed using args)
```suggestion
# @raycast.description This script posts a message text to the a slack channel and sets active status (can be changed using args)
```

2021-05-02 23:52 UTC, unnamedd commented on commands/communication/slack/send-channel-good-morning.applescript
> +# @raycast.argument1 { "type": "text", "placeholder": "channel (default: #general)", "optional": true, }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Channel (default: #general)", "optional": true, }
```

2021-05-02 23:52 UTC, unnamedd commented on commands/communication/slack/send-channel-good-morning.applescript
> +# @raycast.argument2 { "type": "text", "placeholder": "message (default: good morning)", "optional": true, }
```suggestion
# @raycast.argument2 { "type": "text", "placeholder": "Message (default: good morning)", "optional": true, }
```

2021-05-02 23:52 UTC, unnamedd commented on commands/communication/slack/send-channel-good-morning.applescript
> +# @raycast.argument3 { "type": "text", "placeholder": "set active? y/n", "optional": true, }
```suggestion
# @raycast.argument3 { "type": "text", "placeholder": "Set Active? y/n", "optional": true, }
```

2021-05-02 23:52 UTC, unnamedd commented on commands/communication/slack/send-channel-good-morning.applescript
> +    if setActive = "y" then
You should support an uppercased value, in case of a user’s mistake, your Script Command won’t stop to work.

2021-05-02 23:52 UTC, unnamedd commented on commands/communication/slack/send-channel-good-morning.applescript
> +end run
Do you need all those `delays` in the methods `openChannel`, `sendMessage`, `slashCommand` and `pressReturn`? I do think that half second is a bit much and calling method after method, it should take at least 4.5 seconds if I counted correctly to finish the execution of your Script Command successfully.

2021-05-03 10:32 UTC, farisaziz12 commented on commands/communication/slack/send-channel-good-morning.applescript
> +# @raycast.title Slack Good Morning in #general
Makes sense! Thanks for the suggestion

2021-05-03 10:54 UTC, farisaziz12 commented on commands/communication/slack/send-channel-good-morning.applescript
> +# @raycast.description This script sends a random good morning text to the #general channel and sets active status (can be changed using args)
```suggestion
# @raycast.description This script posts a message text to a slack channel and sets active status (defaults to random good morning message in #general)
```
@unnamedd  how about keeping the main description about general usage of the script and in brackets mentioning default behaviour? This way the user does not need to dig through and understand the code to understand this. 😄

2021-05-03 11:00 UTC, unnamedd commented on commands/communication/slack/send-channel-good-morning.applescript
> +# @raycast.description This script sends a random good morning text to the #general channel and sets active status (can be changed using args)
Sounds good to me if you mention the default value. Explicit information is always better than an implicit ones.

2021-05-03 11:03 UTC, farisaziz12 commented on commands/communication/slack/send-channel-good-morning.applescript
> +end run
@unnamedd Thank you so much for taking the time to make your suggestions. I have actioned all of them and brought down the execution time to maximum 4 seconds. Any lower than this and the script becomes unreliable. Reducing execution time to 3.5 seconds yields issues such as this:
![Screenshot 2021-05-03 at 12 56 29](https://user-images.githubusercontent.com/53216647/116868850-d7351800-ac0f-11eb-91e0-092a5cc2ede7.png)

2021-05-03 11:06 UTC, unnamedd commented on commands/communication/slack/send-channel-good-morning.applescript
> +end run
Nice, thanks for take a time addressing my concerns. If this is the minimum we can have, then let's go. 

Maybe a nice thing to do as an improvement here, is to use Slack API in the future.

2021-05-03 11:09 UTC, farisaziz12 commented on commands/communication/slack/send-channel-good-morning.applescript
> +end run
I would have used the slack API but wanted to reduce the hassle of getting a token to verify requests. This way you don't have to create and install an app to Slack (which may not always be an option for professional workspaces).

2021-05-03 14:28 UTC, merged

2021-05-03 14:29 UTC, dehesa commented
Thanks for this @farisaziz12