Added bcv command
raycast/script-commands pull request #443
Opened 2021-05-27 07:24 UTC by thesulaj

## Description

Added the "bcv" (`B`ase `C`on`v`erter) command. Allows the user to easily change the base of one or a series of space-delimited numbers. Very useful for embedded developers, for example.

## Type of change

- [x] New script command

## Screenshot

![Untitled](https://user-images.githubusercontent.com/34177866/119782956-9da7a380-be81-11eb-8f73-fb730068a527.gif)

## Dependencies / Requirements

N/A

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-05-27 10:05 UTC, unnamedd requested changes
Hi @thesulaj, I made some comments, when you finish to address them, please let us know for a second round of review.

Thanks for your first contribution and welcome! :D

2021-05-27 10:05 UTC, unnamedd commented on commands/developer-utils/bcv.sh
> +# @raycast.packageName Base converter
```suggestion
# @raycast.packageName Developer Utilities
```

2021-05-27 10:05 UTC, unnamedd commented on commands/developer-utils/bcv.sh
> +# @raycast.refreshTime 1h
This won't have any effect in this Script Command. `@raycast.refreshTime` only works together with the `@raycast.mode` `inline`.

```suggestion
```

2021-05-27 10:05 UTC, unnamedd commented on commands/developer-utils/bcv.sh
> +#!/bin/bash
Please, rename the file to `base-converter.sh`.

2021-05-27 10:05 UTC, unnamedd commented on commands/developer-utils/bcv.sh
> +# @raycast.author Saimir S.
You already added it above, please remove it from here.
```suggestion
```

2021-05-28 05:57 UTC, thesulaj commented
Hi @unnamedd, thanks for the reviewing the PR. I addressed all of your comments, let me know if any further changes are required.

2021-05-31 10:05 UTC, grzegorzkrukowski commented on commands/developer-utils/base-converter.sh
> +echo "$output";
Hey

It seems that $output contains some trailing whitespace - may be a good idea to use `${output##}` before copying it to pasteboard.

2021-05-31 20:01 UTC, thesulaj commented on commands/developer-utils/base-converter.sh
> +echo "$output";
Great idea, implemented. Thanks for the feedback

2021-05-31 20:22 UTC, merged