Add commands for Plash app
raycast/script-commands pull request #447
Opened 2021-05-27 18:59 UTC by sindresorhus

## Description

I'm adding commands for my Plash app: https://github.com/sindresorhus/Plash#scripting

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

<img width="886" alt="Screen Shot 2021-05-28 at 01 57 53" src="https://user-images.githubusercontent.com/170270/119882004-1ed16a00-bf58-11eb-8d26-0522e20dc904.png">

## Dependencies / Requirements

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-05-27 19:18 UTC, unnamedd requested changes
Hi @sindresorhus, thanks for you first contribution to our repository. 

Just one small change for you, please, check it out.

2021-05-27 19:18 UTC, unnamedd commented on commands/apps/plash/plash-add.sh
> +# Note: Plash v2.2.0 required
Based on our [guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-runtimes-and-dependencies), please use this example to indicate the external dependency needed in this file and in others:

```
# Dependency: This script requires `jq` cli installed: https://stedolan.github.io/jq/
# Install via homebrew: `brew install jq`
```

2021-05-27 19:44 UTC, thomaspaulmann commented on commands/apps/plash/plash-add.sh
> +open --background "plash:add?url=$1&title=$2"
**TIL:** The `open` command has a `background` option 👏

2021-05-27 19:47 UTC, thomaspaulmann commented on commands/apps/plash/plash-add.sh
> +# Note: Plash v2.2.0 required
Seems that Plash is only [available in the app store](https://github.com/sindresorhus/Plash/issues/17), so this should be fine.

2021-05-27 19:52 UTC, thomaspaulmann approved these changes
Thanks for your first contribution @sindresorhus 🎉 The commands are handy and cool app icon. I left some suggestions for more readable titles that would also match Plash's menu items. WDYT?

2021-05-27 19:52 UTC, thomaspaulmann commented on commands/apps/plash/plash-add.sh
> +# @raycast.title Add
How about adding website to the title to match your menu item?

```suggestion
# @raycast.title Add Website
```

2021-05-27 19:52 UTC, thomaspaulmann commented on commands/apps/plash/plash-next.sh
> +# @raycast.title Next
```suggestion
# @raycast.title Next Website
```

2021-05-27 19:52 UTC, thomaspaulmann commented on commands/apps/plash/plash-previous.sh
> +# @raycast.title Previous
```suggestion
# @raycast.title Previous Website
```

2021-05-28 05:50 UTC, sindresorhus commented
Good suggestions. Applied.

2021-05-28 06:01 UTC, sindresorhus commented on commands/apps/plash/plash-add.sh
> +# Note: Plash v2.2.0 required
@thomaspaulmann I just followed what CleanShot X did here, but maybe it would be useful to also include an App Store link? And maybe put that in the guidelines.

2021-05-28 09:24 UTC, thomaspaulmann commented on commands/apps/plash/plash-next.sh
> +# Note: Plash v2.2.0 required
```suggestion
# Note: Plash v2.2.0 required
# Install via Mac App Store: https://apps.apple.com/app/id1494023538
```

2021-05-28 09:24 UTC, thomaspaulmann commented on commands/apps/plash/plash-previous.sh
> +# Note: Plash v2.2.0 required
```suggestion
# Note: Plash v2.2.0 required
# Install via Mac App Store: https://apps.apple.com/app/id1494023538
```

2021-05-28 09:24 UTC, thomaspaulmann commented on commands/apps/plash/plash-reload.sh
> +# Note: Plash v2.2.0 required
```suggestion
# Note: Plash v2.2.0 required
# Install via Mac App Store: https://apps.apple.com/app/id1494023538
```

2021-05-28 09:24 UTC, thomaspaulmann commented on commands/apps/plash/plash-toggle-browser-mode.sh
> +# Note: Plash v2.2.0 required
```suggestion
# Note: Plash v2.2.0 required
# Install via Mac App Store: https://apps.apple.com/app/id1494023538
```

2021-05-28 09:27 UTC, unnamedd commented on commands/apps/plash/plash-add.sh
> +# Note: Plash v2.2.0 required
Great suggestion @thomaspaulmann! I guess this will make more sense for this and future cases where we can't use brew to install a dependency.

2021-05-28 09:30 UTC, thomaspaulmann commented
I went ahead and added the links to the Mac App Store. I've also extended our [guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-apps) to handle this case. Thanks again for the addition 👏

2021-05-28 09:30 UTC, merged