Add Script Commands: ping
raycast/script-commands pull request #46
Opened 2020-11-09 20:38 UTC by crstauf

`ping` and `ping-monitor`

2020-11-12 00:49 UTC, unnamedd approved these changes

2020-11-13 18:17 UTC, PitNikola requested changes

2020-11-13 18:17 UTC, PitNikola commented on developer-utils/ping.sh
> +# @raycast.title Ping address in clipboard
Let's name file `ping-address-from-clipboard`

2020-11-13 18:17 UTC, PitNikola commented on developer-utils/ping.sh
> +# @raycast.needsConfirmation true
Do you think this command worth having a confirmation? Doesn't seem to be that dangerous...

2020-11-13 18:17 UTC, PitNikola commented on developer-utils/ping.sh
> +ping -i 0.25 -t 3 "$clipboard"
How about using url validation here? See https://github.com/raycast/script-commands/blob/master/navigation/open-url-from-clipboard.sh

2020-11-13 18:20 UTC, crstauf commented on developer-utils/ping.sh
> +# @raycast.needsConfirmation true
Anytime I use the clipboard for specific content, I include a request for confirmation, as a double-check that clipboard contains valid content.

2020-11-13 18:21 UTC, crstauf commented on developer-utils/ping.sh
> +ping -i 0.25 -t 3 "$clipboard"
`ping` is not limited to URLs, can also be IP addresses.

2020-11-13 18:23 UTC, crstauf commented on developer-utils/ping.sh
> +# @raycast.title Ping address in clipboard
Changed to `ping-from-clipboard.sh` to be inclusive of both URLs and IP addresses.

2020-11-13 18:39 UTC, PitNikola approved these changes

2020-11-13 18:39 UTC, merged