Added script that cleans docker data
raycast/script-commands pull request #464
Opened 2021-06-06 19:36 UTC by qeude

## Description

Basic shell script that clean everything related to docker (images, containers, volumes).

## Type of change

- [x] New script command

## Screenshot

![Screen Recording 2021-06-06 at 21 28 15](https://user-images.githubusercontent.com/19294297/120937687-1d016680-c70f-11eb-93b5-d40ef773ba21.gif)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-06-06 21:44 UTC, unnamedd requested changes
Hi @qeude, thanks for your contribution adding another Script Command to Docker. 
I made some small comments here, please address them and let us know for a second round of review!

2021-06-06 21:44 UTC, unnamedd commented on commands/developer-utils/docker/clean-docker.sh
> +# @raycast.description Script that cleans Docker images, volumes, and containers
Don’t forget to add your credits here @qeude.

2021-06-06 21:44 UTC, unnamedd commented on commands/developer-utils/docker/clean-docker.sh
> +# @raycast.title Clean Docker
```suggestion
# @raycast.title Clean
```

2021-06-06 21:44 UTC, unnamedd commented on commands/developer-utils/docker/clean-docker.sh
> +
You need to add the dependency information here and the check if docker is installed in the system or not. Check this [pull request ](https://github.com/raycast/script-commands/pull/459/files)to copy how it was added there.

2021-06-07 10:42 UTC, qeude commented
Hi @unnamedd,
Thanks for your feedback, changes have been commited 🙌

2021-06-12 17:29 UTC, unnamedd approved these changes
Looks good to me! It's approved ✅ 

We're ready to go @mattisssa

2021-06-12 17:30 UTC, merged