Added scripts that create and open blank Swift Playground project
raycast/script-commands pull request #465
Opened 2021-06-08 18:53 UTC by qeude

## Description

Scripts that use [playground cli](https://github.com/JohnSundell/Playground) to create and open new Playground project.
The first script opens a basic Playground.
The second one opens a view prototyping Playground.

## Type of change

- [x] New script command

## Screenshot

![basic](https://user-images.githubusercontent.com/19294297/121241169-6da5ca80-c89b-11eb-9583-5f42d434eab1.gif)

![view](https://user-images.githubusercontent.com/19294297/121241227-7f876d80-c89b-11eb-9f30-00e8d9232346.gif)

## Dependencies / Requirements

Requiring installing [playground cli](https://github.com/JohnSundell/Playground) before.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-06-12 18:20 UTC, unnamedd requested changes
Nice addition this pull request @qeude! 

However, I strongly suggest you to move it to a new folder, maybe called `swift-playground` or just `playground` inside of `apps` folder. As you have more than one Script Command, I do think it will fit better there, even though it's a developer utility.

2021-06-12 18:20 UTC, unnamedd commented on commands/developer-utils/open-new-playground.py
> +# @raycast.argument1 { "type": "text", "placeholder": "Destination Path (eg: ~/MyPlayground)", "optional": true }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Destination Path)", "optional": true }
```

2021-06-12 18:20 UTC, unnamedd commented on commands/developer-utils/open-new-playground.py
> +# @raycast.argument2 { "type": "text", "placeholder": "Gist, a GitHub URL or any other URL to open in Playground (eg: https://gist.github.com/JohnSundell/b7f901e8edb89d1396ede4d8db3e8c21)", "optional
Huge descriptions won't affect the width of the field and we should avoid them as much as we can.

```suggestion
# @raycast.argument2 { "type": "text", "placeholder": "GitHub/Gist URL", "optional": true }
```

2021-06-12 18:20 UTC, unnamedd commented on commands/developer-utils/open-new-playground.py
> +# @raycast.argument3 { "type": "text", "placeholder": "Add some dependencies to your playground (eg: ~/unbox/unbox.xcodeproj,~/files/files.xcodeproj) ", "optional": true }
As this placeholder looks something very important to have, I'd suggest you to right a small README containing some explanations about all of them. Check it out here: https://github.com/raycast/script-commands/tree/master/commands/apps/things

```suggestion
# @raycast.argument3 { "type": "text", "placeholder": "Dependencies", "optional": true }
```

2021-06-12 18:20 UTC, unnamedd commented on commands/developer-utils/open-new-playground.py
> +# @raycast.packageName Developer Utils
```suggestion
# @raycast.packageName Swift Playgrounds
```

2021-06-12 18:20 UTC, unnamedd commented on commands/developer-utils/open-new-playground.py
> +# @raycast.title Open new basic Playground
```suggestion
# @raycast.title Create Basic
```

2021-06-12 18:20 UTC, unnamedd commented on commands/developer-utils/open-new-view-playground.py
> +# @raycast.argument3 { "type": "text", "placeholder": "Add some dependencies to your playground (eg: ~/unbox/unbox.xcodeproj,~/files/files.xcodeproj) ", "optional": true }
The same explanation about huge placeholders I made above, applies here.

2021-06-12 18:20 UTC, unnamedd commented on commands/developer-utils/open-new-view-playground.py
> +# @raycast.packageName Developer Utils
```suggestion
# @raycast.packageName Swift Playgrounds
```

2021-06-12 18:20 UTC, unnamedd commented on commands/developer-utils/open-new-view-playground.py
> +# @raycast.title Open new view based Playground
```suggestion
# @raycast.title Create View Based
```

2021-06-13 09:22 UTC, qeude commented
@unnamedd Thanks for those feedbacks, I did make the changes 😄

2021-06-14 18:22 UTC, fe9lix commented
Hey @qeude! I think this got by mistake into the root folder in `commands` now. The idea was to move it into the apps folder, correct?

2021-06-14 18:27 UTC, qeude commented
@fe9lix My bad, thought the idea was to put the playground folder in the `commands`, I'll fix this

2021-06-14 18:32 UTC, fe9lix approved these changes

2021-06-14 18:32 UTC, merged