Added create gif from video script
raycast/script-commands pull request #470
Opened 2021-06-10 20:52 UTC by qeude

## Description

Converts a video file to a gif file using [gifski](https://github.com/ImageOptim/gifski), arguments are all optionals, first one is source file path, second on is destination file path, and last one is resulting gif fps number.
By default, it takes the last video file on Desktop. I've done that to easily convert screen videos.
## Type of change

- [x] New script command

## Screenshot

![generated_gif](https://user-images.githubusercontent.com/19294297/121595382-81d5fd00-ca3e-11eb-8de6-60f47d70997e.gif)

## Dependencies / Requirements

Needs [gifski](https://github.com/ImageOptim/gifski) to work.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-06-12 17:47 UTC, unnamedd requested changes

2021-06-12 17:47 UTC, unnamedd commented on commands/conversions/create-gif-from-video.py
> +# @raycast.argument1 { "type": "text", "placeholder": "Path to the source file (default: take the last screen recording on the Desktop)", "optional": true }
Avoid huge placeholders, they won't be visible anyway.
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Source File Path", "optional": true }
```

2021-06-12 17:47 UTC, unnamedd commented on commands/conversions/create-gif-from-video.py
> +# @raycast.argument2 { "type": "text", "placeholder": "FPS (between 1 and 60, default: 20)", "optional": true }
```suggestion
# @raycast.argument2 { "type": "text", "placeholder": "FPS (Default: 20)", "optional": true }
```

2021-06-12 17:47 UTC, unnamedd commented on commands/conversions/create-gif-from-video.py
> +# @raycast.argument3 { "type": "text", "placeholder": "Width (default 600)", "optional": true }
```suggestion
# @raycast.argument3 { "type": "text", "placeholder": "Width (Default: 600)", "optional": true }
```

2021-06-12 17:47 UTC, unnamedd commented on commands/conversions/create-gif-from-video.py
> +# @raycast.packageName Utilities
```suggestion
# @raycast.packageName Conversions
```

2021-06-12 17:47 UTC, unnamedd commented on commands/conversions/create-gif-from-video.py
> +from pathlib import Path
A small suggestion just to organize
```suggestion
import mimetypes
import os
import subprocess
import sys

from glob import glob
from pathlib import Path
from shutil import which
```

2021-06-14 17:45 UTC, fe9lix commented on commands/conversions/create-gif-from-video.py
> +    os.system(f"ffmpeg -y -loglevel panic -err_detect aggressive -fflags discardcorrupt -i '{from_file_path}' -c:v libx264 -preset slow -crf 18 -c:a copy '{mp4_file_path}'>/dev/null")
Please also check for ffmpeg in the dependency check above.

2021-06-14 19:15 UTC, fe9lix requested changes
Hey @qeude ! Just quickly ran the script here locally with an mp4 (screencapture recorded from CleanShot) and ended up in a situation where I got a success message, but the original mp4 file deleted and no gif actually created. I guess this needs some more error handling because it's obviously undesired that my original file was deleted when running into the error.
Not sure what the actual issue is with the gif not being created...

2021-06-15 07:07 UTC, qeude commented
Hi @fe9lix ! I've got an idea about why your file has been deleted, it's my bad, I'll figure it out when I'll have some free time.
About the error handling, I'll try to do something but when I did before for `gifski` I wasn't able to redirect output to `/dev/null` while keeping errors.

2021-06-15 07:26 UTC, fe9lix commented
Sounds good – I guess showing the error to the user and in that case leaving the original file in place would be an improvement. I'll leave the PR open for now and you can just continue working on it when you have some time.

2021-06-15 19:01 UTC, qeude commented
@fe9lix I made the fix about the deletion of the source file. Wasn't able to reproduce the not generated gif file. I would maybe need some help to handle error of commands nicely.

2021-06-16 13:51 UTC, fe9lix commented
Hey @qeude ! I ran the ffmpeg and gifski commands directly in the shell and I got an error on gifski complaining that it hasn't been compiled with "video support". So that seems something specific to me setup here. Nevertheless, I think the error should be handled and then shown to the user. Afaik, os.system doesn't allow you to capture the output of the standard streams, so you would need to use a different way of capturing the output of stderr in Python (Popen maybe). After capturing stderr, you can print it and exit with a non-zero code.

2021-06-27 12:46 UTC, qeude commented
Hey @fe9lix, was a bit tought to find time to look at it.
I did commit what I think should fix the handling of stderr, since I'm not able to reproduce your problem, could you maybe confirm that it's working pls ?

2021-07-02 07:58 UTC, fe9lix commented
Hey @qeude ! Thanks for your updates and sorry for the reviewing delay! I've just retested and see an error message now (video disabled...). I guess we can merge it now since it works for you and I seem to have a weird local setup here. If something else pops up in the future, you can just iterate on it and further improve it. Cheers!

2021-07-02 07:59 UTC, merged