Add genpasswd2 script
raycast/script-commands pull request #472
Opened 2021-06-11 13:02 UTC by everdrone

## Description

Generates password according to [Password Rules Validation Tool](https://developer.apple.com/password-rules) by Apple

Much like iOS Safari, it generates passwords like `cesblw-xrdgeb-Gjdpi1`.

This script is based on [genpasswd2](https://github.com/everdrone/genpasswd2)

It's bundled with both light and dark icons (from SF Symbols for better integration in the ecosystem)

## Type of change

- [x] New script command

## Screenshot

<img width="937" alt="Screen Shot 2021-06-11 at 14 57 52" src="https://user-images.githubusercontent.com/22671061/121689860-70840380-cac5-11eb-9036-8119cedb05d0.png">

## Dependencies / Requirements

python3

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-06-12 17:41 UTC, unnamedd requested changes
Hi @everdrone, check my comments and let us know what you think.

Thanks for your first contribution in our repository.

2021-06-12 17:41 UTC, unnamedd commented on commands/developer-utils/genpasswd.py
> +    #     sys.exit(1)
Are the lines above intended to be used? If not, I'd highly suggest to remove them.

2021-06-12 17:41 UTC, unnamedd commented on commands/developer-utils/genpasswd.py
> +
```suggestion
# @raycast.argument1 {"type": "text", "placeholder": "Password Length", "optional": true}
```

2021-06-12 17:41 UTC, unnamedd commented on commands/developer-utils/genpasswd.py
> +print(superset())
Would be nice if you make use of the metatag @raycast.argument and let the choice of the length to the user.
```suggestion
print(superset(sys.argv[1]))
```

2021-06-12 17:41 UTC, unnamedd commented on commands/developer-utils/genpasswd.py
> +import string
To make use of argument as suggested
```suggestion
import sys
import string
```

2021-06-13 15:26 UTC, everdrone commented
> Hi @everdrone, check my comments and let us know what you think.
> 
> Thanks for your first contribution in our repository.

Sure! Thanks for the tips!

But the password length is not exactly defined by one argument in my script. I'll need to make some more changes

### Long explanation:
The password length is defined by this equation: `set_length * length + (len(separator) * length - 1)`

The `length` parameter changes the number of sets (the alphanumeric strings between the separators)
The `set_length` defines the actual length of the substrings in between the separators

The default regexp of the password is `([\w\d]{6}-?){3}`, where `6` is  `set_length` and `3` is `length`

2021-06-14 18:09 UTC, fe9lix approved these changes

2021-06-14 18:09 UTC, merged