Add character count command
raycast/script-commands pull request #479
Opened 2021-06-17 14:52 UTC by ubuntudroid

## Description

Counts the characters of either the clipboard or the passed argument.

## Type of change

- [x] New script command

## Screenshot

![CleanShot 2021-06-17 at 16 41 00](https://user-images.githubusercontent.com/519867/122419172-079c0000-cf8b-11eb-997e-a9cb100791eb.gif)

## Dependencies / Requirements

Needs python 3.x and the [pasteboard library](https://github.com/tobywf/pasteboard).

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-06-17 14:56 UTC, ubuntudroid commented
Here is a gif that better shows the output of the script (the one in the PR description was trimmed to aggressively and I can't change it anymore:

![CleanShot 2021-06-17 at 16 53 11](https://user-images.githubusercontent.com/519867/122421864-fa801080-cf8c-11eb-9eb4-b0abecb63950.gif)

2021-06-17 15:05 UTC, unnamedd requested changes
Hey @ubuntudroid, thanks for submit your Script Command and welcome aboard. 🎉 

Just two small things to change to keep the conformance with the guideline.

2021-06-17 15:05 UTC, unnamedd commented on commands/developer-utils/count-characters.py
> +# @raycast.title Count characters
```suggestion
# @raycast.title Count Characters
```

2021-06-17 15:05 UTC, unnamedd commented on commands/developer-utils/count-characters.py
> +# @raycast.packageName Developer Utils
```suggestion
# @raycast.packageName Developer Utilities
```

2021-06-17 21:13 UTC, unnamedd approved these changes
Looks good to me! Thanks for the changes @ubuntudroid!

2021-06-18 16:55 UTC, fe9lix approved these changes

2021-06-18 16:55 UTC, merged

2021-06-21 16:26 UTC, jaklan commented
@ubuntudroid @unnamedd Dependency on a globally installed pip package is a **very bad** practice. Especially there's absolutely no need to use it, you can just go with plain Bash + Python script with no dependencies, exactly like here:
https://github.com/raycast/script-commands/blob/master/commands/conversions/strikethrough.sh

2021-06-21 16:30 UTC, unnamedd commented
@jaklan I didn't say anything about a global pip install, but the point here is the use of `pasteboard` which is clearly not part of the Python framework. Am I wrong?

2021-06-21 19:32 UTC, es183923 commented
something like the following could replace the script, and it doesn't have any dependencies.
```bash
#!/bin/bash
str=$(pbpaste)
echo ${#str}
```

2021-06-21 22:43 UTC, unnamedd commented
> something like the following could replace the script, and it doesn't have any dependencies.
> 
> ```shell
> #!/bin/bash
> str=$(pbpaste)
> echo ${#str}
> ```

For sure, then I’d like to ask one of you to bring this benefit to our community bringing this improvement updating the Script Command! cc @jaklan @es183923

2021-06-21 23:22 UTC, es183923 commented
Sure!