Add Bitwarden TOTP command
raycast/script-commands pull request #508
Opened 2021-07-13 18:38 UTC by int3rrupt

## Description

This new script command allows users to copy Bitwarden TOTP codes into their clipboard.

## Type of change

- [x] New script command
- [x] Documentation update

## Screenshot

## Dependencies / Requirements

## Checklist

- [ ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-07-13 19:59 UTC, PSalant726 requested changes
Thanks for the PR! I have just two very minor suggestions for code changes.

Separately, can you please add this script to the package's [`README.md` file](https://github.com/raycast/script-commands/blob/master/commands/password-managers/bitwarden/README.md) as a part of these changes? It probably belongs right after _Copy First Matching Password_.

2021-07-13 19:59 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +# @raycast.author Adrian Reyes
There's support for multiple authors by duplicating this line. Since this is mostly code from the _Copy First Matching Password_ script, I would appreciate a nod 😄 . This isn't a blocker for me.
```suggestion
# @raycast.author Adrian Reyes
# @raycast.author Phil Salant
```

2021-07-13 19:59 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +totp=$(eval "bw get totp $id $session" 2> /dev/null) || itemNoTotp "$name"
There's absolutely nothing functionally wrong with this, as far as I can tell, but the `bw list items` command will return the TOTP in it's result. If we copy it from there instead of the `id`, then we can make one less call to the CLI.
```suggestion
item=$(bw list items --search "$1" $session 2> /dev/null | jq ".[0] | { name: .name, totp: .login.totp }")
name=$(echo $item | jq --exit-status ".name") || notFound
totp=$(echo $item | jq --raw-output --exit-status ".totp") || notFound
```

2021-07-13 21:41 UTC, int3rrupt commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +totp=$(eval "bw get totp $id $session" 2> /dev/null) || itemNoTotp "$name"
The actual TOTP isn't provided in the JSON which is why we need `bw get totp`. What you get in the JSON is the TOTP key/secret that is used to generate the TOTP. I also don't see any option to include it in the JSON output. Have you seen it in the JSON? Am I missing something?

2021-07-13 23:24 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +totp=$(eval "bw get totp $id $session" 2> /dev/null) || itemNoTotp "$name"
Ah, yes that makes more sense than assuming the `bw list items` JSON output would change every 30 seconds 😂 . I haven't seen any other TOTP-related fields in the JSON, but it doesn't matter anyway because what you have should work just fine.

2021-07-13 23:25 UTC, PSalant726 requested changes
I don't have TOTP tokens in my personal Bitwarden vault, so if you've been able to test your code as-is, then it works for me (although I'm not sure you need [the `eval`](https://github.com/raycast/script-commands/pull/508/files#diff-ec14dee94b8d0225cbb35f7716146e488b29bcf4a5553b450f36c44354bea3f5R62)).

Separately, can you please add this script to the package's [`README.md` file](https://github.com/raycast/script-commands/blob/master/commands/password-managers/bitwarden/README.md) as a part of these changes? It probably belongs right after _Copy First Matching Password_.

2021-07-14 09:36 UTC, jaklan requested changes

2021-07-14 09:36 UTC, jaklan commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +itemNoTotp() {
To keep it consistent, I would rename it to "totpNotFound":

```suggestion
totpNotFound() {
```

2021-07-14 09:36 UTC, jaklan commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +  echo "Item '$1' does not have a TOTP configured."
```suggestion
  echo "The item '$1' does not have a TOTP configured."
```

2021-07-14 09:36 UTC, jaklan commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +totp=$(eval "bw get totp $id $session" 2> /dev/null) || itemNoTotp "$name"
As @PSalant726 mentioned, is there any reason to use eval here?

```suggestion
totp=$(bw get totp $id $session 2> /dev/null || totpNotFound "$name")
```

2021-07-14 15:28 UTC, int3rrupt commented
> I don't have TOTP tokens in my personal Bitwarden vault, so if you've been able to test your code as-is, then it works for me (although I'm not sure you need [the `eval`](https://github.com/raycast/script-commands/pull/508/files#diff-ec14dee94b8d0225cbb35f7716146e488b29bcf4a5553b450f36c44354bea3f5R62)).
> 
> Separately, can you please add this script to the package's [`README.md` file](https://github.com/raycast/script-commands/blob/master/commands/password-managers/bitwarden/README.md) as a part of these changes? It probably belongs right after _Copy First Matching Password_.

Originally I didn't have `eval` but I wasn't getting a token while running it through Raycast, however, executing the actual command in the terminal works. I'm not very familiar with bash scripting so it might be a simple fix.

This is what I had before:
```bash
totp=$(bw get totp $id $session 2> /dev/null) || itemNoTotp "$name"
```
I think the issue is due to the way I am referencing the variables. Once I wrap the command in a string and throw an `eval` in front, it works as expected. I too would prefer not having that `eval` in there, any suggestions?

2021-07-14 15:36 UTC, int3rrupt commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +totp=$(eval "bw get totp $id $session" 2> /dev/null) || itemNoTotp "$name"
See my response in the comment below. If we can get rid of it that would be great.

2021-07-14 16:46 UTC, PSalant726 commented
Since I can't test it locally, it's unclear what `bw get totp` command returns, but the fact that wrapping the call in a string seems to work implies that it's just returning the raw TOTP code. You can instead try wrapping the entire `$()` in a string, without `eval`, like:
```sh
totp="$(bw get totp $id $session 2> /dev/null) || itemNoTotp '$name')"
```

2021-07-16 17:31 UTC, int3rrupt commented
> Since I can't test it locally, it's unclear what `bw get totp` command returns, but the fact that wrapping the call in a string seems to work implies that it's just returning the raw TOTP code. You can instead try wrapping the entire `$()` in a string, without `eval`, like:
> 
> ```shell
> totp="$(bw get totp $id $session 2> /dev/null) || itemNoTotp '$name')"
> ```

This did not work. I also removed the extra parenthesis:
```bash
totp="$(bw get totp $id $session 2> /dev/null || itemNoTotp '$name')"
```
This did not work either. Other ideas?

2021-07-16 23:35 UTC, PSalant726 commented
Ah, sorry the typo was the last `)`, not the first one. So it should have been:
```sh
totp="$(bw get totp $id $session 2> /dev/null)" || itemNoTotp '$name'
```
This way, you'll place the return value of `bw get totp` into a string `||` the string returned by `itemNoTotp`. This is all just a guess. I'm not a bash expert either 😅

2021-07-16 23:55 UTC, int3rrupt commented
> Ah, sorry the typo was the last `)`, not the first one. So it should have been:
> 
> ```shell
> totp="$(bw get totp $id $session 2> /dev/null)" || itemNoTotp '$name'
> ```
> 
> This way, you'll place the return value of `bw get totp` into a string `||` the string returned by `itemNoTotp`. This is all just a guess. I'm not a bash expert either 😅

I believe this is close to what I was originally trying when I reached out on Slack. I did just try this though to confirm. It appears to work, because I don't the the error message, however, I also don't get a value in my clipboard.

2021-07-17 00:13 UTC, PSalant726 commented
Ok, I think it's because `""` isn't treated as "falsey" in Bash like it would be in JS, so you're just getting `""` on your clipboard. This pattern probably wont work for `bw get totp` like it does for `jq --exit-status`. You may need to try refactoring it to check the exit code of `bw get totp` after calling it, and printing the error message unless the exit code is 0. I've implemented something similar on L54 for `bw unlock `.

2021-07-17 05:06 UTC, int3rrupt commented
Ok, I'll check it out. Thanks.

2021-07-17 08:27 UTC, int3rrupt commented
`eval` has been removed. I just needed to add `-r` to the `jq` command in order to remove the quotes from the ID. Also added check for exit code.

2021-07-17 13:33 UTC, PSalant726 requested changes
Glad you got got this working! Thanks for sticking with it, and thanks for updating the `README.md` as well.

My only remaining comments are just some small stylistic improvements.

2021-07-17 13:33 UTC, PSalant726 commented on commands/password-managers/bitwarden/README.md
> +All authentication and vault-related commands in this package require the [Bitwarden CLI](https://bitwarden.com/help/article/cli/) v1.14.0 or later. Bitwarden Send-related commands require v1.15.1 or
Just a misplaced `,` character here.
```suggestion
All authentication and vault-related commands in this package require the [Bitwarden CLI](https://bitwarden.com/help/article/cli/) v1.14.0 or later. Bitwarden Send-related commands require v1.15.1 or later. The _Bitwarden Status_, _Search Vault Items_, _Copy First Matching Password_, _Copy First Matching TOTP_, and Bitwarden Send-related commands (except _Delete a Send_) also require the [`jq` utility](https://stedolan.github.io/jq/).
```

2021-07-17 13:33 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +id=$(echo $item | jq -r --exit-status ".id") || itemNotFound
Please use the long-form of `-r`. It's a hard-coded command, so it improves the maintainability if other contributors can get an idea of what it's doing without having to look at documentation.
```suggestion
id=$(echo $item | jq --raw-output --exit-status ".id") || itemNotFound
```

2021-07-17 13:33 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +status=$?
```suggestion
totp_status=$?
```

2021-07-17 13:33 UTC, PSalant726 commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +fi
We can flatten this a bit.
```suggestion
if [ $totp_status -ne 0 ]; then
  totpNotFound "$name"
  exit 1
fi

echo -n $totp | pbcopy
unset totp
echo "Copied the TOTP for '$name' to the clipboard."
exit 0
```

2021-07-17 20:50 UTC, int3rrupt commented
Suggestions applied.

2021-07-17 23:48 UTC, PSalant726 approved these changes
LGTM! Thanks again!

2021-07-19 09:46 UTC, jaklan commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +  exit 1
```suggestion
```
It's redundant here, because you are already exiting in `totpNotFound` function

2021-07-19 09:52 UTC, jaklan requested changes

2021-07-19 09:52 UTC, jaklan commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +  exit 1
In general, you can replace lines 63-68 with one-liner:
```
test $? -eq 0 || totpNotFound "$name"
```

2021-07-19 09:55 UTC, jaklan requested changes

2021-07-19 09:55 UTC, jaklan commented on commands/password-managers/bitwarden/copy-first-matching-totp.sh
> +fi
In general, you can replace lines 63-68 with one-liner:
```
test $? -eq 0 || totpNotFound "$name"
```

2021-07-19 13:35 UTC, int3rrupt commented
Suggestion applied and tested.

2021-07-20 23:16 UTC, jaklan approved these changes
Imho it's ready to merge, @mattisssa or anyone?

2021-07-21 10:12 UTC, mattisssa commented
@jaklan nice 👍

2021-07-21 10:12 UTC, merged