Add commands/developer-utils/search-script-command-marketplace
raycast/script-commands pull request #509
Opened 2021-07-14 04:19 UTC by Pondorasti

## Description

Created new utility script that searches for script commands in the Unofficial Marketplace, [scriptcommands.com](scriptcommands.com).

## Type of change

- [x] New script command

## Screenshot

https://user-images.githubusercontent.com/32957606/125560446-3d20b2ba-8716-42eb-ae0b-13859c132936.mov

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-07-14 04:20 UTC, Pondorasti commented
@unnamedd 🕵️‍♂️ 👀

2021-07-14 09:47 UTC, unnamedd requested changes
Hey @Pondorasti,

thanks for the website you've created for the Script Commands and also for this Script Command as well. It's funny to think that you will find this Script Command in your website to search for Script Commands... haha like chicken and egg problem, a paradox! :P

I've made some suggestion but the last one I need to do here: this Script Command will fit better in the web-searches folder instead of developer-utils.

Thanks one more time!

2021-07-14 09:47 UTC, unnamedd commented on commands/developer-utils/search-script-command-marketplace.sh
> +# @raycast.description Search for Script Commands in the Unofficial Marketplace, scriptcommands.com
```suggestion
# @raycast.description Search for Script Commands in the [Unofficial Raycast Script Commands Marketplace](https://scriptcommands.com).
```

2021-07-14 09:47 UTC, unnamedd commented on commands/developer-utils/search-script-command-marketplace.sh
> +# @raycast.packageName Marketplace Search
```suggestion
# @raycast.packageName Web Searches
```

2021-07-14 16:20 UTC, Pondorasti commented on commands/developer-utils/search-script-command-marketplace.sh
> +# @raycast.packageName Marketplace Search
Fixed, but wouldn't it make more sense to just use `Marketplace` as `packageName`?

2021-07-14 22:22 UTC, unnamedd commented on commands/developer-utils/search-script-command-marketplace.sh
> +# @raycast.packageName Marketplace Search
Following the standard already created, I'd say: no. If you check for example the Script Commands for some stores we have inside of the web-searches folder, they also have in the `packageName`: "Web Searches".

2021-07-14 22:23 UTC, unnamedd commented on commands/developer-utils/search-script-command-marketplace.sh
> +# @raycast.packageName Marketplace Search
Of course, unless we decide to give an upgrade on them and change the packageName for the Script Commands related to Marketplaces.

2021-07-15 00:53 UTC, Pondorasti commented on commands/developer-utils/search-script-command-marketplace.sh
> +# @raycast.packageName Marketplace Search
Yup, that makes sense. The beauty of it is that I can customize it however I like on my device, hehe.

2021-07-15 08:51 UTC, unnamedd approved these changes
Looks good to me!

2021-07-15 21:23 UTC, mattisssa approved these changes
Thanks for the PR! Looks good to me 👍

2021-07-15 21:23 UTC, merged