Add Obsidian search vault and create note templates
raycast/script-commands pull request #516
Opened 2021-07-18 13:53 UTC by HotThoughts

## Description

Add two templates for the Obsidian app
- search in a given vault, and
- create a new note in the given vault

## Type of change

- [X] New script command

## Screenshot

When creating a new note, `Name` of the note is required, while `Content` is optional.
![image](https://user-images.githubusercontent.com/26658608/126069622-bc8e381f-6892-4418-bca8-4b4861811abe.png)

This will start a search query in the given vault.
![image](https://user-images.githubusercontent.com/26658608/126069689-6bb2c481-e03e-461e-81d1-51c9a7abbe57.png)

## Dependencies / Requirements

Requires Obsidian `v0.8.15+` as this is the version that [URL scheme was first introduced](https://forum.obsidian.md/t/obsidian-release-v0-8-15/5697). 
You can Install Obsidian via: 
1. the offical website: https://obsidian.md
2. use HomeBrew: `brew install --cask obsidian`

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-07-19 12:38 UTC, grzegorzkrukowski commented
Thanks for your first contribution! 

In general, it all looks good, but I would like to suggest adding a check for `$VAULT_NAME` being empty in each of the scripts:

```
VAULT_NAME=""

if [ -z "$VAULT_NAME" ]
then
  echo "Configure VAULT_NAME"
  exit 1
fi
```

In case someone misses the fact he should do it directly in the script file - it's gonna give a bit nicer error handling than the current solution that is error shown directly by Obsidian

2021-07-19 12:39 UTC, grzegorzkrukowski requested changes
Thanks for your first contribution! 

In general, it all looks good, but I would like to suggest adding a check for `$VAULT_NAME` being empty in each of the scripts:

```
VAULT_NAME=""

if [ -z "$VAULT_NAME" ]
then
  echo "Configure VAULT_NAME"
  exit 1
fi
```

In case someone misses the fact he should do it directly in the script file - it's gonna give a bit nicer error handling than the current solution that is error shown directly by Obsidian

2021-07-19 20:08 UTC, HotThoughts commented
@grzegorzkrukowski Woohoo my first contribution  :tada: 

I added the suggested error handling. 😄

2021-07-20 11:52 UTC, grzegorzkrukowski approved these changes

2021-07-20 11:52 UTC, merged