Add stopwatch script command
raycast/script-commands pull request #517
Opened 2021-07-20 08:06 UTC by pomdtr

## Description

Add a stopwatch mechanism to raycast. You can start, stop and see progress of an active stopwatch

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

Not much to see.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-07-20 09:01 UTC, thomaspaulmann commented on commands/productivity/stopwatch/start.bash
> +    echo "A stopwatch already exists!" > /dev/stderr
Good one!

2021-07-20 11:50 UTC, grzegorzkrukowski requested changes

2021-07-20 11:50 UTC, grzegorzkrukowski commented on commands/productivity/stopwatch/stop.bash
> +PROGRESS=$(./progress.sh)
There is no `progress.sh` file included in this PR - should this be `.bash` instead here?

2021-07-20 11:51 UTC, grzegorzkrukowski commented
I would also suggest adding `stopwatch-` prefix to all filenames - some users will throw all scripts into one folder.

2021-07-20 12:25 UTC, pomdtr commented on commands/productivity/stopwatch/stop.bash
> +PROGRESS=$(./progress.sh)
Oups. I'll correct it

2021-07-20 17:59 UTC, pomdtr commented on commands/productivity/stopwatch/stop.bash
> +PROGRESS=$(./progress.sh)
Done in da945f7

2021-07-20 18:24 UTC, es183923 commented
I think putting the file in `/tmp/stopwatch/stopwatch.txt` or somewhere similar would be a better location for the stopwatch temporary file.

2021-07-20 22:00 UTC, pomdtr commented
I agree, I moved it to the system TMPDIR in 82d69ea.

Thanks for the feedback!

2021-07-20 23:26 UTC, jaklan commented
@pomdtr it's not as issue actually, but `.bash` suffix is pretty rare (even if it's explicitly `bash`, not `sh`, script), I would keep with the standard `.sh` as all other bash scripts in the repository.

2021-07-22 09:36 UTC, grzegorzkrukowski commented
@pomdtr why we ended up having both .sh and .bash in this PR ?

2021-07-22 09:37 UTC, grzegorzkrukowski requested changes
@pomdtr why we ended up having both .sh and .bash in this PR ? Let's remove duplicated files and leave .sh only

2021-07-22 20:51 UTC, grzegorzkrukowski approved these changes
Looks good now - thanks for the changes

2021-07-22 20:51 UTC, merged