New Note script
raycast/script-commands pull request #520
Opened 2021-07-22 03:51 UTC by commai

## Description

Simply allows you to create a new note with appropriate title and body formatting via Raycast

## Type of change
- [ ] New script command

## Screenshot

https://user-images.githubusercontent.com/46573539/126587604-fc52ea20-d7b6-4c00-8a04-e748937b0868.mov

## Dependencies / Requirements

Simply add it to your list of enabled commands 

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-07-22 06:53 UTC, unnamedd requested changes
Thanks for the Script Command @commai! Please, check my comments and let me know when finish to address them! 🤘

2021-07-22 06:53 UTC, unnamedd commented on commands/apps/notes/QuickNote.applescript
> +# @raycast.description Create a New Note quickly via Raycast
As the Script Commands are done to work primarily on Raycast, doesn't make much sense mention "via Raycast" in the title of the Script Command.

```suggestion
# @raycast.description Create a new Note quickly 
```

2021-07-22 06:53 UTC, unnamedd commented on commands/apps/notes/QuickNote.applescript
> +# @raycast.title Quick Notes
```suggestion
# @raycast.title Create Note
```

2021-07-22 06:53 UTC, unnamedd commented on commands/apps/notes/QuickNote.applescript
> +
One of our requirements for the submission of Script Commands to this repository is the use of the meta tag `packageName` to improve portability. You can check some of our conventions [here](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#metadata-convention).

```suggestion
# @raycast.package Notes

```

2021-07-22 06:53 UTC, unnamedd commented on commands/apps/notes/QuickNote.applescript
> +	</body>"
Really interesting! I didn't know under the hood Notes used HTML! Thanks for the TIL!

2021-07-23 00:55 UTC, commai commented
@unnamedd Just finished making the fixes! Thanks for reviewing :)

2021-07-23 09:00 UTC, grzegorzkrukowski requested changes
Thanks for your contribution.

It all looks good, but one small thing is to follow up [File naming convention](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#file-naming-convention) - please use dashed, lower-case naming for the file.

2021-07-23 20:55 UTC, unnamedd commented
> Thanks for your contribution.
> 
> It all looks good, but one small thing is to follow up [File naming convention](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#file-naming-convention) - please use dashed, lower-case naming for the file.

Excellent point @grzegorzkrukowski!

2021-07-23 20:56 UTC, unnamedd commented on commands/apps/notes/create-note.applescript
> +# @raycast.package Notes
```suggestion
# @raycast.packageName Notes
```

2021-07-23 20:56 UTC, unnamedd requested changes
@commai just missing a last point and then we will be good to go!

2021-07-26 10:13 UTC, RSO approved these changes

2021-07-26 10:13 UTC, merged

2021-07-26 10:14 UTC, RSO commented
Thank you for your contribution!