Add ability to launch kit scripts from raycast
raycast/script-commands pull request #521
Opened 2021-07-23 11:56 UTC by pomdtr

## Description

This script allows to launch kit scripts directly from raycast.

## Type of change

- [ ] New script command

## Screenshot

https://user-images.githubusercontent.com/17577332/126778347-38401e92-368f-4d12-af8d-6b8c14ac2b34.mp4

## Dependencies / Requirements

Kit needs to be installed: https://www.scriptkit.com/

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-07-26 10:22 UTC, RSO commented
Small suggestion to change the template shebang (I couldn't find `/usr/bin/env sh` being used in this repository). Other than that this looks good to me. 

It's a bit unfortunate that you have to run the regenerate command manually, I expect that our upcoming Extension API might make it easier and smoother to integrate kit scripts with Raycast 🤞 .

2021-07-26 14:00 UTC, unnamedd requested changes
Nice Script Command @pomdtr! 

I've made some comments, check them out and let me know if you have any questions.

2021-07-26 15:06 UTC, pomdtr commented on commands/apps/kit/template.txt
> +# @raycast.mode silent
The raycast script command is supposed to launch the interactive Script Kit launcher, so we don't need any output from raycast.

2021-07-26 15:11 UTC, pomdtr commented on commands/apps/kit/template.txt
> +# @raycast.author $author
This was implicit because these fields where coming from the json file. I change theses mapping to be explicits.

2021-07-26 15:19 UTC, pomdtr commented on commands/apps/kit/import-kit-scripts.py
> +# @raycast.packageName Kit
> Small suggestion to change the template shebang (I couldn't find `/usr/bin/env sh` being used in this repository). Other than that this looks good to me.
> 
> It's a bit unfortunate that you have to run the regenerate command manually, I expect that our upcoming Extension API might make it easier and smoother to integrate kit scripts with Raycast 🤞 .

I hope so :)

Don't hesitate to take a look at the extension api built by @johnlindquist, I think he found a nice balance between a lot of available features and a good developper experience.
It is so much nicer than alfred for building quick scripts.

Here is the code for the vscode quick launcher I've shown in the script.

```json
// Menu: Open Recent in VSCode
// Shortcode: code

const vscodeStorage = `${kit.home()}/Library/Application Support/Code/storage.json`;
const json = JSON.parse(await kit.readFile(vscodeStorage));

const recentEntries = json.openedPathsList.entries
const uri = await kit.arg("Choose Path to Open", recentEntries.map(entry => entry.folderUri || entry.fileUri).map(uri => {
    const uri_components = uri.split("/")
    const path = uri.replace("file://", "")
    return { value: uri, name: uri_components[uri_components.length-1], description: path }
}))

kit.exec(`open -a "Visual Studio Code" '${uri}'`)

```

2021-07-26 15:19 UTC, pomdtr commented
> Small suggestion to change the template shebang (I couldn't find `/usr/bin/env sh` being used in this repository). Other than that this looks good to me.
> 
> It's a bit unfortunate that you have to run the regenerate command manually, I expect that our upcoming Extension API might make it easier and smoother to integrate kit scripts with Raycast 🤞 .

I hope so :)

Don't hesitate to take a look at the extension api built by @johnlindquist, I think he found a nice balance between a lot of available features and a good developper experience.
It is so much nicer than alfred for building quick scripts.

Here is the code for the vscode quick launcher I've shown in the script.

```json
// Menu: Open Recent in VSCode
// Shortcode: code

const vscodeStorage = `${kit.home()}/Library/Application Support/Code/storage.json`;
const json = JSON.parse(await kit.readFile(vscodeStorage));

const recentEntries = json.openedPathsList.entries
const uri = await kit.arg("Choose Path to Open", recentEntries.map(entry => entry.folderUri || entry.fileUri).map(uri => {
    const uri_components = uri.split("/")
    const path = uri.replace("file://", "")
    return { value: uri, name: uri_components[uri_components.length-1], description: path }
}))

kit.exec(`open -a "Visual Studio Code" '${uri}'`)

```

2021-07-26 15:21 UTC, unnamedd commented on commands/apps/kit/template.txt
> +# @raycast.author $author
Ahh okay, make them explicit would avoid this kind of confusion I had for future readers!

2021-07-26 15:21 UTC, unnamedd commented on commands/apps/kit/template.txt
> +# @raycast.mode silent
Nice, thanks for the explanation! ;)

2021-07-26 15:23 UTC, pomdtr commented on commands/apps/kit/template.txt
> +# @raycast.author $author
Yep, this was done in a7ba0bd

2021-07-26 15:27 UTC, unnamedd requested changes
@pomdtr thanks for address my comments, however I have one last: let's rename the folder to `script-kit` to keep the conformance with the `packageName`.

2021-07-26 15:39 UTC, pomdtr commented
Done! I also updated the title of the import script to be coherent with all the other changes :)

Thanks for the review!

2021-07-26 15:42 UTC, unnamedd approved these changes
Looks good to me! 
Thanks for the changes @pomdtr!

2021-07-27 07:30 UTC, merged

2021-07-27 07:30 UTC, RSO commented
Thanks again for the contribution and collaboration!