feat(brew): Add brew leaves command
raycast/script-commands pull request #523
Opened 2021-07-26 11:28 UTC by Owpac

## Description

New script command for brew: `brew leaves`
List installed formulae that are not dependencies of another installed formula.

## Type of change

- [ ] New script command

## Screenshot

Like brew list command

## Checklist

- [ ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

(Sorry I edited commands/README file)

2021-07-26 13:42 UTC, unnamedd requested changes
Hi @Owpac, 
just one small comment regarding the README.md, please address it and let us know when you finish.

Thanks for your first contribution!

2021-07-26 13:42 UTC, unnamedd commented on commands/README.md
> +to brainstorm ideas with like-minded folks.
Please, revert the changes done in this file, it is auto-generated and all your changes here will be lost.

2021-07-26 13:53 UTC, Owpac commented on commands/README.md
> +to brainstorm ideas with like-minded folks.
It should be good, sorry for this mistake !

2021-07-26 14:02 UTC, unnamedd commented on commands/README.md
> +to brainstorm ideas with like-minded folks.
Would you mind to revert this line as well? 
Thanks a lot and sorry for all these requests!

2021-07-27 05:28 UTC, Owpac commented on commands/README.md
> +to brainstorm ideas with like-minded folks.
Done :)

2021-07-27 07:05 UTC, unnamedd approved these changes
Looks good to me! 
Thanks for your changes @Owpac!

2021-07-27 07:31 UTC, merged

2021-07-27 07:31 UTC, RSO commented
Thank you for your contribution!

2021-07-27 07:50 UTC, Owpac commented
@unnamedd I noticed a mistake in @raycast.description: "Show Brew List" --> "Show Brew Leaves"
Should I submit a new PR or I let you commit this update?

Sorry for the inconvenience!

2021-07-27 07:51 UTC, RSO commented
I'll make the change, no worries!

2021-07-27 07:54 UTC, RSO commented
2c74d4ee83bb00fe415cc73e0a65f9d922a4682c I took the description from `brew -h leaves`.

2021-07-27 07:56 UTC, Owpac commented
Thanks! :)

2021-07-27 08:20 UTC, unnamedd commented
> I'll make the change, no worries!

Nice! Thanks for the fix Remon!