Improve default browser front most app
raycast/script-commands pull request #529
Opened 2021-08-01 00:14 UTC by 186dk

## Description

## Type of change

- [ ] New script command
- [ ] Bug fix
- [x] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

## Dependencies / Requirements

## Checklist

- [ ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-08-03 11:28 UTC, unnamedd requested changes
Hi @186dk, 

even if I reviewed your changes for the file `commands/developer-utils/git/git-standup.sh`, could you please split this PR in two? That file changes are not related to the title of this PR where you are doing improvements in the file `commands/system/default-browser-front-most-app.applescript`.

Please, address the comments I made and let me know for a second round.

2021-08-03 11:28 UTC, unnamedd commented on commands/developer-utils/git/git-standup.sh
> +# @raycast.argument1 { "type": "text", "placeholder": "Project path"}
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Project Path"}
```

2021-08-03 11:28 UTC, unnamedd commented on commands/developer-utils/git/git-standup.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "Since (optional; eg. 1 week)", "optional": true }
```suggestion
# @raycast.argument2 { "type": "text", "placeholder": "Since (e.g: 1 week)", "optional": true }
```

2021-08-03 11:28 UTC, unnamedd commented on commands/system/default-browser-front-most-app.applescript
> +# @raycast.argument1 { "type": "text", "placeholder": "Browser Name (chrome, dev, safari)", "optional": true }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Browser (chrome, safari)", "optional": true }
```

2021-08-03 11:28 UTC, unnamedd commented on commands/system/default-browser-front-most-app.applescript
> +on run {rayCastAgrv}
The "C" in the Raycast name is lowercased.

```suggestion
on run {raycastArgv}
```

2021-08-03 11:28 UTC, unnamedd commented on commands/system/default-browser-front-most-app.applescript
> +if (rayCastAgrv is equal to "") then
```suggestion
if (raycastArgv is equal to "") then
```

2021-08-03 11:28 UTC, unnamedd commented on commands/system/default-browser-front-most-app.applescript
> +# rayCastAgrv is raycast argument
```suggestion
# raycastArgv is Raycast argument
```

2021-08-03 11:28 UTC, unnamedd commented on commands/system/default-browser-front-most-app.applescript
> +# display dialog ("Set defaut browser is " & rayCastAgrv & "!")
```suggestion
  # appName is used for print log message
  if (raycastArgv is equal to "dev")
    set appName to "Chrome dev"
  else
     set appName to raycastArgv
  end if
  set browserName to raycastArgv
end if  

# display dialog ("Set defaut browser is " & raycastArgv & "!")
```

2021-08-03 13:26 UTC, 186dk commented on commands/system/default-browser-front-most-app.applescript
> +# @raycast.argument1 { "type": "text", "placeholder": "Browser Name (chrome, dev, safari)", "optional": true }
Browser "dev" is developer version of Google Chrome, so please keep "dev" in the placeholder.

2021-08-03 14:55 UTC, unnamedd approved these changes
Looks good to me! Thanks for the updates @186dk!

2021-08-06 17:23 UTC, fe9lix approved these changes

2021-08-06 17:23 UTC, merged