Add "Create Trello card" script command
raycast/script-commands pull request #542
Opened 2021-08-11 11:30 UTC by mikefrancis

## Description

Creates a new script command which adds cards to a Trello board

## Type of change

- [x] New script command

## Screenshot

![Screenshot 2021-08-11 at 12 21 10 pm](https://user-images.githubusercontent.com/1672610/129020434-56f79746-7e09-44cc-a428-003e9e398d9c.png)

## Dependencies / Requirements

* Python 3.x
  * `sys`, `requests`, `dateparser` Python libraries
* Trello account
  * API key
  * API token
  * List ID

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-08-11 12:17 UTC, unnamedd requested changes
Hello @mikefrancis,

Nice to have your first contribution in our repository. I've made some comments in order to make your Script Command conform to our guidelines.

As soon you address the comments, please let me know for a second review.

Great to have you onboard!

2021-08-11 12:17 UTC, unnamedd commented on commands/apps/trello/create-trello-card.py
> +# To find the Board ID, head to https://api.trello.com/1/members/me/boards?key={TRELLO_KEY}&token={TRELLO_TOKEN}
```suggestion
# To find the Board ID, head to https://api.trello.com/1/members/me/boards?key={TRELLO_KEY}&token={TRELLO_TOKEN}
TRELLO_TOKEN = ''
```

2021-08-11 12:17 UTC, unnamedd commented on commands/apps/trello/create-trello-card.py
> +# To generate an API key/token, head to https://trello.com/app-key
As the user will need an extra configuration to make use of your Script Command, you need to add `.template` in the name of the file, i.e: `create-trello-card.template.py`.

https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-additional-modification

2021-08-11 12:17 UTC, unnamedd commented on commands/apps/trello/create-trello-card.py
> +
It is a nice thing if you add some early returns here to avoid the use of the Script Command in case of empty key, token and list id.

2021-08-11 12:17 UTC, unnamedd commented on commands/apps/trello/create-trello-card.py
> +# @raycast.title Create card
```suggestion
# @raycast.title Create Card
```

2021-08-11 12:58 UTC, mikefrancis commented on commands/apps/trello/create-trello-card.py
> +# To find the Board ID, head to https://api.trello.com/1/members/me/boards?key={TRELLO_KEY}&token={TRELLO_TOKEN}
I can appreciate this looks a bit strange as it's 2 comments together, but they both pertaiin to `TRELLO_LIST_ID` so ideally should be together

2021-08-11 13:06 UTC, mikefrancis commented
@unnamedd I definitely did not read the contribution guidelines, my apologies and thanks so much for your review.

I've pulled down the repo, made the changes and tidied up the Git history as it was mainly done through the UI.

2021-08-11 13:10 UTC, unnamedd commented
@mikefrancis would be great if everyone reads it because would make even easier for the community (me and others) to review the Script Commands, but if you didn't read, worry nothing, we will help you out anyway. It's a pleasure for this community here to have the support of the developers to bring new ideas to make Raycast even better to every one.

2021-08-11 13:19 UTC, unnamedd requested changes

2021-08-11 13:19 UTC, unnamedd commented on commands/apps/trello/create-trello-card.template.py
> +# Install them with `pip install {library}`
If I'm not wrong, `sys` and `dateparser` is part of Python, right? In that case, the only library which is needed to make it work is `requests` then, `pip install requests` should be enough. Please, correct me if I'm wrong.

```suggestion
# Install them with `pip install requests`
```

2021-08-11 13:19 UTC, unnamedd commented on commands/apps/trello/create-trello-card.template.py
> +# To find the Board ID, head to https://api.trello.com/1/members/me/boards?key={TRELLO_KEY}&token={TRELLO_TOKEN}
Let's move the comment above the variable, the keep your standard

```suggestion
# To find the Board ID, head to https://api.trello.com/1/members/me/boards?key={TRELLO_KEY}&token={TRELLO_TOKEN}
TRELLO_TOKEN = ''
```

2021-08-11 13:19 UTC, unnamedd commented on commands/apps/trello/create-trello-card.template.py
> +  exit(1)
Let's separate the conditions in three to make easier to explain the user if something is missing:

```suggestion
if TRELLO_KEY == '':
  print('Command not configured correctly. Missing variable: TRELLO_KEY')
  exit(1)

if TRELLO_TOKEN == '':
  print('Command not configured correctly. Missing variable: TRELLO_TOKEN')
  exit(1)

if TRELLO_LIST_ID == '':
  print('Command not configured correctly. Missing variable: TRELLO_LIST_ID')
  exit(1)
```

2021-08-11 13:25 UTC, mikefrancis commented on commands/apps/trello/create-trello-card.template.py
> +# To find the Board ID, head to https://api.trello.com/1/members/me/boards?key={TRELLO_KEY}&token={TRELLO_TOKEN}
Sorry - not sure I understand what you're asking here. A key and token are generated at the same time, this is why they sit under:

```# To generate an API key/token, head to https://trello.com/app-key```

Finding the Board ID is necessary to then find the List ID, which is why these are grouped together.

2021-08-11 13:28 UTC, unnamedd commented on commands/apps/trello/create-trello-card.template.py
> +# To find the Board ID, head to https://api.trello.com/1/members/me/boards?key={TRELLO_KEY}&token={TRELLO_TOKEN}
I just changed the position of the comment and the variable:

Before was:
```
variable = ''
# Comment
```
now is:

```
# Comment
variable = ''
```

this is just to keep organized.

2021-08-11 13:28 UTC, unnamedd commented on commands/apps/trello/create-trello-card.template.py
> +# Install them with `pip install {library}`
Okay, I was not sure if `dateparser` was part of Python or not! Thanks! ;)

2021-08-11 13:33 UTC, mikefrancis commented on commands/apps/trello/create-trello-card.template.py
> +# To find the Board ID, head to https://api.trello.com/1/members/me/boards?key={TRELLO_KEY}&token={TRELLO_TOKEN}
I understand what you mean, I think my point still stands though; Line 27 explains how to get the data needed for Line 28 and 29.

Lines 30 and 31 explain how to get the data needed for line 32.

If I accept your suggestion, the instructions no longer make any sense and it now looks like you retrieve `TRELLO_TOKEN` from the instructions to find the board ID, which is not true.

I really hope this makes sense as I'm not sure how to better explain this, perhaps I can take a screenshot and annotate.

2021-08-11 13:35 UTC, mikefrancis commented on commands/apps/trello/create-trello-card.template.py
> +# To find the Board ID, head to https://api.trello.com/1/members/me/boards?key={TRELLO_KEY}&token={TRELLO_TOKEN}
![Screenshot 2021-08-11 at 2 33 31 pm](https://user-images.githubusercontent.com/1672610/129038608-f56a0563-0500-4f93-ae8a-35cd94e180cb.png)

2021-08-11 13:45 UTC, unnamedd commented on commands/apps/trello/create-trello-card.template.py
> +# To find the Board ID, head to https://api.trello.com/1/members/me/boards?key={TRELLO_KEY}&token={TRELLO_TOKEN}
Ahhh okay, got it now your intention! The problem for me was read the first comment and see the TOKEN in the end of the line. Makes completely sense your point here! Thanks to make it clear for me and sorry to waste your time explaining via screenshot! haha

2021-08-11 13:47 UTC, unnamedd commented
@mikefrancis to finish and to make your first Script Command even better, what do you think to embed in this PR the Trello’s logo? Would be great to have it logo instead of the robot emoji. You can check the other apps on how to do. ;)

2021-08-11 14:13 UTC, mikefrancis commented
@unnamedd Good call, added 👍

2021-08-11 14:16 UTC, unnamedd approved these changes
@mikefrancis thanks a lot to address all the comments I brought here! You’re Script Command now looks amazing!

Thanks again for your first contribution and please, keep ‘em coming!

2021-08-11 14:21 UTC, mikefrancis commented
@unnamedd No problem, thanks for building such an awesome tool and for the review.

I've updated the screenshot to a GIF if you'd like to see it in action.

2021-08-11 14:25 UTC, unnamedd commented
Thanks a lot for your kind words regarding the review, but I’d like to kindly ask you to submit also your kind words to those who deserve them a lot: the developers. On Raycast, search for “Send Feedback” and send them message saying how much you like the project, I’m pretty sure they will like a lot or maybe, join us in our Slack Community: https://raycast.com/community

Will be a pleasure to have you there with the rest of the community.

2021-08-12 07:49 UTC, dehesa commented
Good stuff @mikefrancis! and thanks, as always, for the outstanding review @unnamedd!

2021-08-12 07:49 UTC, merged