Fixed Script Documentation
raycast/script-commands pull request #556
Opened 2021-08-20 05:12 UTC by KABILAN235

## Description

Made Changes to Documentation on Request of @unnamedd .

## Type of change

- [x ] Documentation update
- [x] Changed Script to A Template

## Checklist

- [x ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-08-20 11:39 UTC, unnamedd requested changes
The only thing missing now is:
You need to apply these changes in the file previously created, here you created another file.

Now, we have two files: `flutter-create.sh` and `flutter-create.template.sh` and we must have only one.

Thanks a lot for your new PR, @KABILAN235. Let me know when you finish for a second round of review.

2021-08-20 11:39 UTC, unnamedd commented on commands/developer-utils/flutter-create.template.sh
> +SDK_PATH="/Users/$USER/DevTools/flutter/bin"
I guess in this case, you should keep the instructions in the comments to help the user, but the string must be empty. This is the path for your flutter/bin, other users may have a different path to work.

2021-08-20 11:39 UTC, unnamedd commented on commands/developer-utils/flutter-create.template.sh
> +WORKSPACE_PATH="/Users/$USER/FlutterProjects"
I guess I can bring the same point I mentioned in the previous comment here. What do you think?

2021-08-22 05:38 UTC, KABILAN235 commented on commands/developer-utils/flutter-create.template.sh
> +SDK_PATH="/Users/$USER/DevTools/flutter/bin"
I Just Kept that String Occupied, just to give an idea of how the Path may be, Some People Often get Confused when they hear Flutter SDK Path.

2021-08-22 05:38 UTC, KABILAN235 commented on commands/developer-utils/flutter-create.template.sh
> +WORKSPACE_PATH="/Users/$USER/FlutterProjects"
Yeah, I Can Remove that One

2021-08-22 05:42 UTC, KABILAN235 commented
@unnamedd, I Just Renamed the flutter-create.sh file to flutter-create.template.sh file. I Don't See Another flutter-create.sh file to delete it. Could You Please Help Me?

2021-08-22 20:19 UTC, unnamedd commented on commands/developer-utils/flutter-create.template.sh
> +SDK_PATH="/Users/$USER/DevTools/flutter/bin"
You can move it to a documented line, which is going to show your example, instead of give your path. I’m saying that, because it may bring confusion if the user are not really confident on how to configure the Script Command, we need to think on beginners trying to learn Flutter, using Raycast and your Script Command.

2021-08-22 20:22 UTC, unnamedd commented
> @unnamedd, I Just Renamed the flutter-create.sh file to flutter-create.template.sh file. I Don't See Another flutter-create.sh file to delete it. Could You Please Help Me?

Currently, we have this file here: https://github.com/raycast/script-commands/blob/master/commands/developer-utils/flutter-create.sh

It was created in your first pull request. Now, you’ve just created another file (containing .template) and added here, if this PR get merged, then we will have two different files with almost the same content and we should avoid that.

To see the file in your machine, you need to pull the master branch from this repository, possibly you are not seeing the file because you do not have the latest update from here.

2021-09-01 13:04 UTC, RSO requested changes
See @unnamedd 's comments

2021-09-21 14:25 UTC, unnamedd commented
@fe9lix I'm still waiting for the changes to be done to do a second round of review, however, due to the lack of interesting I only see three ways for us to follow: 
1 - Remove the Script Command (I don't like that).
2 - Do the changes ourselves.
3 - Ignore completely my requests and move on.

2021-09-21 14:33 UTC, fe9lix commented
@unnamedd i would suggest to leave it open for one more week and then if there's no further activity, close the pr again.

2021-09-21 14:35 UTC, unnamedd commented
Sounds good to me @fe9lix!

2021-09-21 15:02 UTC, KABILAN235 commented
Hey @fe9lix , Sorry, it was not a Lack of Interest on this PR, I Just Have No Idea on How to Actually Remove A File, I'm Relatively New to all this GitHub and Stuff, and it was Pretty Overwhelming. Just Saw how to make a PR in Youtube Before Actually Opening this PR. Anyone Helping?

2021-09-21 17:26 UTC, fe9lix commented
@KABILAN235 no worries...@unnamedd could you assist with the needed changes?

2021-09-21 17:28 UTC, unnamedd commented
Welcome back @KABILAN235! 

Yes, sure @fe9lix!

2021-09-22 11:22 UTC, unnamedd commented
@KABILAN235 are you on our slack? If yes, please send me a message there!

2021-10-06 08:39 UTC, nhojb commented
@unnamedd @KABILAN235 has this PR been resolved yet?

2021-10-06 08:41 UTC, unnamedd commented
> @unnamedd @KABILAN235 has this PR been resolved yet?

Yeah @nhojb, it wasn't finished yet, but in this case the fault is mine, I didn't have much time to help @KABILAN235. Please, keep it open and I will try to finish everything with him still this week! ;)

2021-11-17 16:45 UTC, unnamedd commented
I've tried to contact the member on Slack, but unfortunately I didn't have success. I decided to close this issue to maybe in the future re-open or submit another PR containing the changes requested in this PR.

2021-11-17 16:45 UTC, closed without merging

2021-11-17 20:34 UTC, nhojb commented
Thanks for following this up @unnamedd 👍