add script append-note-from-clipboard
raycast/script-commands pull request #561
Opened 2021-08-20 21:52 UTC by ayoub-g

## Description

This script accepts an existent note name, appends to it the content of the clipboard

## Type of change
- [x] New script command

## Screenshot

https://user-images.githubusercontent.com/841163/130296709-e0fd8a02-4910-413c-87a1-38a549247cb6.mov

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-08-21 13:43 UTC, unnamedd requested changes

2021-08-21 13:43 UTC, unnamedd commented on commands/apps/notes/append-note-from-clipboard.applescript
> +# @raycast.description this script accepts an existent note name, appends to it the content of the clipboard
What do you think?
```suggestion
# @raycast.description Script to append to an existing note content from clipboard.
```

2021-08-21 13:43 UTC, unnamedd commented on commands/apps/notes/append-note-from-clipboard.applescript
> +# @raycast.title Append Note From Clipboard
```suggestion
# @raycast.title Append Content From Clipboard
```

2021-08-21 19:22 UTC, ayoub-g commented on commands/apps/notes/append-note-from-clipboard.applescript
> +# @raycast.title Append Note From Clipboard
Yes it's accurate

2021-08-21 19:28 UTC, ayoub-g commented on commands/apps/notes/append-note-from-clipboard.applescript
> +# @raycast.description this script accepts an existent note name, appends to it the content of the clipboard
Yes, it's accurate, thank you @unnamedd

2021-08-23 10:14 UTC, unnamedd approved these changes
Looks good to me! 🎉 

Thanks for your contribution @ayoub-g!

2021-08-23 10:41 UTC, mattisssa commented
Wow, this is nice! 👍

2021-08-23 10:41 UTC, merged