Add Script Command for iconsur
raycast/script-commands pull request #569
Opened 2021-08-27 07:26 UTC by StevenRCE0

## Description

Generate adaptive application icons for Big Sur and the future. Password is required to change the apps from App Store. Iconsur automatically search the App Store for iOS version of the icon. To force generate from local icons, place "y" in the third option. 
Learn more about [iconsur](https://github.com/rikumi/iconsur)

## Type of change

- [x] New script command

## Screenshot

<img width="776" alt="截圖 2021-08-27 15 14 52" src="https://user-images.githubusercontent.com/40051361/131088564-7f106752-b239-4b4b-92cb-786e332f992b.png">

## Dependencies

[iconsur](https://github.com/rikumi/iconsur)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-08-30 14:32 UTC, unnamedd requested changes
Hey @StevenRCE0, 

take a look in my comments, nothing really special but I guess they deserve a read.

2021-08-30 14:32 UTC, unnamedd commented on commands/apps/iconsur/iconsur.sh
> +# @raycast.description Change App Icons to Match Big Sur
```suggestion
# @raycast.description Change App icons to match Big Sur
```

2021-08-30 14:32 UTC, unnamedd commented on commands/apps/iconsur/iconsur.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "Password (store apps)", "secure": true, "optional": true }
Given the explanation in the placeholder, it looks you might be expecting the App Store user's password, however, in the code you are using it only for local purposes. 

Would you mind to give a quick explanation about the real need of password request here?

2021-08-30 14:32 UTC, unnamedd commented on commands/apps/iconsur/iconsur.sh
> +    echo "pwding"
What's the need of this echo here? It will be shadowed by the next one (or the incorrect password or the icon changed successfully).

2021-08-30 15:25 UTC, StevenRCE0 commented on commands/apps/iconsur/iconsur.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "Password (store apps)", "secure": true, "optional": true }
Didn't make it clear, it's the user's root password, elevation is required to change those apps from App Store.

2021-08-30 15:26 UTC, StevenRCE0 commented on commands/apps/iconsur/iconsur.sh
> +    echo "pwding"
It's for debug purpose, I'll remove that.

2021-08-30 15:42 UTC, unnamedd commented on commands/apps/iconsur/iconsur.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "Password (store apps)", "secure": true, "optional": true }
Then I guess we can change for something like "User's Root Password", "User Local Password", something on this way...

PS: your Pull Request is marked as "Draft", to have it ready to be merged, you will have to change from Draft to (I guess) Open.

2021-08-31 07:50 UTC, unnamedd approved these changes
Looks good to me!
I guess I didn't forget anything to ask you, @StevenRCE0! haha

Thanks for your contribution!

2021-08-31 08:52 UTC, merged

2021-08-31 08:52 UTC, RSO commented
Thank you for the contribution!