time calculation
raycast/script-commands pull request #571
Opened 2021-08-30 10:23 UTC by Mitra98t

## Description

### time-between-dates

Given two dates (the first is optional, the default value is today) the script returns the time between them in different unit of measure.

The result will be in milliseconds, hours, days and years.

### time-calculator

Given a date (optional, the default value is today) the script allows you to add or subtract an amount of time specifying the unit of measure choosing from Seconds, Minutes, Hours, Days, Weeks, Years.

The result will be the resulting date and time as well as the unix time.

## Type of change

- [x] New script command

## Screenshot

### time-between-dates

![TimeBetweenDates](https://user-images.githubusercontent.com/51447075/131324674-4c129d7f-633f-43b3-a950-7fbfe6bbe315.gif)

### time-calculator

![TimeCalculator](https://user-images.githubusercontent.com/51447075/131324698-b426bbdb-3c44-45a0-8e89-875095814617.gif)

## Dependencies / Requirements

Install Nodejs

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-08-30 14:15 UTC, unnamedd requested changes
Hello @Mitra98t, 
Nice to have your first pull request in our repository!

Please, take a look into my comments and let me know when you finish to address them!

Welcome aboard!

2021-08-30 14:15 UTC, unnamedd commented on commands/developer-utils/time-between-dates.js
> +// @raycast.packageName Developer Utils
```suggestion
// @raycast.packageName Developer Utilities
```

2021-08-30 14:15 UTC, unnamedd commented on commands/developer-utils/time-calculator.js
> +// @raycast.argument3 { "type": "text", "placeholder": "s, m, h, d, w, y DEFAULT: h", "optional":true}
```suggestion
// @raycast.argument3 { "type": "text", "placeholder": "s, m, h, d, w, y (Default: h)", "optional":true}
```

2021-08-30 14:15 UTC, unnamedd commented on commands/developer-utils/time-calculator.js
> +// @raycast.argument1 { "type": "text", "placeholder": "Starting Date DEFAULT: now", "optional":true }
```suggestion
// @raycast.argument1 { "type": "text", "placeholder": "Starting Date (Default: now)", "optional":true }
```

2021-08-30 14:15 UTC, unnamedd commented on commands/developer-utils/time-calculator.js
> +// @raycast.argument2 { "type": "text", "placeholder": "Time to add or subtract eg: -44, 44, +44" }
```suggestion
// @raycast.argument2 { "type": "text", "placeholder": "Time to Add/Subtract (eg: -44, 44, +44)" }
```

2021-08-30 14:15 UTC, unnamedd commented on commands/developer-utils/time-calculator.js
> +    console.log("Use s, m, h, d, w, y as units of mesure")
```suggestion
    console.log("Use s, m, h, d, w, y as units of measure")
```

2021-08-30 14:15 UTC, unnamedd commented on commands/developer-utils/time-calculator.js
> +// @raycast.description Add and Subtract specified amount of time from given date.
```suggestion
// @raycast.description Add or Subtract specified amount of time from given date.
```

2021-08-30 15:11 UTC, Mitra98t commented
Hello @unnamedd 
I should have resolved every comment with the last commit.
Hope I've done well!

2021-08-30 15:13 UTC, unnamedd approved these changes
Hello @Mitra98t,

it looks good to me! Thanks for your changes! 
Your PR should be merged soon!

2021-08-31 08:53 UTC, merged

2021-08-31 08:53 UTC, RSO commented
Thank you for the contribution, and welcome aboard!