Add zoom mute-mic.applescript command
raycast/script-commands pull request #573
Opened 2021-08-31 08:57 UTC by lcardito

## Description

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

## Dependencies / Requirements

## Checklist

- [ ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-08-31 10:43 UTC, unnamedd requested changes
Just some changes need to be done not in the code but in the meta tags.

Thanks for your contribution @lcardito!

2021-08-31 10:43 UTC, unnamedd commented on commands/communication/zoom/mute-mic.applescript
> +# @raycast.authorURL https://github.com/lcardito (credits Faris Aziz https://github.com/farisaziz12)
```suggestion
# @raycast.author Luigi Cardito
# @raycast.authorURL https://github.com/lcardito
# @raycast.author Faris Aziz
# @raycast.authorURL https://github.com/farisaziz12
```

2021-08-31 10:43 UTC, unnamedd commented on commands/communication/zoom/mute-mic.applescript
> +# @raycast.title Mute microphone
```suggestion
# @raycast.title Mute Microphone
```

2021-08-31 10:43 UTC, unnamedd commented on commands/communication/zoom/mute-mic.applescript
> +# @raycast.description Mutes your microphone in the current meetin
```suggestion
# @raycast.description Mute your microphone in the current meeting
```

2021-08-31 13:24 UTC, lcardito commented
Thanks @unnamedd for the quick review! Planning to add the same for toggling the video, shall I raise a different PR or add another script here?

2021-08-31 13:29 UTC, unnamedd commented
> Thanks @unnamedd for the quick review! Planning to add the same for toggling the video, shall I raise a different PR or add another script here?

It is up to you, as it is part of the Zoom package, you can add it here and I will review as soon you submit. Just don't forget to update the PR's title!

2021-08-31 13:42 UTC, lcardito commented
> > Thanks @unnamedd for the quick review! Planning to add the same for toggling the video, shall I raise a different PR or add another script here?
> 
> It is up to you, as it is part of the Zoom package, you can add it here and I will review as soon you submit. Just don't forget to update the PR's title!

Done! Let me how this looks! Thanks!

2021-08-31 14:22 UTC, unnamedd requested changes
@lcardito just remove the two lines as I suggested and we will be good to go!

2021-08-31 14:22 UTC, unnamedd commented on commands/communication/zoom/toggle-mic.applescript
> +# @raycast.needsConfirmation false
You can remove this line here

```suggestion
```

2021-08-31 14:22 UTC, unnamedd commented on commands/communication/zoom/toggle-video.applescript
> +# @raycast.needsConfirmation false
Remove this one as well

```suggestion
```

2021-08-31 15:59 UTC, unnamedd approved these changes
Looks good to me! 

Thanks for your changes @lcardito! 🤘

2021-09-01 07:00 UTC, lcardito commented
> Looks good to me!
> 
> Thanks for your changes @lcardito! 🤘

Thank you!!

2021-09-01 13:04 UTC, merged

2021-09-01 13:05 UTC, RSO commented
Thank you for your contributions!!! 🎉