Added script
raycast/script-commands pull request #574
Opened 2021-08-31 21:09 UTC by tfmart

## Description

Very excited to be sharing my first script with the community 🎉 

This script open the inputted URL on the iOS simulator that is currently booted, which also includes URL Schemes and Universal Links. This has been really handy when I need to test a deep link in my apps

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

![Gravação de Tela 2021-08-31 às 18 04 22](https://user-images.githubusercontent.com/23082132/131575932-2ec03b5a-61ba-4518-9759-b224be0a9f45.gif)

## Dependencies / Requirements

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-08-31 21:31 UTC, unnamedd requested changes
Hello @tfmart, 
really nice addition to our repository!

Just one small thing to keep your arguments conformant to our code style and then we will be good to go!

Thanks for your first contribution and welcome aboard!

2021-08-31 21:31 UTC, unnamedd commented on commands/developer-utils/open-link-simulator.applescript
> +# @raycast.argument1 { "type": "text", "placeholder": "Deep link" }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Deep Link" }
```

2021-08-31 21:57 UTC, tfmart commented
Thanks @unnamedd, I've committed your suggestion

2021-08-31 21:59 UTC, unnamedd approved these changes
Looks good to me! 
It should be merged soon! 🤘

2021-09-01 13:05 UTC, merged

2021-09-01 13:05 UTC, RSO commented
Thank you for your contribution! 🎉