Add Youtube statistics dashboard script
raycast/script-commands pull request #615
Opened 2021-11-01 21:54 UTC by astrit

## Description

Get your channel statistics like: views, subscribers and videos on Raycast dashboard
## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

![youtube-statistics](https://user-images.githubusercontent.com/2398447/139746533-1bff5c50-d57f-4829-b81c-3f1362be152e.jpg)

## Dependencies / Requirements

- You need to specify `Channel ID` — [Guide](https://support.google.com/youtube/answer/3250431?hl=en)
- You need to specify `YouTube Data API v3 API Key` — [Guide](https://developers.google.com/youtube/registering_an_application)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-11-01 22:42 UTC, unnamedd requested changes
Hi @astrit, thanks for another contribution. 
I made some few comments, please, after address them, let me know!

2021-11-01 22:42 UTC, unnamedd commented on commands/dashboard/youtube-statistics.rb
> +# @raycast.title Youtube Statistics
```suggestion
# @raycast.title YouTube Statistics
```

2021-11-01 22:42 UTC, unnamedd commented on commands/dashboard/youtube-statistics.rb
> +# @raycast.packageName Youtube Statistics
```suggestion
# @raycast.packageName YouTube Statistics
```

2021-11-01 22:42 UTC, unnamedd commented on commands/dashboard/youtube-statistics.rb
> +#!/usr/bin/env ruby
As you need extra setup to make this Script Command work, you need to rename this file to: `youtube-statistics.template.rb`.

2021-11-01 22:42 UTC, unnamedd commented on commands/system/wifi-password.sh
> +#!/bin/bash
This Script Command doesn’t belong to this pull request.

2021-11-06 22:31 UTC, astrit commented on commands/system/wifi-password.sh
> +#!/bin/bash
Do you mind checking now ?

2021-11-06 22:33 UTC, astrit commented
@unnamedd I did update and if you don't mind checking it

2021-11-07 11:57 UTC, closed without merging