Add YouTube Statistics and Add channel title
raycast/script-commands pull request #617
Opened 2021-11-07 12:17 UTC by astrit

## Description

Get your channel statistics like: views, subscribers, videos and channel title on Raycast dashboard

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

![yt](https://user-images.githubusercontent.com/2398447/140644545-4482c727-e879-47a8-9919-553aa073dcac.jpg)

## Dependencies / Requirements

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-11-07 15:11 UTC, unnamedd commented on commands/dashboard/youtube-statistics.template.rb
> +# @raycast.description Shows YouTube Subscribers
```suggestion
# @raycast.description Shows YouTube Subscribers, Views and Videos
```

2021-11-07 15:15 UTC, unnamedd commented on commands/dashboard/youtube-statistics.template.rb
> +
What about if you do something like

```suggestion
   item = result["items"][0] 
   statistics = item["statistics"]

   title = item["snippet"]["title"]
   subs = statistics["subscriberCount"]
   views = statistics["viewCount"]
   videos = statistics["videoCount"]
```

2021-11-07 15:17 UTC, unnamedd requested changes
Hey @astrit,

just minor comments here, nothing critical, but would improve a bit the Script Command!

2021-11-08 08:45 UTC, astrit commented
@unnamedd good idea actually I did update and now nothing else is open. Thank you very much for the suggestions. ✌️

2021-11-08 11:26 UTC, dehesa commented
Thanks for the contribution @astrit. Could you please squash all your commits?

2021-11-08 22:40 UTC, astrit commented
Hey @dehesa I did squash them please let me know if this is good ✌️

2021-11-09 09:33 UTC, closed without merging