Add Script Command: Generate Password
raycast/script-commands pull request #62
Opened 2020-11-12 20:07 UTC by hofmannsven

This script generates a random password with 40 chars and copies it to the clipboard.

Example: LsK9XN5CYq4YHFTR4gADCfne/Jtn/I+AbHoUeLJo

2020-11-12 20:14 UTC, unnamedd requested changes
Amazing addition! Just need to remove the changes on the files mentioned in the review comments.

Thanks for the Script Command and welcome aboard, @hofmannsven!

2020-11-12 20:14 UTC, unnamedd commented on extensions.json
> +      },
The `extensions.json` and `extension.md` are generated automatically, any changes made here will be overwritten.

2020-11-12 20:14 UTC, unnamedd commented on extensions.md
> +| 💻 | [Generate Password](developer-utils/generate-password.sh) | Generates a random password and copies it to the clipboard. | [Sven Hofmann](https://github.com/hofmannsven) |
The rollback of this addition is recommended, it is not needed.

2020-11-12 20:15 UTC, unnamedd commented on developer-utils/generate-password.sh
> +# @raycast.icon 💻
Maybe this icon 🔑 here might be better. What do you think?

2020-11-12 20:25 UTC, hofmannsven commented on developer-utils/generate-password.sh
> +# @raycast.icon 💻
I changed the icon from 💻 to 🔑

2020-11-12 20:39 UTC, unnamedd approved these changes

2020-11-13 19:03 UTC, PitNikola requested changes
Nice one, thanks for contribution!

I suppose user should have gpg installed? Let's mention it in the comments section and make this file `.template.` as per [new guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-additional-modification).

Sorry, we didn't have guidelines before 😬

2020-11-13 19:08 UTC, crstauf commented
> make this file `.template.` as per new guidelines

@PitNikola To me the contributions do not state that `.template.` is required for dependencies. Is this really the case? If so, `curl` and `open` are technically dependencies.

2020-11-13 19:12 UTC, unnamedd commented
> Do scripts with dependencies really need to have `.template.`? If so, `curl` and `open` are technically dependencies.

`open` is part of the system, `curl` is almost part of the system. It is embedded in almost every operating system, for that reason, I don't see reason to have them as `.template.`. To me it's different when you need to install something else, like the `gpg` here.

2020-11-13 19:18 UTC, crstauf commented
> when you need to install something else

A template is a starting point for creating something, and does not speak to other requirements. 

In painting, you've got a template for painting symbols, but that doesn't speak at all to the type or color or possession or quality of the paint.

2020-11-13 19:21 UTC, PitNikola commented
Okay, it's a valid point, `.template.` indeed doesn't speak to dependencies. Perhaps having a requirement to handle missing dependency is enough + instruction at the top in comments section stating the dependency.

2020-11-13 19:30 UTC, PitNikola commented
Okay, @hofmannsven, for now let's do it this way:

- Add handling of non-installed gpg command line ([here's example](https://github.com/raycast/script-commands/pull/67/files))
- Mention it in the comments section, e.g.

```
#!/bin/bash

# Dependencies: Requires installed [gpg cli](https://formulae.brew.sh/formula/gnupg)

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Generate Password
# @raycast.mode silent

# Optional parameters:
# @raycast.author Sven Hofmann
# @raycast.authorURL https://github.com/hofmannsven
# @raycast.description Generates a random password and copies it to the clipboard.
# @raycast.icon 🔐
```

2020-11-13 20:53 UTC, PitNikola commented
I've added new section to [CONTRIBUTING.md](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md) regarding to dependencies.

2020-11-17 11:49 UTC, thomaspaulmann commented
Hey @hofmannsven, looks like your script isn't in the right folder. We restructured our repository and you should move the script to `commands/developer-utils` as mentioned in our guidelines. Sorry for the inconvenience and thanks for understanding.

2020-11-17 11:49 UTC, thomaspaulmann requested changes
As mentioned, please move your script.

2020-11-17 23:30 UTC, thomaspaulmann approved these changes
Perfect and congrats for your first contribution @hofmannsven. Off to many more :-)

2020-11-17 23:30 UTC, merged