Add macOCR
raycast/script-commands pull request #621
Opened 2021-11-10 11:36 UTC by jaklan

## Description

Add OCR with `macOCR`

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

## Dependencies / Requirements

[macOCR](https://github.com/schappim/macOCR)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-11-10 16:54 UTC, unnamedd requested changes
Hey @jaklan, thanks for you contribution (again <3)!

I've made some small comments, please let me know when you finish to address them!

2021-11-10 16:54 UTC, unnamedd commented on commands/productivity/macocr/macocr-run-ocr.sh
> +# brew install schappim/ocr/ocr
Nice you added the instructions here, would you mind to follow the way defined in the [contributing.md](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)? 
```
# Dependency: This script requires `jq` cli installed: https://stedolan.github.io/jq/
# Install via homebrew: `brew install jq`
```

2021-11-10 16:54 UTC, unnamedd commented on commands/productivity/macocr/macocr-run-ocr.sh
> +result=$(ocr -l ${1:-"en-US"})
Also, make sure to check the existence of the `ocr` installed in the system:

```
if ! command -v download &> /dev/null; then
      echo "download command is required (https://github.com/kevva/download-cli).";
      exit 1;
fi
```

2021-11-10 16:54 UTC, unnamedd commented on commands/productivity/macocr/macocr-run-ocr.sh
> +echo $result | tee >(pbcopy)
I guess `tee` isn't installed by default in the system, right? If yes, it's better to add up in the requirements and also in the check before use.

2021-11-11 02:52 UTC, jaklan commented on commands/productivity/macocr/macocr-run-ocr.sh
> +echo $result | tee >(pbcopy)
@unnamedd hm, afaik - it is installed.
```shell
❯ which tee
/usr/bin/tee
```

2021-11-11 11:20 UTC, dehesa commented on commands/productivity/macocr/macocr-run-ocr.sh
> +echo $result | tee >(pbcopy)
It is also in my machine

2021-11-11 11:22 UTC, dehesa commented
Thanks for the addition @jaklan

2021-11-11 11:22 UTC, merged