Custom window size
raycast/script-commands pull request #623
Opened 2021-11-13 20:57 UTC by astrit

## Description

## Type of change

- [X] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

![cws](https://user-images.githubusercontent.com/2398447/141658697-7d9d9f29-41bd-4326-b0d0-bb97506c324a.jpg)

## Dependencies / Requirements

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-11-15 18:15 UTC, unnamedd requested changes
Hey @astritm thanks for you new contribution to our repository!

Just two small comments here! ;)

2021-11-15 18:15 UTC, unnamedd commented on commands/system/custom-window.applescript
> +# @raycast.packageName system
```suggestion
# @raycast.packageName System
```

2021-11-15 18:15 UTC, unnamedd commented on commands/system/custom-window.applescript
> +# @raycast.icon ?
```suggestion
# @raycast.icon images/custom-window-size.png
```

2021-11-16 17:29 UTC, astrit commented on commands/system/custom-window.applescript
> +# @raycast.packageName system
Updated.

2021-11-16 17:29 UTC, astrit commented on commands/system/custom-window.applescript
> +# @raycast.icon ?
Updated this also, not sure why It happened, initially had a emoji.

2021-11-16 17:29 UTC, unnamedd approved these changes
Now we are good to go! Thanks @astrit!

2021-11-16 18:04 UTC, astritm commented
Please tag the right @astrit 😊

2021-11-16 20:42 UTC, unnamedd commented
> Please tag the right @astrit 😊

Sorry! My bad! 😳

2021-11-17 16:41 UTC, merged