feat: random-number script command
raycast/script-commands pull request #625
Opened 2021-11-16 06:27 UTC by gleich

Signed-off-by: Matt Gleich <git@mattglei.ch>

## Description

This script-command allows the user to generate a number between a given range quickly

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

https://user-images.githubusercontent.com/43759105/141932900-d38b2af1-a3f6-44d0-b21d-29db52e10dbd.mov

## Dependencies / Requirements

`jot` and `pbcopy` are included by default in macOS

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-11-16 06:30 UTC, gleich commented
The demo seems to be cut off so here is a corrected video

https://user-images.githubusercontent.com/43759105/141933279-ac116d97-1546-4883-9db9-93f83f244e22.mov

2021-11-16 17:32 UTC, unnamedd requested changes
Hey @gleich, nice to see you around! 
I've made two suggestions, address them and when you finish we will be good to go!

2021-11-16 17:32 UTC, unnamedd commented on commands/math/random-number.sh
> +# @raycast.needsConfirmation false
```suggestion
```

2021-11-16 17:32 UTC, unnamedd commented on commands/math/random-number.sh
> +# @raycast.currentDirectoryPath ~
```suggestion
```

2021-11-16 17:37 UTC, gleich commented
Hey @unnamedd! Good to see you too! Just made the requested changes :)

2021-11-16 17:41 UTC, unnamedd commented
@gleich I was wondering here and I guess will make more sense if we name the arguments placeholder to indicate the numbers From and To, then the user will have an idea about the meaning of those arguments, don't you think?

2021-11-16 18:57 UTC, gleich commented
Agreed! Just fixed

2021-11-16 20:44 UTC, unnamedd approved these changes
We are good to go! Thanks for the changes @gleich!

2021-11-17 04:43 UTC, gleich commented
Great, thanks @unnamedd for the review!

2021-11-17 16:41 UTC, merged