Add script to place call via Apple's Cellular Calls feature
raycast/script-commands pull request #629
Opened 2021-12-07 03:02 UTC by alexjsteffen

Add a basic script using the native Cellular Call Feature provided by apple. There is no easy way to make a normal telephone call other than using the Contacts app or FaceTime (although the UX for this feature has gotten worse in Monterey. 

See: https://support.apple.com/en-ca/HT209456 

## Description

This script uses the "iPhone Cellular Call Feature" provided by apple to quickly make telephone calls without having to go via Contacts. Added one second of sleep to allow an individual to consider whether it was a mistake. It happens.

## Type of change

- [ ] New script command

## Screenshot

As simple as can be:

![Demo](https://user-images.githubusercontent.com/52205871/144958411-73b94102-e0fe-4bc0-930a-09d3941e6c17.gif)

## Dependencies / Requirements

None. 

## Checklist

- [ ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md) - Yes

2021-12-07 21:33 UTC, unnamedd requested changes
Hey @alexjsteffen,

I made two really small suggestions in the code, nothing to worry about but it will make your Script Command more conformant to the others we have.

Thanks a lot for your first contribution on our community and welcome aboard!

2021-12-07 21:33 UTC, unnamedd commented on commands/communication/call-with-iphone.sh
> +# @raycast.packageName Call
```suggestion
# @raycast.packageName Communication
```

2021-12-07 21:33 UTC, unnamedd commented on commands/communication/call-with-iphone.sh
> +# @raycast.description Place a telephone call via your iPhone on wifi.
```suggestion
# @raycast.description Place a telephone call via your iPhone on Wi-Fi.
```

2021-12-09 17:48 UTC, alexjsteffen commented on commands/communication/call-with-iphone.sh
> +# @raycast.description Place a telephone call via your iPhone on wifi.
Good suggestions. Just merged your change. Cheers :)

2021-12-09 22:33 UTC, unnamedd commented on commands/communication/call-with-iphone.sh
> +# @raycast.description Place a telephone call via your iPhone on wifi.
@alexjsteffen would apply this suggestion here as well? After it we will be good to go! ;)

2021-12-10 02:35 UTC, alexjsteffen commented
Done. Have a great eve.

2021-12-10 14:00 UTC, unnamedd approved these changes
Now we are good to go! ✅ 
Thanks a lot for your contribution @alexjsteffen!

2021-12-20 12:46 UTC, merged