Add Script Command: xkcdpass
raycast/script-commands pull request #63
Opened 2020-11-12 22:22 UTC by crstauf

https://pypi.org/project/xkcdpass/

2020-11-15 12:51 UTC, PitNikola requested changes
As discussed in Slack and per [new section in guidelines about dependencies](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-dependencies), let's add a comment section explicitly stating the dependency and installation instruction. Thanks!

2020-11-15 14:00 UTC, crstauf commented
@PitNikola Added dependency comments.

2020-11-16 20:58 UTC, thomaspaulmann requested changes
Nice one. What's the difference to #62? Do we need both?

2020-11-16 20:58 UTC, thomaspaulmann commented on commands/communication/xkcdpass.sh
> +# @raycast.title xkcdpass
Let's give it a proper title.
```suggestion
# @raycast.title Generate Passphrase
```

2020-11-16 21:19 UTC, crstauf commented
> What's the difference to #62? Do we need both?

Yes.

> There are dozens of random password generators out there that will happily put together a bunch of random characters for you to use as a password. These random passwords are secure, but they're a huge pain to actually remember.
> 
> Random passphrases provide the best combination of memorability and security.

Source: [useapassphrase.com](https://www.useapassphrase.com/#i-get-it-simple-passwords-are-cracked-easily-but-why-should-i-use-a-random-pass-phrase-instead-of-say-ipz2-az8k-0h-)

2020-11-16 22:16 UTC, merged