Add AWS SSO util script
raycast/script-commands pull request #633
Opened 2021-12-15 22:06 UTC by doktor500

## Description

Add script to logon to AWS using [aws-sso-util](https://github.com/benkehoe/aws-sso-util)

## Type of change

- [X] New script command

## Screenshot

![2021-12-15 22 54 34](https://user-images.githubusercontent.com/1174998/146271119-f2c671ee-1c4e-4681-ad0c-6925c89df44b.gif)

## Dependencies / Requirements

It requires to have [aws-sso-util](https://github.com/benkehoe/aws-sso-util) installed and configured

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2021-12-19 15:18 UTC, unnamedd requested changes

2021-12-19 15:18 UTC, unnamedd commented on commands/developer-utils/aws/aws-sso-util.sh
> +# @raycast.packageName Developer Utilities
```suggestion
# @raycast.packageName AWS
```

2021-12-19 15:18 UTC, unnamedd commented on commands/developer-utils/aws/aws-sso-util.sh
> +# @raycast.title AWS SSO
I'd prefer to use `Single Sign-On` here, it's more complete and descriptive, but of course, you are more aware than me how people used to refer to it on AWS world. So, feel free to accept this suggestion or not, it's not mandatory.

```suggestion
# @raycast.title Single Sign-On
```

2021-12-20 13:35 UTC, unnamedd approved these changes
Thanks for the change @doktor500! 

It looks good to me!

2021-12-28 21:33 UTC, doktor500 commented
Thanks, are we happy merging it then?

2021-12-29 01:34 UTC, unnamedd commented
@doktor500 it will be merged as soon as possible! The Raycast Team is on holiday! ;)

2021-12-30 11:22 UTC, merged

2021-12-30 11:22 UTC, dehesa commented
Hey @doktor500, sorry for the delay, but as @unnamedd said most of the team is on holidays. In any case, I will merge it right away. Thank you for the contribution.

2021-12-30 12:33 UTC, doktor500 commented
Thanks!