Add Script Commands: DND
raycast/script-commands pull request #64
Opened 2020-11-13 03:39 UTC by crstauf

2020-11-15 12:52 UTC, PitNikola requested changes
As discussed in Slack and per [new section in guidelines about dependencies](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-dependencies), let's add a comment section explicitly stating the dependency and installation instruction.

2020-11-15 14:04 UTC, crstauf commented
@PitNikola Added dependency comments.

2020-11-16 21:10 UTC, thomaspaulmann requested changes
A great one! I can use that quite often myself :-) 

Generally I would use a single command and toggling the do not disturb mode. There isn't much value having different command for turning it on/off. 

I was also digging into the [dependency tree](https://github.com/sindresorhus/do-not-disturb), at seems that you could build this entire command with `Swift`, maybe even with `AppleScript` and could avoid installing dependencies. This would make it easier for others to adopt the command. This is probably out of scope for this PR but I thought to bring it up.

2020-11-16 21:10 UTC, thomaspaulmann commented on commands/system/dnd-off.sh
> +# @raycast.icon 🌗
We ave the moon for toggle appearance already. 

```suggestion
# @raycast.icon 😴
```

2020-11-16 21:10 UTC, thomaspaulmann commented on commands/system/dnd-on.sh
> +# @raycast.icon 🌗
Same as above.

2020-11-16 21:10 UTC, thomaspaulmann commented on commands/system/dnd-on.sh
> +# @raycast.title Do Not Disturb - On
```suggestion
# @raycast.title Turn On Do Not Disturb
```

2020-11-16 21:10 UTC, thomaspaulmann commented on commands/system/dnd-off.sh
> +# @raycast.title Do Not Disturb - Off
```suggestion
# @raycast.title Turn Off Do Not Disturb
```

2020-11-16 21:21 UTC, crstauf commented
> There isn't much value having different command for turning it on/off

Unless you're not sure what the current state is, and want to make sure you've got the correct mode active.

2020-11-16 21:23 UTC, crstauf commented
> build this entire command with `Swift`, maybe even with `AppleScript`

I'd have no problem with this command being replaced by a native Swift or Applescript version.

2020-11-17 21:05 UTC, thomaspaulmann commented
> > build this entire command with `Swift`, maybe even with `AppleScript`
> 
> I'd have no problem with this command being replaced by a native Swift or Applescript version.

We should rather strive for the solution that makes most users happy. Having to install less dependencies is a more flawless experience. I don't think that people would just re-implement existing commands when there is one already committed.

2020-11-17 21:05 UTC, merged