Add Script Commands: emoji
raycast/script-commands pull request #65
Opened 2020-11-13 04:45 UTC by crstauf

2020-11-15 12:55 UTC, PitNikola requested changes
As discussed in Slack and per [new section in guidelines about dependencies](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-dependencies), let's add a comment section explicitly stating the dependency and installation instruction.

2020-11-15 14:09 UTC, crstauf commented
@PitNikola Added dependency comments.

2020-11-16 21:14 UTC, thomaspaulmann requested changes
Lets give the commands somewhat more descriptive titles. Otherwise they appear very general and are not easy to understand what they do.

2020-11-16 21:14 UTC, thomaspaulmann commented on commands/communication/emojis/emoji-copy.sh
> +# @raycast.title Copy emoji
Not sure if `Copy emoji` is a great name for this command. I couldn't tell what it does. How about this title?

```suggestion
# @raycast.title Search Emoji From Clipboard
```

2020-11-16 21:14 UTC, thomaspaulmann commented on commands/communication/emojis/emoji-copy.sh
> +# @raycast.mode compact
👍

2020-11-16 21:14 UTC, thomaspaulmann commented on commands/communication/emojis/emojis-search.sh
> +# @raycast.title Get emojis
```suggestion
# @raycast.title Search Related Emojis from Clipboard
```

2020-11-16 21:14 UTC, thomaspaulmann commented on commands/communication/emojis/emojis-search.sh
> +# @raycast.needsConfirmation true
Lets remove the `needsConfirmation`.

2020-11-16 21:14 UTC, thomaspaulmann commented on commands/communication/emojis/emoji-copy.sh
> +# @raycast.needsConfirmation true
I don't think you need a confirmation here.

2020-11-16 21:24 UTC, crstauf commented on commands/communication/emojis/emoji-copy.sh
> +# @raycast.title Copy emoji
This command searches for an emoji based on text in clipboard, and copies the first result to the clipboard. I'd like to give some indication to the user that the first result is copied.

2020-11-16 21:25 UTC, crstauf commented on commands/communication/emojis/emojis-search.sh
> +# @raycast.needsConfirmation true
As mentioned elsewhere, to me it's preferable to do a check to the user before the script accesses their clipboard, to confirm that they've the correct content there.

2020-11-16 21:25 UTC, crstauf commented on commands/communication/emojis/emoji-copy.sh
> +# @raycast.needsConfirmation true
As mentioned elsewhere, to me it's preferable to do a check to the user before the script accesses their clipboard, to confirm that they've the correct content there.

2020-11-17 21:03 UTC, thomaspaulmann approved these changes

2020-11-17 21:03 UTC, thomaspaulmann commented on commands/communication/emojis/emoji-copy.sh
> +# @raycast.needsConfirmation true
I'm not really convinced that this is a big issue. All commands are transparent and when you install them should be treated as safe. The confirmation dialog should be only used for irreversible actions, e.g. deleting files. I'll accept that one but I would please you to remove it from almost all commands to fit into the user experience of the rest of Raycast.

2020-11-17 21:03 UTC, merged