Add files via upload
raycast/script-commands pull request #667
Opened 2022-01-31 16:26 UTC by Rediwed

## Description

Adds a compact script command that allows you to quickly run terminal commands from within Raycast. Alternatively, (if no input command is given) the script command will open terminal or bring it to the front.

## Type of change

- [x] New script command

## Screenshot

![Screenshot of Raycast running Quick Terminal](https://user-images.githubusercontent.com/9107063/151832341-4f949e9d-d2dc-4468-b628-200d006a1f50.png)

## Dependencies / Requirements

None

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2022-01-31 16:29 UTC, Rediwed commented
Hi there! This is my first pull request on Github, so please inform me if I’ve made any mistakes. Thanks :)

2022-01-31 17:29 UTC, dehesa requested changes
Hy @Rediwed. Congratulations on your 1st PR 🎉 It looks great, but please look at the comment I left and reduce the icon size to 64x64px.

2022-01-31 17:29 UTC, dehesa commented on commands/apps/terminal/quick-terminal.applescript
> +# @raycast.argument1 { "type": "text", "placeholder": "Command (opt)", "optional": true }
No need for the placeholder text `(opt)` since you already marked `"optional": true`. That already adds a visual marker to the command in Raycast.

2022-01-31 19:03 UTC, unnamedd commented
Hello @Rediwed, thanks for your first contribution to our repository, however, unfortunately a already have a Script Command doing exactly what you are proposing here.

Script Command: [developer-utils/run-bash-command.sh](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/run-bash-command.sh).

2022-01-31 19:53 UTC, Rediwed commented on commands/apps/terminal/quick-terminal.applescript
> +# @raycast.argument1 { "type": "text", "placeholder": "Command (opt)", "optional": true }
Good to know, thanks!

2022-01-31 19:58 UTC, Rediwed commented
> Hello @Rediwed, thanks for your first contribution to our repository, however, unfortunately a already have a Script Command doing exactly what you are proposing here.
> 
> Script Command: [developer-utils/run-bash-command.sh](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/run-bash-command.sh).

Ah, I oversaw that one (there are so many)! That’s unfortunate. Will you close this request or should I make the requested changes?

2022-01-31 21:54 UTC, unnamedd commented
Definitely it’s not a nice thing to have duplicated Script Commands in the repository, it might bring confusion to the users. I’d rather close the PR due to the duplication, however, Marco suggested some changes, then make sense to read what he has to say.

@dehesa, your opinion, please?

2022-02-01 11:11 UTC, dehesa commented
@unnamedd is completely right. I also overlooked we had that. I will close this PR without merging. Sorry @Rediwed. We still appreciate you took the time to write here and be responsive.

2022-02-01 11:11 UTC, closed without merging