Add support for generating unique DuckDuckGo Email Protection addresses
raycast/script-commands pull request #681
Opened 2022-02-09 11:22 UTC by Rediwed

# Description

DuckDuckGo Email Protection is an email protection service (currently invite-only). After having been invited, DDG provides you with an intermediary e-mail address ([you@duck.com](mailto:you@duck.com)). Any e-mail sent to this address will be stripped of its analytics components, before being forwarded to your actual e-mail address ([you@you.com](mailto:you@you.com)).

This script command lets you quickly generate a unique @duck.com address that is connected to your own e-mail address. Just like your personal [you@duck.com](mailto:you@duck.com) address, the unique addresses will also forward any e-mail to your own e-mail address, after having been stripped of any tracking or analytics modules.

# Type of change

- [x] New Script Command

(I have added this script command to the communication group, becuase it is related to generating unique email addresses instead of related to performing web-searches)

# Screenshot

![Screenshot of Microsoft Excel on 2022-02-08 at 14 24 07](https://user-images.githubusercontent.com/9107063/153189940-7b8ac7a5-0eef-4eb3-9252-5f106cc56b96.png)

Dependencies / Requirements

- It is required to have been invited into the @duck.com email protection service.
- It is also required to extract your authorization ID from the official DuckDuckGo Privacy Essentials extension (see README.md).

# Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2022-02-09 14:33 UTC, dehesa requested changes
Hi @Rediwed,

This looks pretty useful. I wasn't aware of it. Cool stuff! I left you some comments below.

By the way, these scripts would benefit from being an [extension](https://developers.raycast.com/). Check them out, if you weren't aware of it.

2022-02-09 14:33 UTC, dehesa commented on commands/communication/duckduckgo-email-protection/README.md
> +![image](https://user-images.githubusercontent.com/9107063/152996647-676ff3df-4ebe-49a5-a28d-97d2fe21ec94.png)
We don't currently accept images to external services. Could you add it to the PR under the `images` folder.
Be sure to reduce the pixel density as much as you can (while still being readable) and pass the image by [ImageOptim](https://imageoptim.com/mac) (or similar compressors).

2022-02-09 14:33 UTC, dehesa commented on commands/communication/duckduckgo-email-protection/README.md
> +![Screenshot of Raycast on 2022-02-08 at 14 24 07](https://user-images.githubusercontent.com/9107063/152995951-91c9f7bd-eddd-43a3-98b0-79dad33308eb.png)
Same thing here.

2022-02-09 14:33 UTC, dehesa commented on commands/communication/duckduckgo-email-protection/README.md
> +![Screenshot of Firefox on 2022-02-08 at 14 21 47](https://user-images.githubusercontent.com/9107063/152995838-fe619525-b4dd-4d3d-bf7f-95c07ed7b2d2.png)
and here.

2022-02-09 14:33 UTC, dehesa commented on commands/communication/duckduckgo-email-protection/generate-unique-email-address.applescript
> +# @raycast.title Generate unique address
It should be titlecased; i.e. `Generate Unique Address`

2022-02-09 16:54 UTC, dehesa requested changes

2022-02-09 16:54 UTC, dehesa commented on commands/communication/duckduckgo-email-protection/README.md
> +![Locate authorization](locate-authorization-id.png)
You forgot the `images/` prefix 😄

2022-02-10 07:39 UTC, Rediwed commented on commands/communication/duckduckgo-email-protection/README.md
> +![Locate authorization](locate-authorization-id.png)
Darn it! Fixed it now :)

2022-02-10 08:48 UTC, merged

2022-02-10 08:49 UTC, dehesa commented
Thanks for the great contribution, @Rediwed

2022-02-10 16:26 UTC, Rediwed commented
> By the way, these scripts would benefit from being an [extension](https://developers.raycast.com/). Check them out, if you weren't aware of it.

Sorry, overread this comment. Thank you for pointing it out, though I was aware of Extensions.

I'm not comfortable with React, Node.js, or TypeScript. Otherwise, I definitely would've made an extension 🙂 I've worked with AppleScript (and AppleScriptObjC) for the more than a decade, and recently started working with Python (though mostly for data-science, not really programming).

What made me so much more excited for Raycast (over Alfred or Launchbar) was that I could actually augment it with AppleScript. So thank you so much for allowing that!

2022-02-10 20:56 UTC, dehesa commented
I understand. Many thanks for taking the time to contribute this to the community.