Run a Shell Command using Hyper
raycast/script-commands pull request #682
Opened 2022-02-10 02:27 UTC by eIiot

## Description

Allows the user to run a shell command in Hyper through Raycast

## Type of change

- [x] New script command

## Screenshot

![CleanShot 2022-02-09 at 18 23 45](https://user-images.githubusercontent.com/39346975/153325327-65757564-837b-4fce-8928-7cc922dfd995.gif)

## Dependencies / Requirements

Requires [`hyperalfred`](https://github.com/gjuchault/hyperalfred) and [Hyper](https://hyper.is/)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2022-02-10 08:57 UTC, dehesa requested changes
Hi @eIiot,

Nice contribution. I left a small comment, but also please reduce the icon size to 64x64 px. I would recommend you to trim some white space margin in the icon, then reduce it to 64x64 and finally pass it by a compressor, such as [ImageOptim](https://imageoptim.com/mac).

2022-02-10 08:57 UTC, dehesa commented on commands/apps/hyper/hyper-run-shell-command.applescript
> +# @raycast.argument1 { "type": "text", "placeholder": "command" }
Please use titlecase for the placeholder (i.e. `Command`).

2022-02-10 08:57 UTC, dehesa commented on commands/apps/hyper/hyper-run-shell-command.applescript
> +# Install via Hyper: `hyper i hyperalfred`
No `hyperraycast`? 😛

2022-02-10 17:51 UTC, eIiot commented on commands/apps/hyper/hyper-run-shell-command.applescript
> +# Install via Hyper: `hyper i hyperalfred`
It's an adaptation of the similar Alfred script that makes compatibility possible. I could write my own, but there would be no functionality difference :)

2022-02-10 17:58 UTC, eIiot commented
Thanks for the suggestions! I've changed the icon resolution and added the titlecase, is there anything else?

2022-02-10 20:50 UTC, dehesa commented on commands/apps/hyper/hyper-run-shell-command.applescript
> +# Install via Hyper: `hyper i hyperalfred`
Yeah, I know I was just kidding 😄

2022-02-11 12:39 UTC, dehesa requested changes
Please @eIiot, follow @unnamedd advices. He is a wiser man than I am 😄

2022-02-17 11:37 UTC, dehesa commented on commands/apps/hyper/hyper-run-shell-command.applescript
> +      log "~/.hyper_plugins/hyperalfred.txt does not exist. Are you sure you installed hyperalfred? (https://github.com/gjuchault/hyperalfred)"
Hey @eIiot sorry for the delay,
I believe @unnamedd is referring to the content of the string (please @unnamedd correct me if I am wrong). So you could say slightly the same more tersely:
```
log "hyperalfred is required (https://github.com/gjuchault/hyperalfred)."
```

2022-02-17 11:37 UTC, dehesa commented on commands/apps/hyper/hyper-run-shell-command.applescript
> +    log "Hyper is required (https://hyper.is)"
@unnamedd what do you mean exactly?

2022-02-17 15:49 UTC, unnamedd commented on commands/apps/hyper/hyper-run-shell-command.applescript
> +      log "~/.hyper_plugins/hyperalfred.txt does not exist. Are you sure you installed hyperalfred? (https://github.com/gjuchault/hyperalfred)"
You are completely right @dehesa! That's exactly what I meant here. 

Sorry for the big delay, folks!

2022-02-17 18:44 UTC, unnamedd commented on commands/apps/hyper/hyper-run-shell-command.applescript
> +    log "Hyper is required (https://hyper.is)"
The point here it is just to follow the same pattern used up there, just to keep it conformant ;)

2022-02-18 06:10 UTC, eIiot commented
Okay, I should have fixed all the previous issues. Anything else?

2022-02-18 10:18 UTC, dehesa commented
Looking good, thank you @eIiot (and sorry for the back-and-forth).

2022-02-18 10:19 UTC, merged