Add close all Finder windows command.
raycast/script-commands pull request #684
Opened 2022-02-15 04:07 UTC by alexjsteffen

## Description

As you may know, it is not easy to close multiple open Finder windows without using the Finder-specific keyboard shortcut. This AppleScript will close all windows while keeping other apps open and Finder without forcing Finder to close and reopen.

## Type of change

- [ ] New script command

## Screenshot

![demo](https://user-images.githubusercontent.com/52205871/153990854-24e96948-da48-4abf-9fb7-4b585adb77a1.gif)

## Dependencies / Requirements

None

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2022-02-15 09:56 UTC, dehesa requested changes
Hi @alexjsteffen , thanks for the contribution.
I suggested some changes below 😉

2022-02-15 09:56 UTC, dehesa commented on commands/system/close-finder-windows.applescript
> +# @raycast.title Close all currently open Finder windows.
We use titlecase for command's titles, also the title is a bit too long. What about `Close All Finder Windows`, instead?

2022-02-15 09:56 UTC, dehesa commented on commands/system/close-finder-windows.applescript
> +# @raycast.packageName Navigation
The package name should be `System`

2022-02-15 09:56 UTC, dehesa commented on commands/system/close-finder-windows.applescript
> +# @raycast.description Close all open Finder windows. They add up.
Remove the `They add up.` 😄

2022-02-18 23:45 UTC, alexjsteffen commented on commands/system/close-finder-windows.applescript
> +# @raycast.title Close all currently open Finder windows.
That works great! Agreed.

2022-02-18 23:45 UTC, alexjsteffen commented on commands/system/close-finder-windows.applescript
> +# @raycast.packageName Navigation
Sounds good. I was wondering for a bit as to where it should belong.

2022-02-18 23:46 UTC, alexjsteffen commented on commands/system/close-finder-windows.applescript
> +# @raycast.description Close all open Finder windows. They add up.
Haha, I like to add a little sardonic humour to my life. Of course.

2022-02-18 23:46 UTC, alexjsteffen reviewed
I agree with the amendments. Let me know what else you'd like.

2022-02-21 01:11 UTC, dehesa approved these changes

2022-02-21 01:12 UTC, dehesa commented
Good stuff!

2022-02-21 01:12 UTC, merged

2022-04-23 00:25 UTC, zaksuhar commented
Hi there, I propose adding an "Open New Finder Window" option to this!

Do you know if this type of workflow is possible?

#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Open New Finder Window
# @raycast.mode silent
# @raycast.packageName System
#
# Optional parameters:
# @raycast.icon 📁
#
# Documentation:
# @raycast.description Open a new Finder window
# @raycast.author Alexander Steffen
# @raycast.authorURL https://github.com/alexjsteffen

2022-04-23 10:15 UTC, dehesa commented
Hey @zaksuhar 

Your script just opens a new finder window. What do you mean by "adding an option to this"? Do you mean to first close all the windows and then open a single window?