Add Brew Cask Upgrade Command
raycast/script-commands pull request #697
Opened 2022-03-01 22:50 UTC by LanikSJ

## Description

Add Brew Cask Upgrade Command

## Type of change

- [x] New script command

## Screenshot

![Screen Shot 2022-03-01 at 2 48 33 PM](https://user-images.githubusercontent.com/12159404/156261984-a519a2b2-33c3-4215-85b2-38a7709f5904.png)

## Dependencies / Requirements

Installation [cask upgrade](https://github.com/buo/homebrew-cask-upgrade) is required.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2022-03-02 09:45 UTC, dehesa requested changes
Hey @LanikSJ,

Thank you for your contribution. I didn't know about [`brew-cask-upgrade`](https://github.com/buo/homebrew-cask-upgrade), but it looks pretty neat.

I left you some small comments/suggestions.

2022-03-02 09:45 UTC, dehesa commented on commands/developer-utils/brew/brew-cask-upgrade.sh
> +#
If a dependency is required, as it's in your case, you need to define it at the top of the file, right under the `!#/bin/bash`. Check out the [CONTRIBUTING.md](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md) 😉 

```bash
# Dependency: This script requires `brew-cask-upgrade` cli installed: https://github.com/buo/homebrew-cask-upgrade
# Install via homebrew: `brew tap buo/cask-upgrade `
```

2022-03-02 09:45 UTC, dehesa commented on commands/developer-utils/brew/brew-cask-upgrade.sh
> +# @raycast.description Run Brew Cask Upgrade
The description should be a bit more "descriptive". Such as: `Updates brew and upgrades every outdate app.`

2022-03-02 18:06 UTC, LanikSJ commented on commands/developer-utils/brew/brew-cask-upgrade.sh
> +#
I have no idea how but I totally missed that text I will address it.

2022-03-02 18:06 UTC, LanikSJ commented on commands/developer-utils/brew/brew-cask-upgrade.sh
> +# @raycast.description Run Brew Cask Upgrade
Thank you will make this change also.

2022-03-03 08:31 UTC, dehesa commented
Looks great! Thanks again and congrats on your 1st contribution! 🎉

2022-03-03 08:32 UTC, merged