Add Script Command: download-url
raycast/script-commands pull request #70
Opened 2020-11-13 07:18 UTC by crstauf

[Weirdness](https://github.com/raycast/script-commands/compare/master...crstauf:add/download-url?expand=1#diff-479aaa3e7b2f8b9056dc772d91cd5b1aeff0e57519fa4aedb625f1699c8cd366R13) as mentioned in [Slack](https://raycastcommunity.slack.com/archives/C01D1B36344/p1605247189239000) and https://github.com/raycast/script-commands/pull/68#issue-520381268:

> due to permissions troubles, i was forced to create a new global directory for npm packages… while a command works from my Terminal, i can’t get the same command to work from a Script Command… i’ve tried everything i know but not working. can someone with more knowledge on this please advise?

2020-11-13 15:47 UTC, unnamedd commented on browsing/download-url.sh
> +cmnd=$(npm config get prefix)/bin/download
Instead of using that `download`, why not use `cURL` do to the job? The chances to use the computer has it, is bigger than this one and reduce one step to make this script command work.

2020-11-13 15:47 UTC, unnamedd commented on browsing/download-url.sh
> +	"$cmnd" -o ~/Desktop $clipboard
What will be the name of the file downloaded here? The full URL or just the of it? (In this case the filename + extension)

2020-11-13 15:48 UTC, crstauf commented on browsing/download-url.sh
> +	"$cmnd" -o ~/Desktop $clipboard
Would be the filename and extension.

2020-11-13 15:51 UTC, crstauf commented on browsing/download-url.sh
> +cmnd=$(npm config get prefix)/bin/download
Because with `curl`, filename has to be specified; `download` handles that on its own. Perhaps I'll submit a separate Script Command for quickly running `curl`.

2020-11-13 15:56 UTC, unnamedd commented on browsing/download-url.sh
> +cmnd=$(npm config get prefix)/bin/download
So then I guess we can do this in this PR instead of a second one. I don't see reasons to have two different script commands one to use `download-cli` and one to use `cURL`. To use cURL, we will have to work a bit more, but at least it will solve the problem and no one will have to install any extra thing. What do you think?

2020-11-13 15:57 UTC, unnamedd commented on browsing/download-url.sh
> +	"$cmnd" -o ~/Desktop $clipboard
I'm sure we can manage that by ourselves.

2020-11-13 15:58 UTC, crstauf commented on browsing/download-url.sh
> +cmnd=$(npm config get prefix)/bin/download
If someone submits a PR for `curl` that has the same behavior as `download`, I'll gladly close this PR in favor of that one.

2020-11-13 17:22 UTC, crstauf commented
Weirdness has been removed, thanks to @unnamedd!

2020-11-16 21:25 UTC, thomaspaulmann requested changes
Could you clarify what this command downloads? I also added some suggestions for title, mode and confirmation.

Thanks for another contribution, yeah!

2020-11-16 21:25 UTC, thomaspaulmann commented on commands/browsing/download-url.sh
> +# @raycast.needsConfirmation true
Let's remove this. I don't think we need a confirmation for this script.

2020-11-16 21:25 UTC, thomaspaulmann commented on commands/browsing/download-url.sh
> +# @raycast.title Download URL in clipboard
Title case :-)
```suggestion
# @raycast.title Download URL in Clipboard
```

2020-11-16 21:25 UTC, thomaspaulmann commented on commands/browsing/download-url.sh
> +# @raycast.description Download URL in clipboard.
What does it download? The sources? The entire page? Just HTML? Could you please clarify?

2020-11-16 21:25 UTC, thomaspaulmann commented on commands/browsing/download-url.sh
> +# @raycast.mode silent
This should be a `compact` script since it does a long-running network request.

```suggestion
# @raycast.mode compact
```

2020-11-16 21:34 UTC, crstauf commented on commands/browsing/download-url.sh
> +# @raycast.needsConfirmation true
I request confirmation whenever the clipboard is in use, as a prompt to the user to check the clipboard's contents. Also whenever files are being generated.

2020-11-16 21:34 UTC, crstauf commented on commands/browsing/download-url.sh
> +# @raycast.mode silent
I specifically choose `silent` in these cases because I'd rather set it running and leave it, and come back to it later.

2020-11-16 21:36 UTC, crstauf commented on commands/browsing/download-url.sh
> +# @raycast.description Download URL in clipboard.
Downloads whatever is present at the URL:

|URL|File type|
|---|---|
|https://github.com|HTML|
|https://github.com/styles.css|CSS|
|https://github.com/scripts.js|JavaScript|
|https://github.com/logo.png|PNG|

2020-11-19 22:59 UTC, thomaspaulmann requested changes
Please adjust the `mode` to be `compact` and remove `needsConfirmation` to align the command to the others in this repository. Thanks.

2020-11-19 22:59 UTC, thomaspaulmann commented on commands/browsing/download-url.sh
> +# @raycast.mode silent
As discussed in Slack, please make sure to use `compact` to follow other the UX of other commands in this repository. Thanks

2020-11-23 16:00 UTC, fe9lix commented
@crstauf What does this script do exactly or when would you use it? If it downloads the passed URL to a certain location, let's use curl instead of the download-url package here.

2020-11-23 16:01 UTC, crstauf commented
> let's use `curl` instead of the `download-url` package

I'm unable to. Closing.

2020-11-23 16:01 UTC, closed without merging