add Celebrate script
raycast/script-commands pull request #726
Opened 2022-05-18 17:53 UTC by Fatpandac

## Description

Set Confetti run times and intervals

## Type of change

- [X] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

<img width="862" alt="image" src="https://user-images.githubusercontent.com/30423976/169108746-eed6d4e7-00eb-4ccc-9fb4-e94b73d11b3d.png">

## Dependencies / Requirements

Raycast >= 1.35.0

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2022-05-18 20:48 UTC, unnamedd requested changes
Hello @Fatpandac 👋

I've made some comments in your PR in order to keep it conformant to our repository. As soon as you finish to address them, please re-request a review! 

Thanks for your contribution! ;)

2022-05-18 20:48 UTC, unnamedd commented on commands/apps/raycast/celebrate.sh
> +# @raycast.packageName Celebrate
```suggestion
# @raycast.packageName Raycast
```

2022-05-18 20:48 UTC, unnamedd commented on commands/apps/raycast/celebrate.sh
> +# @raycast.argument1 { "type": "text", "placeholder": "times, defualt by 1", "optional": true }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Times (Default: 1)", "optional": true }
```

2022-05-18 20:48 UTC, unnamedd commented on commands/apps/raycast/celebrate.sh
> +# @raycast.argument2 { "type": "text", "placeholder": "interval, defualt by 0", "optional": true  }
```suggestion
# @raycast.argument2 { "type": "text", "placeholder": "Interval (Default: 0)", "optional": true  }
```

2022-05-18 20:48 UTC, unnamedd commented on commands/apps/raycast/celebrate.sh
> +# @raycast.description Set Confetti run times and intervals
```suggestion
# @raycast.description Set Confetti to run for a number of times and during intervals
```

2022-05-19 11:07 UTC, dehesa commented
This is great @Fatpandac 😄

2022-05-19 11:07 UTC, merged