feat(navigation): iterm support back
raycast/script-commands pull request #73
Opened 2020-11-14 22:14 UTC by japanese-goblinn

## Description

Please write a short summary for this change. If it's a new script command, explain what it does.

## Type of change

- [ ] New script command
- [ ] Bug fix
- [x] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other

## Screenshot

<img width="744" alt="Screen Shot 2020-11-15 at 01 13 42" src="https://user-images.githubusercontent.com/33631005/99158067-d2bb8800-26df-11eb-98f1-15441c635868.png">

## Dependencies / Requirements

`iTerm 2` installed

2020-11-15 13:14 UTC, PitNikola commented
Hm, I guess it's one of those cases where iTerm is kind of a dependency, but an obvious one which is mentioned in the name (same as Spotify). We should rephrase our guidelines a bit to make it more clear what is considered to be a dependency. Otherwise we would need to handle cases when iTerm is not installed [per our new guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-dependencies). Btw, do you know if there is a way to check if an app is installed via Apple Script?

2020-11-16 14:16 UTC, thomaspaulmann commented
Yeah, seems fine to not mention `iTerm` as a dependency in the comments of the script command. @japanese-goblinn could you rebase your branch and adjust to the restructuring that has landed on master. Your command should go into `./commands/navigation`. 

It would be cool to use `iTerm`'s app icon. I extracted it from the bundle and added it here. Feel free to add it yourself.
![iterm-logo](https://user-images.githubusercontent.com/12066405/99261174-4199fd80-2814-11eb-8e73-77530cc3758c.png)

2020-11-16 14:18 UTC, thomaspaulmann requested changes
Please rebase your branch and adopt the latest restructuring. Your command should go into `commands/navigation`. Thanks 🙌

2020-11-16 14:23 UTC, japanese-goblinn commented
> Please rebase your branch and adopt the latest restructuring. Your command should go into `commands/navigation`. Thanks 🙌

yep, I'll do it soon

2020-11-21 22:51 UTC, thomaspaulmann requested changes
Thanks for adding the iTerm icon. Now it feels nicely integrated. Let's make the user-visible strings title-cased to look between the other commands. Otherwise it's good to go.

2020-11-21 22:51 UTC, thomaspaulmann commented on commands/navigation/open-finder-from-iterm.applescript
> +# @raycast.title Open current iTerm directory in Finder
Let's make it title-cased to align with the other commands.
```suggestion
# @raycast.title Open Current iTerm Directory in Finder
```

2020-11-21 22:51 UTC, thomaspaulmann commented on commands/navigation/open-finder-from-iterm.applescript
> +# @raycast.icon images/iterm-logo.png
Thanks for adding the logo. Now it's nicely integrated and feels like an extension of iTerm.

2020-11-21 22:51 UTC, thomaspaulmann commented on commands/navigation/open-finder-from-iterm.applescript
> +# @raycast.description Open curren iTerm directory in Finder
Small typo
```suggestion
# @raycast.description Open the current iTerm directory in Finder
```

2020-11-21 22:51 UTC, thomaspaulmann commented on commands/navigation/open-iterm-from-finder.applescript
> +# @raycast.title Open current Finder directory in iTerm
Same as above.
```suggestion
# @raycast.title Open Current Finder Directory in iTerm
```

2020-11-21 22:51 UTC, thomaspaulmann commented on commands/navigation/open-iterm-from-finder.applescript
> +# @raycast.description Open curren Finder directory in iTerm
```suggestion
# @raycast.description Open the current Finder directory in iTerm
```

2020-11-21 23:06 UTC, japanese-goblinn commented
@thomaspaulmann done

2020-11-21 23:08 UTC, japanese-goblinn commented
@thomaspaulmann really confused who this curren was and how she appeared in script descriptions

2020-11-23 16:19 UTC, merged