add custom script that adds short urls with emojis
raycast/script-commands pull request #730
Opened 2022-05-31 03:27 UTC by samueljim

## Description
Adds script to turn https://www.raycast.com/blog/making-a-raycast-wallpaper/ into https://bne.sh/🍗🚥🧏‍♂️

## Type of change

- [ ] New script command

## Screenshot
<img width="562" alt="image" src="https://user-images.githubusercontent.com/19277887/171086620-52190181-f1c9-4711-922b-d048dc023cc1.png">
[bne.sh/create](https://bne.sh/create) lets you make URLs but this script lets you make a short url for free

## Dependencies / Requirements
NA

## Checklist

- [ ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2022-06-02 10:39 UTC, dehesa requested changes
Hi @samueljim,

Thank you for the contribution. I didn't know about the emoji shorting. Please don't commit changes in the `README.md` file, this would be done automatically by a hook.

2022-06-02 10:39 UTC, dehesa commented on commands/browsing/short-url-emoji.sh
> +# @raycast.packageName 😍🥹😠
Although very cute 😄 Please change the `packageName` to `Browsing`.

2022-06-16 17:00 UTC, dehesa commented
Hey @samueljim, will you continue working on this?

2022-06-20 00:21 UTC, samueljim commented on commands/browsing/short-url-emoji.sh
> +# @raycast.packageName 😍🥹😠
I have removed my changes to the readme files. I have also made your change as requested

2022-06-20 06:40 UTC, merged