add CopyCode script
raycast/script-commands pull request #734
Opened 2022-06-14 10:28 UTC by Fatpandac

## Description

Copy code from Chinese message.

## Type of change

- [X] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

<img width="862" alt="image" src="https://user-images.githubusercontent.com/30423976/173556539-8d81084a-808d-4e04-9028-da55f492ed43.png">

## Dependencies / Requirements

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2022-06-16 17:02 UTC, dehesa commented
Hi @Fatpandac,

Thank you for the contribution. Could you please explain further what this script does? Maybe send a gif/video showing how it works? I am not sure I am understanding it from the script code.

2022-06-16 18:16 UTC, Fatpandac commented
Just copy the code from a message in the Message APP.
![cc](https://user-images.githubusercontent.com/30423976/174138351-6093cbe3-ab21-469a-99f2-508c024ea59a.gif)

2022-06-20 07:16 UTC, dehesa requested changes
Hi @Fatpandac 

Thank you for the gif and sorry for the delay reviewing this. The scripts is pretty neat and useful. I would recommend making this scrip "international" by letting the user select the word being search in the message. Currently you hardcode `验证码` but I believe it would be better if this would be an optional message which defaults in the code a user can hardcode. What do you think?

2022-06-20 07:16 UTC, dehesa commented on commands/apps/Message/copycode.sh
> +  echo "最近60秒未收到验证码！"
I would appreciate if the `echo` is in English. Raycast doesn't currently support internationalization and English is (for now) the development language.

```
echo "No verification code received in the last 60 seconds!"
```

2022-06-20 07:16 UTC, dehesa commented on commands/apps/Message/copycode.sh
> +  echo "$code 验证码已复制"
Same thing here:

```
echo "$code code copied!"
```

2022-06-20 07:16 UTC, dehesa commented on commands/apps/Message/copycode.sh
> +keyword="验证码";
I would make this an optional argument with a default value. You do that by setting the `@raycast.argument1` in the header:

```
# @raycast.argument1 { "type": "text", "placeholder": "code", "optional": true }
```

and then using `$1` for the `keyword`.

```
keyword=$1;
```

2022-06-23 02:32 UTC, Fatpandac commented on commands/apps/Message/copycode.sh
> +keyword="验证码";
Maybe I can create a keyword list, everyone can open other PR to add another keyword into the keyword list to support other language messages because the keyword just needs set up once.

2022-06-23 08:38 UTC, dehesa commented on commands/apps/Message/copycode.sh
> +keyword="验证码";
Sure, that seems good to me.

2022-06-23 10:59 UTC, merged

2022-06-23 11:00 UTC, dehesa commented
Thanks for the useful script @Fatpandac