ocr_swift
raycast/script-commands pull request #735
Opened 2022-06-17 09:32 UTC by wmszhe

OCR with macOS Vision

2022-06-20 08:36 UTC, dehesa requested changes
Hi @wmszhe 

Thank you for the contribution. I tried your code with a random QR code, but it doesn't work for me. Could you provide a QR code example with the PR, please?

Also, it would be great to have more detail on what the script actually do. Where does the script read the png from? Where does the output goes? I would appreciate if you code add a gif showing what the script does.

2022-06-20 08:36 UTC, dehesa commented on commands/system/ocr.swift
> +        let _ = detectText(fileName: URL(fileURLWithPath: tmpPath))
What is this function for? It is never returning anything

2022-06-20 08:36 UTC, dehesa commented on commands/system/ocr.swift
> +// @raycast.description OCR with macOS Vision
I would appreciate a better description. What does this script do? Where is the input of the OCR and where the output goes?

2022-07-04 08:04 UTC, wmszhe commented
Use macOS Vision API Identification pictures, if it contain a QR code, Copy the QR code content to the clipboard, If do not include QR codes, identify text content and supplement to clipboard

GIF: https://github.com/wmszhe/pichub/blob/3aad700130158a0a538504b82d8c1010c3d4bb3c/imgs/ocr.gif

2022-07-08 08:46 UTC, unnamedd requested changes
Hi @wmszhe,

thanks for your contribution to our repository, as we all Swift developers, we (me and Marcos) made some comments for you in order to make your contribution even better.

Check them out and let us what you think.

2022-07-08 08:46 UTC, unnamedd commented on commands/system/ocr.swift
> +func screenCapture(_ command: String) throws -> String{
```suggestion
@discardableResult
func screenCapture(_ command: String) throws -> String {
```

2022-07-08 08:46 UTC, unnamedd commented on commands/system/ocr.swift
> +        let _ = try screenCapture("/usr/sbin/screencapture -i " + screenCapturePath)
If you add the annotation `@discardableResult` in the `screenCapture` method, you won't need to make use of `let _ =`

```suggestion
        try screenCapture("/usr/sbin/screencapture -i " + screenCapturePath)
```

2022-07-08 08:46 UTC, unnamedd commented on commands/system/ocr.swift
> +    }
You are unwrapping the content from `CIImage(contentOf:)` in the line 72, why not do the same with this guard? Actually, instead of a `if let` you can move the guard up and instead of a new level, you have the whole method statement at the same level.

```suggestion
    guard 
        let ciImage = CIImage(contentsOf: fileName), 
        let img = convertCIImageToCGImage(inputImage: ciImage) 
    else {
        return
    }

    let requestHandler = VNImageRequestHandler(cgImage: img)

    // Create a new request to recognize text.
    let request = VNRecognizeTextRequest(completionHandler: recognizeTextHandler)
    request.recognitionLanguages = recognitionLanguages

    do {
        // Perform the text-recognition request.
        try requestHandler.perform([request])
    } catch {
        print("Unable to perform the requests: \(error).")
    }
```

2022-07-08 08:46 UTC, unnamedd commented on commands/system/ocr.swift
> +    return String(decoding: data, as: UTF8.self)
Question: is this method working? Because as far as I remember and I was checking here, `String(encoding:as)` isn't an existing method in the Foundation, the real one is `String(data:encoding)` which returns as an optional result.

That being said, I don't think this method here is working, if you convert to use the one I mentioned before, then it will be an optional and you need to make the method return and optional String (`-> String?`) or unwrap the content into a real String before return it here.

2022-07-22 09:53 UTC, dehesa commented
All seems good. Thank you for the work @wmszhe and sorry it took a bit of time to review this.

2022-07-22 09:53 UTC, merged