Fix bugs and changed file name
raycast/script-commands pull request #744
Opened 2022-07-06 00:12 UTC by razvanazamfirei

## Description

Updated API call to new endpoint, changed add method to "quick add" to reduce the number of arguments, cleaned up redundant code

## Type of change

- [X] Bug fix
- [X] Improvement of an existing script

## Screenshot

## Dependencies / Requirements

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2022-07-08 08:09 UTC, unnamedd requested changes
Hi @razvanazamfirei,

thanks for your update in this Script Command. I've made some comments, please, let us know in the comment when you address them for a second round of review.

2022-07-08 08:09 UTC, unnamedd commented on commands/apps/todoist/create-task.sh
> +# @raycast.argument1 { "type": "text", "placeholder": "call mom tomorrow at 5", "optional": false, }
```suggestion
# @raycast.argument1 { "type": "text", "placeholder": "Call Mom Tomorrow at 5" }
```

2022-07-08 08:09 UTC, unnamedd commented on commands/apps/todoist/create-task.sh
> +# @raycast.description Creates Todoist task
```suggestion
# @raycast.description Create Task
```

2022-07-08 08:09 UTC, unnamedd commented on commands/apps/todoist/create-task.sh
>  #!/bin/bash
This Script Command demands an extra setup, for that reason, you must rollback the file name to `create-task.template.sh`, the suffix `.template` for this case is mandatory in this repository.

2022-07-09 15:20 UTC, razvanazamfirei commented
Should be addressed. Thank you!

2022-07-22 10:29 UTC, merged