Add script command bitcoin price
raycast/script-commands pull request #79
Opened 2020-11-16 20:49 UTC by tanguyls

## Description

This script command retrieves the latest Bitcoin price in USD from the Coindesk API and displays it inline in Raycast.

## Type of change

- [x] New script command

## Screenshot

<img width="862" alt="Screen Shot 2020-11-16 at 20 42 40" src="https://user-images.githubusercontent.com/22481735/99299969-49759400-284c-11eb-872c-2ffbf86980aa.png">

## Dependencies / Requirements

Requires python, not sure this counts as a dependency.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2020-11-16 21:58 UTC, unnamedd approved these changes
@tanguyls it would count as dependency if you had to install anything else, as Python is part of the system, it is okay!

2020-11-17 20:50 UTC, thomaspaulmann requested changes
Great to see your first contribution and what a goodie :-) I left some comments around title, formatting and the refresh interval. Please address those to make your command fit into the rest of the catalog.

Great job 👍

2020-11-17 20:50 UTC, thomaspaulmann commented on commands/dashboard/bitcoin-price-usd.sh
> +# @raycast.title Bitcoin price in USD
We use title-case in our UI. I would suggest the following:

```suggestion
# @raycast.title Bitcoin Price
```

And then move the USD information to the output of the price. See later comment.

2020-11-17 20:50 UTC, thomaspaulmann commented on commands/dashboard/bitcoin-price-usd.sh
> +# @raycast.refreshTime 5s
I know bitcoin is very fluctuating but 5 seconds refresh time seems a lot (or a little?!)! How about decreasing it. I would suggest `1h`. You can always hit enter to do a manual refresh.

2020-11-17 20:50 UTC, thomaspaulmann commented on commands/dashboard/bitcoin-price-usd.sh
> +price=$(curl -s http://api.coindesk.com/v1/bpi/currentprice.json | python -c "import json, sys; print(json.load(sys.stdin)['bpi']['USD']['rate'])")
It would be nice to format the output a little bit more, something like this: `$123.45`. Also you would probably do yourself a favor and write the entire command in python ;-) You would need to change the file extension and the shebang at the top of the file that Raycast detects it. Anyways, I think this is out of scope for this PR.

2020-11-23 16:42 UTC, fe9lix commented
To move this PR forward, I'll merge it and then fix some smaller things on master:

- icon path
- execution bit
- dollar sign for formatting

2020-11-23 16:42 UTC, merged

2020-11-23 16:45 UTC, fe9lix commented
...and refresh rate to 1h, as suggested above