Prayer times diyanet command
raycast/script-commands pull request #791
Opened 2022-11-17 09:25 UTC by emircanerkul

## Description

This command grabs prayer times from the Diyanet's Official Website for people located in Türkiye.

## Type of change

- [x] New script command

## Screenshot
<img width="862" alt="image" src="https://user-images.githubusercontent.com/11430795/202407416-b47bc0f0-0d37-4fed-b145-a9c6a80e5ba1.png">

## Dependencies / Requirements

> You may need to install coreutils via homebrew to make this script work (gdate function).

* Homebrew: https://brew.sh/
* Coreutils: https://formulae.brew.sh/formula/coreutils

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2022-11-17 09:51 UTC, dehesa requested changes
Hey @emircanerkul 

Thank you for another contribution. Could you please create a new folder called `culture` within the `commands` directory and put this script there?

Also check the small documentation notes I left.

2022-11-17 09:51 UTC, dehesa commented on commands/productivity/prayer-times-diyanet.sh
> +# @raycast.description Prayer Times that grabbed from the Diyanet's Official Website for people located in Türkiye.
The word `that` here is unnecessary 😄

2022-11-17 09:51 UTC, dehesa commented on commands/productivity/prayer-times-diyanet.sh
> +# @raycast.icon 🕌
It is not very important, but would you mind sorting the comments as follows. It will help skimming over them.

```bash
# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Prayer Times
# @raycast.mode inline
# @raycast.refreshTime 10m
# @raycast.packageName Culture

# Optional parameters:
# @raycast.icon 🕌

# Documentation
# @raycast.author Emircan Erkul
# @raycast.authorURL https://emircanerkul.com
# @raycast.description Prayer Times grabbed from the Diyanet's Official Website for people located in Türkiye.
```

2022-11-17 10:18 UTC, emircanerkul commented on commands/productivity/prayer-times-diyanet.sh
> +# @raycast.description Prayer Times that grabbed from the Diyanet's Official Website for people located in Türkiye.
Yea, I'm always trying to reduce `that` word in my English, but lots of times, I fail :) Even though I have Grammarly Pro edition, it doesn't catch `that.`

2022-11-17 10:20 UTC, emircanerkul commented on commands/productivity/prayer-times-diyanet.sh
> +# @raycast.icon 🕌
It's done I changed the folder and comment structure. Btw It really helps productivity :) But yea it's also quite religious/cultural.

https://quran.com/17/82

2022-11-17 10:54 UTC, dehesa commented
You forgot the `# @raycast.refreshTime 10m`

2022-11-17 11:45 UTC, emircanerkul commented
@dehesa I removed with purpose. I put in the comment title @emircanerkul
[remove refresh time as it causes clipboard override](https://github.com/raycast/script-commands/pull/791/commits/dbf46299272161114e2c8dc17f8125a7066d805f)

2022-11-17 20:50 UTC, dehesa commented
I see what you mean. Wouldn't it be better to have two commands? One for inline display and another one to copy to clipboard?

2022-11-18 02:20 UTC, emircanerkul commented
@dehesa yea might be, but no need to create complexity and make a command long list. When I need to look I'll just run manually and easily and speedily, when running manually it's okay to copy the clipboard.

2022-11-18 11:23 UTC, dehesa commented
Alright! Sounds good to me.

2022-11-18 11:23 UTC, merged