Create this command to open up a new chrome instance with web security disabled
raycast/script-commands pull request #811
Opened 2023-01-24 11:49 UTC by thsnyzkn

## Description

## Type of change

- [X] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

![chrome-no-cors ](https://user-images.githubusercontent.com/12461397/214284048-0cbc8c9d-e3d6-4d84-8334-0e549da4f65a.gif)

## Dependencies / Requirements

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2023-01-27 01:19 UTC, dehesa requested changes
Hey @thsnyzkn,

Thanks for the contribution, it looks great. I am just suggesting that you change the title title and package name, because they will appear repeated in the RootSearch.

In Raycast, elements in the RootSearch are displayed as: Icon > Title > Package Name.

2023-01-27 01:19 UTC, dehesa commented on commands/browsing/open-chrome-without-cors.sh
> +# @raycast.title Open Chrome without CORS
I would change it to:

```bash
# @raycast.title Open without CORS
```

2023-01-27 01:19 UTC, dehesa commented on commands/browsing/open-chrome-without-cors.sh
> +# @raycast.packageName Open Chrome without CORS
and here:

```bash
# @raycast.packageName Chrome
```

2023-01-27 01:19 UTC, dehesa commented on commands/browsing/open-chrome-without-cors.sh
> +# @raycast.icon 🤖
Optionally (and not necessary for this PR) a nice addition would be to upload a 64x64 Chrome icon under the `/commands/browsing/images` folder and point it out here.

2023-01-30 20:02 UTC, thsnyzkn commented
Hey @dehesa,
Thank you for reviewing and getting back. I added requested changes. Could you please check them, when you have time?

2023-01-31 00:02 UTC, dehesa commented
Looks good! Thank you @thsnyzkn

2023-01-31 00:02 UTC, merged