✨ add command to convert twitter link to nitter
raycast/script-commands pull request #863
Opened 2023-08-04 06:46 UTC by noidwasavailable

## Description

A new script command that takes in a twitter link as an argument and converts it to a nitter.net link and open it in the default browser.

## Type of change

- [x] New script command

## Screenshot

[Passing a Twitter link as an argument](https://imgur.com/u5L8Vau)
[Opening a new browser window with a prompt](https://imgur.com/Vo63WZG)
[Opened link](https://imgur.com/LNuQZiE)

## Dependencies / Requirements

None

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2023-08-04 17:42 UTC, unnamedd requested changes
Hi @noidwasavailable 👋,
thanks for your first contribution to our repository! 

I made some comments on your PR, let me know what you do think about and re-request a review when you finish to address them.

See ya!

2023-08-04 17:42 UTC, unnamedd commented on commands/browsing/convert-twitter-to-nitter.js
> +
According to the CONTRIBUTING.md documentation, in the section [Scripts that require installation of apps](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-apps), if you need a installation of a third party app in order to run your Script Command, you must inform it at the top of this file the dependency needed. 

In your case, it is this one:
```suggestion
// Dependency: This script requires Nodejs.
// Install Node: https://nodejs.org/en/download/

```

2023-08-04 17:42 UTC, unnamedd commented on commands/browsing/convert-twitter-to-nitter.js
> +// @raycast.authorURL https://raycast.com/csharp
According to your GitHub handle, you are @noidwasavailable, why not point to your profile in here? 😉
```suggestion
// @raycast.author cSharp
// @raycast.authorURL https://github.com/noidwasavailable
```

2023-08-04 17:42 UTC, unnamedd commented on commands/browsing/convert-twitter-to-nitter.js
> +let [link] = process.argv.slice(2);
I honestly don't think you need to make use of arguments in here, since your user are probably going to copy the URL, you can simply copy it directly from the clipboard area improving the experience of those who will use your Script Command. 

What do you think of the following suggestion?

```suggestion

// Example Twitter link: https://twitter.com/Cron/status/1644010827647975425
const child_process = require('child_process');
let link = child_process.execSync("pbpaste").toString();
```

this way you will have one less thing to do when using it ;)

2023-08-05 02:02 UTC, noidwasavailable commented
@unnamedd Hey, thanks for such a kind and detailed feedback for my code!

This is my first PR ever period, and I wasn't really sure I was doing them the way I was supposed to. All the suggested changes you made make sense in hindsight.

2023-08-05 17:37 UTC, unnamedd approved these changes
Hi @noidwasavailable, thanks for the changes! Glad you enjoyed them. I am quite confident that everyone who decide to use your Script Command will like the changes you made to make their life easier! 

It looks really good to me! It is approved.
Soon, it will be merged by some of our folks from Raycast.

2023-08-10 08:56 UTC, merged