Add Warp reauth command
raycast/script-commands pull request #864
Opened 2023-08-04 13:13 UTC by DaniruKun

## Description

Adds a missing command to the WARP package - reauthenticate.
In our usecase, just toggling Warp is not enough - we have day-long sessions so we need to trigger a reauth manually a lot.

## Type of change

- [x] New script command
- [ ] 
## Screenshot

## Dependencies / Requirements

WARP CLI (nothing new WARP related).

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2023-08-04 17:22 UTC, unnamedd requested changes

2023-08-04 17:22 UTC, unnamedd commented on commands/README.md
> +  | <img src="https://raw.githubusercontent.com/raycast/script-commands/master/commands/apps/warp/images/warp.png" width="20" height="20"> | [WARP Reauthenticate](apps/warp/warp-reauth.sh) | Reauthen
You don't  need to update change this file, it is auto-generated based on the information defined on the Script Command's metadata.
All the changes made here are going to be lost.

2023-08-04 17:22 UTC, unnamedd commented on commands/apps/warp/warp-reauth.sh
> +# @raycast.title Reauthenticate WARP
You don't need to repeat WARP here, because of the `@raycast.packageName` it will be used anyway at the right side of `Reauthenticate`.

```suggestion
# @raycast.title Reauthenticate
```

2023-08-07 17:17 UTC, DaniruKun commented on commands/README.md
> +  | <img src="https://raw.githubusercontent.com/raycast/script-commands/master/commands/apps/warp/images/warp.png" width="20" height="20"> | [WARP Reauthenticate](apps/warp/warp-reauth.sh) | Reauthen
Removed changes.

2023-08-07 17:17 UTC, DaniruKun commented on commands/apps/warp/warp-reauth.sh
> +# @raycast.title Reauthenticate WARP
Done

2023-08-07 18:25 UTC, unnamedd approved these changes
Nice @DaniruKun! Thanks for the changes!

It is approved! ✅

2023-08-10 08:55 UTC, merged