Add Record Screen With Keystroke Pro command
raycast/script-commands pull request #866
Opened 2023-08-12 09:55 UTC by danulqua

## Description

Some people love to use the Keystroke Pro app to display keystrokes during screen recordings but don't like keeping it running in the background all the time. This script command simultaneously launches Keystroke Pro and starts CleanShot's Screen Recording.

## Type of change

- [x] New script command

## Screenshot

<img width="1000" alt="Raycast 2023-08-12 at 12 46 03" src="https://github.com/raycast/script-commands/assets/38916225/072eb431-661d-4478-b472-d7a598a1e30f">

## Dependencies / Requirements

CleanShot X and Keystroke Pro should be installed.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2023-08-12 23:23 UTC, unnamedd requested changes
Hey @danulqua, thanks for your contribution! 
I've made some comments here, nothing problematic, but a nice to have. 

Please, let us know when you finish to address them, will be a pleasure to have your contribution in our repository.

2023-08-12 23:23 UTC, unnamedd commented on commands/apps/cleanshot/cleanshot-record-screen-with-keystroke-pro.sh
> +# @raycast.description Start a screen recording with keystrokes using the Keystroke Pro app and save it as a video or an optimized GIF file.
You cannot have 2 `@raycast.description`s, you must keep everything you want to describe at the same metatag.

```suggestion
# @raycast.description Launch Keystroke Pro and CleanShot X screen recording. Start a screen recording with keystrokes using the Keystroke Pro app and save it as a video or an optimized GIF file.
```

2023-08-12 23:23 UTC, unnamedd commented on commands/apps/cleanshot/cleanshot-record-screen-with-keystroke-pro.sh
> +# @raycast.author danulqua
Will be nicer if you use your own name here, to make it visible in the tools and also on the Awesome Script Commands we do have (this is the README.md)

```suggestion
# @raycast.author Danylo Zalizchuk
```

2023-08-13 07:15 UTC, danulqua commented on commands/apps/cleanshot/cleanshot-record-screen-with-keystroke-pro.sh
> +# @raycast.description Start a screen recording with keystrokes using the Keystroke Pro app and save it as a video or an optimized GIF file.
@unnamedd oh, of course! I just forgot to remove one of them. Fixed!

2023-08-15 07:11 UTC, danulqua commented
Hey @unnamedd, letting you know that I made changes according to your suggestions. Waiting for a review :)

2023-08-15 12:59 UTC, unnamedd approved these changes
Hey @danulqua, thanks for the changes and sorry for the delay in the answer! 
It looks good to me! It is approved! 

Our friends from Raycast will merge as soon as possible! ;)

2023-08-16 13:56 UTC, merged