Add command to join clipboard lines by delimiter
raycast/script-commands pull request #871
Opened 2023-08-27 11:36 UTC by decaylala

## Description

Adds a new script command that joins multiple lines of text from the clipboard into a single line, separated by a specified delimiter.

Suppose the clipboard content is as follows and the delimiter specified is `-`:

```
apple
banana
cherry
```

This will result in the new clipboard content being:

```
apple-banana-cherry
```

## Type of change

- [x] New script command

## Screenshot

<img width="781" alt="CleanShot 2023-08-27 at 19 28 34@2x" src="https://github.com/raycast/script-commands/assets/442899/beca22b9-194c-44a6-955c-1976a8c7133f">

## Dependencies / Requirements

None

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2023-08-27 20:31 UTC, unnamedd requested changes
Hi @decaylala 👋,
thanks for your first contribution to our repo. 

Even your PR looks overall good to me, an addition of an extra metatag pointing to your GitHub profile would be very nice! ;)

2023-08-27 20:31 UTC, unnamedd commented on commands/developer-utils/join-lines.sh
> +# @raycast.author decaylala
Add an url for your own profile would be very nice.

```suggestion
# @raycast.author decaylala
# @raycast.authorURL https://github.com/decaylala
```

2023-08-28 06:38 UTC, decaylala commented on commands/developer-utils/join-lines.sh
> +# @raycast.author decaylala
@unnamedd Thank you for your feedback and suggestion.

2023-08-28 11:47 UTC, unnamedd approved these changes
Thanks for the update @decaylala!

It looks good to me! Approved ✅

2023-09-05 15:21 UTC, merged