add npmjs search script
raycast/script-commands pull request #89
Opened 2020-11-19 21:16 UTC by tborychowski

## Description

Add [NPM](npmjs.com) package search script command.

## Type of change

Please delete options that are not relevant.

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot
<img width="862" alt="Screenshot 2020-11-19 at 21 14 09" src="https://user-images.githubusercontent.com/392513/99724893-3660ff00-2aac-11eb-9cdc-99b44eb72a7f.png">

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2020-11-19 22:21 UTC, unnamedd commented
@tborychowski just a reminder, both `commands/README.md` and `commands/extensions.json` are auto generated by the Raycast Toolkit, then, any change you make on those files are going to be overwritten.

2020-11-19 22:25 UTC, unnamedd requested changes

2020-11-19 22:25 UTC, unnamedd commented on commands/web-searches/npmjs.sh
> +# @raycast.icon images/npmjs.png
You need to add the `npmjs.png` in your pull request.

2020-11-19 22:25 UTC, unnamedd commented on commands/README.md
> +| <img src="https://raw.githubusercontent.com/raycast/script-commands/master/commands/web-searches/images/npmjs.png?raw=true" width="20" height="20"> | [Search in npmjs.com](web-searches/npmjs.sh) |
Will be overwritten.

2020-11-19 22:52 UTC, thomaspaulmann commented
> @tborychowski just a reminder, both `commands/README.md` and `commands/extensions.json` are auto generated by the Raycast Toolkit, then, any change you make on those files are going to be overwritten.

We should mention that these files are auto-generated int the contribution guidelines. Seems like it's causing some confusion.

2020-11-19 22:56 UTC, thomaspaulmann requested changes
Please adjust the title to follow our guidelines on title-cased userfacing strings. This way your search looks good among other commands. Thanks!

2020-11-19 22:56 UTC, thomaspaulmann commented on commands/web-searches/npmjs.sh
> +# @raycast.icon images/npmjs.png
Seems like it's there now.

2020-11-19 22:56 UTC, thomaspaulmann commented on commands/web-searches/npmjs.sh
> +# @raycast.title NPM search package
We prefer title-cased user-facing strings. I would suggest the following
```suggestion
# @raycast.title Search NPM Packages
```

Alternatively you could name the command just `Search Packages` and set `NPM` as `packageName`.

2020-11-19 23:08 UTC, unnamedd commented on commands/web-searches/npmjs.sh
> +# @raycast.icon images/npmjs.png
Great!

2020-11-20 01:53 UTC, sindresorhus commented on commands/web-searches/npmjs.sh
> +# @raycast.title NPM search package
`npm` should be lowercase. That's how the official name is.

2020-11-20 08:27 UTC, tborychowski commented on commands/web-searches/npmjs.sh
> +# @raycast.title NPM search package
I have no idea how to do both :-)

2020-11-20 09:06 UTC, thomaspaulmann approved these changes
Thanks for updating the title and great first contribution @tborychowski 🎉

2020-11-20 09:06 UTC, merged

2020-11-20 19:45 UTC, thomaspaulmann commented on commands/web-searches/npmjs.sh
> +# @raycast.title NPM search package
Thanks @sindresorhus. I wasn't aware that this is the official name. Just updated it.