Add the 'Enable borderless Arc' script
raycast/script-commands pull request #891
Opened 2023-11-29 06:18 UTC by rudeayelo

## Description

This script quickly and effortlessly enables the feature flag that remove Arc Browser's border. The process is rather tedious if done manually.

Here's [some more documentation about modifying Arc's preference file](https://arcinternet.notion.site/arcinternet/Arc-Advanced-f7efb9a85d824cec828711ece77e1474).

## Type of change

- [x] New script command

## Screenshot
![CleanShot 2023-11-29 at 07 13 54@2x](https://github.com/raycast/script-commands/assets/140042/7265e9e9-752d-4b83-917f-c250aaf044ad)

## Dependencies / Requirements

Requires [Arc](https://arc.net/) to be installed, obviously.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2023-11-30 14:30 UTC, dehesa requested changes
Thank you for the contribution. Aside from the minor comment below. Would you mind making the icon 64x64 px, please.

2023-11-30 14:30 UTC, dehesa commented on commands/apps/arc/enable-borderless-arc.sh
> +# @raycast.title Enable borderless Arc
The word `Arc` will appear duplicated when displayed in RootSearch. That is:
```
[Icon] Enable borderless Arc Arc
```

I would suggest two changes:
- Make The `b` of `borderless a capital letter.
- Remove the word `Arc` from `@raycast.title`

2023-11-30 18:47 UTC, unnamedd commented on commands/apps/arc/enable-borderless-arc.sh
> +# @raycast.icon imges/arc.png
Would be also great if you could follow the most used naming for the images folder, instead of `imges` (which looks more like a typo) rename it to `images`.

2023-12-01 05:25 UTC, rudeayelo commented on commands/apps/arc/enable-borderless-arc.sh
> +# @raycast.icon imges/arc.png
It totally was a typo 😅

2023-12-01 05:27 UTC, rudeayelo commented
Closing since the last Arc update removed the possibility of modding it via feature flags 😢

@unnamedd @dehesa thank you guys for the code review, will keep those comments into account whenever I post a new command.

2023-12-01 05:27 UTC, closed without merging