Feat: OctoPrint connection
raycast/script-commands pull request #894
Opened 2023-12-19 21:19 UTC by mSarheed

## Description

Small python script which connects to local OctoPrint instance and retrieve the 3D printer information.

## Type of change

- [X] New script command

## Screenshot

![SCR-20231219-tfgn](https://github.com/raycast/script-commands/assets/6534633/86ee8891-eddc-4dad-bff4-9617a707641a)

## Dependencies / Requirements

Requires the installation of the "requests" dependency for Python. "pip install requests".

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2023-12-20 19:53 UTC, unnamedd requested changes
Hi @mSarheed,

Thanks for submitting your Script Command! This is the moment when I'd like to have a 3D print, just like yours, to make use of it! 😅

I have made some comments here. Please re-request a review when you finish addressing them!

2023-12-20 19:53 UTC, unnamedd commented on commands/dashboard/octoprint.template.py
> +# @raycast.packageName OctoPrint
As the `packageName` used to be related to the folder to where the Script Command belongs to, and also, as it seems to belong to a OctoPrint app (correct me if I am wrong), it is better if you move this file to apps/octoprint, this way it will fit better in the repository's organization.

2023-12-20 19:53 UTC, unnamedd commented on commands/dashboard/octoprint.template.py
> +# @raycast.title OctoPrint
As we do have the `packageName` pointing to `OctoPrint`, we don't need to have it duplicated, otherwise, you are going to see in the root search "OctoPrint [OctoPrint]", that said, what do you think if we rename it to "Status"? In the root search it will be visible as "Status [OctoPrint]"

```suggestion
# @raycast.title Status
```

2023-12-20 19:53 UTC, unnamedd commented on commands/dashboard/octoprint.template.py
> +#
None of the lines above is needed, you can safely remove them.

```suggestion
```

2023-12-20 19:53 UTC, unnamedd commented on commands/dashboard/octoprint.template.py
> +# @raycast.description Raycast script commands which returns the status of your OctoPrint intance
You don't have to mention "Raycast Script Command" in the description of your Script Command, with that in mind, what do you think with the following?

```suggestion
# @raycast.description Show the status of your OctoPrint.
```

2023-12-20 19:53 UTC, unnamedd commented on commands/dashboard/octoprint.template.py
> +#
You can clean it from here
```suggestion
```

2023-12-20 19:53 UTC, unnamedd commented on commands/dashboard/octoprint.template.py
> +        print(20 * "-")
I hope you don't mind, but I took the liberty to make a small change in the code to suggest you here, in order to avoid some duplications.

In any case, you can completely ignore this comment here.

```suggestion
    is_printing = state == 'Printing'
    emoji = " 💪" if is_printing else " 😴"

    print("OctoPrint Status 🖨️")
    print(20 * "-")
    print(green("➡️ " + "State ", state) + emoji)

    if is_printing:
        # Retrieve the job information
        endpoint = 'job'
        url = f'{base_url}{endpoint}'
        response = requests.get(url, headers=headers)
        job_info = response.json()
        job_name = job_info['job']['file']['name']
        job_progress = int(job_info['progress']['completion'])
        job_progress = str(job_progress) + "%"
        time_left = job_info['progress']['printTimeLeft'] // 60
        time_left = str(time_left) + " minutes left"

        print(green("➡️ " + "Job Name", job_name) + " 📝")
        print(green("➡️ " + "Job Progress", job_progress) + " 📈")
        print(green("➡️ " + "Time Left", time_left) + " ⏳")

    print(green("➡️ " + "Tool Temp", a_tool_temp) + " -> " + red("Target Temp", t_tool_temp) + " 🔥")
    print(green("➡️ " + "Bed Temp", a_bed_temp)+ " -> " + red("Target Temp", t_bed_temp) + " 🔥")
    print(20 * "-")
```

2024-01-08 17:48 UTC, dehesa commented
Hey @mSarheed, thanks again for the PR, but do you intend to address the comments from @unnamedd?

2024-01-18 11:09 UTC, closed without merging