Codeforces contests to Google Calendar
raycast/script-commands pull request #896
Opened 2023-12-26 08:23 UTC by Iron0utlaw

## Description

This script command is designed to incorporate upcoming [Codeforces](https://codeforces.com/) contests into Google Calendar. It leverages the [Codeforces public API](https://codeforces.com/apiHelp/methods#contest.list) to retrieve information about the upcoming contests and utilizes the [Google Calendar API](https://developers.google.com/calendar/api/quickstart/python#enable_the_api) to add them. To keep track of previously added contests, the script utilizes a `data.txt` file to store the corresponding contest IDs.

## Type of change

- [x] New script command

## Screenshot
![Screenshot 2023-12-26 at 13 46 45](https://github.com/raycast/script-commands/assets/92783708/8eaa49be-5f27-461e-966a-bfa8f7aba749)

## Dependencies / Requirements

### Dependencies
- google-api-python-client
- google-auth-httplib2
- google-auth-oauthlib
- requests

### API Credentails
- Using this documentation https://developers.google.com/calendar/api/quickstart/python#enable_the_api
- Add `credentials.json` as `creds.json` to the folder

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2024-01-08 12:18 UTC, unnamedd commented
Hey @Iron0utlaw,
sure thing, will be a pleasure. 
Sorry for the long delay to answer, I will review it as soon as possible.

2024-01-08 18:37 UTC, dehesa requested changes
Hey there,

Sorry it took so long to review. I was hoping @unnamedd would lend a hand here since my Python knowledge is fairly low 😛

I left below some comments; aside from that and as far as I understand, this script would generate a further 3 files: `token.json`, `creds.json`, and `data.txt`. I am not a big fan of that. Do you have any suggestion @unnamedd on how to not have so many lingering files?

2024-01-08 18:37 UTC, dehesa commented on commands/productivity/google-calendar/codeforces/add-codeforces-contests.template.py
> +        'timeZone': 'Asia/Kolkata',
This is hardcoded to Kolkata in the middle of the code, it would be better to extract the timezone in a variable at the beginning of the code so it is easy to change for users.

2024-01-09 00:15 UTC, unnamedd requested changes
Hi @Iron0utlaw, 👋 
thanks for contributing to our repository.

I wrote some comments for you. 
Please, read them carefully because there are too many things we need to discuss before moving on (or not).

As soon as you finish to address them, please re-request a review for a second round.

2024-01-09 00:15 UTC, unnamedd commented on commands/productivity/google-calendar/codeforces/add-codeforces-contests.template.py
> +      token.write(creds.to_json())
It is not good to run the authorisation process every single time you call `add_event`. 
You must extract that process from here into another method and call it before calling `add_event`, because this method is being called inside of a `for-loop`.

2024-01-19 23:32 UTC, dehesa commented
Hey @Iron0utlaw,

Do you intend to work on this PR?

2024-01-20 06:43 UTC, Iron0utlaw commented
Yes, I will start working on this

2024-01-23 08:42 UTC, closed without merging