Create new BusyCal event or task
raycast/script-commands pull request #904
Opened 2024-01-26 22:03 UTC by annietma

## Description

This script command creates a new BusyCal event or task.

## Type of change

- [X] New script command

## Screenshot
![CleanShot 2024-01-26 at 14 02 52](https://github.com/raycast/script-commands/assets/67172603/dc0d3621-3ccd-4f2a-8177-1797a773013f)

## Dependencies / Requirements
# Dependency: This script requires `Python3` installed: https://www.python.org/downloads/

## Checklist
- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2024-01-29 12:50 UTC, unnamedd requested changes
Hi @annietma :wave:
Thanks for your contribution to our repository. 

I made some comments on your PR, please re-request a review when you finish to address them and we will do a second round of review.

2024-01-29 12:50 UTC, unnamedd commented on commands/apps/busycal/new-busycal-event-or-task.applescript
> +# @raycast.description This script creates a new event or task in BusyCal.
```suggestion
# @raycast.description Creates new events or tasks in BusyCal.
```

2024-01-29 12:50 UTC, unnamedd commented on commands/apps/busycal/new-busycal-event-or-task.applescript
> +# @raycast.title New BusyCal Event/Task
```suggestion
# @raycast.title Create Event/Task
```

2024-01-29 12:50 UTC, unnamedd commented on commands/apps/busycal/new-busycal-event-or-task.applescript
> +# @raycast.argument2 { "type": "text", "placeholder": "task", "optional": true }
Instead of creating two arguments for each purpose, from now on, you can make use of a dropdown in the arguments. Give a check in [here](https://github.com/raycast/script-commands/blob/master/documentation/ARGUMENTS.md).
Basically you just have to change the `type` from `text` to `dropdown` and add another property `data` which will contain a list of a structured data. 

Let me show you an example:

```
# @raycast.argument2 { "type": "dropdown", "placeholder": "Type", "data": [{"title": "Event", "value": "event"}, {"title": "Task", "value": "task"}]}
```

After that, of course you will have to change your condition to check which value was selected in the dropdown, and we cannot forget you will have to have the type text to get the event/task's description.

2024-01-29 12:50 UTC, unnamedd commented on commands/apps/busycal/new-busycal-event-or-task.applescript
> +# Dependency: This script requires `Python3` installed: https://www.python.org/downloads/
You need to indicate the BusyCal is also a dependency the user needs to have installed in the system.

2024-01-29 12:50 UTC, unnamedd commented on commands/apps/busycal/new-busycal-event-or-task.applescript
> +    set theText to do shell script "/usr/bin/python3 -c 'import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))' " & quoted form of msg
Just a small question: is Python here really needed?

2024-02-02 21:12 UTC, annietma commented
Yep, that makes more sense! I've gone ahead and switched the parameter orders.

Thanks😊

2024-02-04 18:56 UTC, unnamedd approved these changes
Hi Annie (@annietma),
thanks for the update and the effort in the PR! 
It looks amazing!

2024-02-06 08:35 UTC, merged

2024-02-06 08:35 UTC, dehesa commented
Thank you for the contribution @annietma. It looks great! And thanks @unnamedd for the fantastic review (as always) 🎉