Add iPerf Speed Test to dashboards
raycast/script-commands pull request #926
Opened 2024-04-08 13:54 UTC by Samywamy10

## Description

This adds a new Dashboard-type script command which runs an [iPerf network speed test](https://iperf.fr/iperf-download.php) to a nominated iPerf server. Useful for seeing how quickly file transfers are to something like a NAS (to test local network speed) or to a remote iPerf server (to test internet speed).

This is an inline output and tells you how fast the speed was (on average) in Mbits/sec as well as the time the test was ran.

## Type of change

- [X] New script command

## Screenshot

https://github.com/raycast/script-commands/assets/1314053/1dd367a9-b4ff-4a3f-8d0b-ecc6c47deea1

## Dependencies / Requirements

1. Install [iPerf](https://iperf.fr/iperf-download.php) (`brew install iperf`)
2. Add IP address of targeted iPerf server

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2024-04-08 17:46 UTC, unnamedd requested changes
Hi Sam, 👋
thanks for you contribution. Please, give a read on my comments and re-request a review when you finish to address them.

2024-04-08 17:46 UTC, unnamedd commented on commands/dashboards/iperf-speed-test.sh
> +# @raycast.description Runs an iPerf speed test.
```suggestion
# @raycast.description Runs an iPerf Speed Test.
```

2024-04-08 17:46 UTC, unnamedd commented on commands/dashboards/iperf-speed-test.sh
> +
```suggestion
# @raycast.packageName iPerf

```

2024-04-08 17:46 UTC, unnamedd commented on commands/dashboards/iperf-speed-test.sh
> +# @raycast.title iPerf Speed Test
```suggestion
# @raycast.title Speed Test
```

2024-04-08 17:46 UTC, unnamedd commented on commands/dashboards/iperf-speed-test.sh
> +# @raycast.author samywamy10
Would be better if you could use your name here instead of your GitHub Handle
```suggestion
# @raycast.author Sam Wright
```

2024-04-08 17:46 UTC, unnamedd commented on commands/dashboards/iperf-speed-test.sh
Based on [our guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-additional-modification), you need to rename this file to include ﻿`.template` in it, for example: `﻿iperf-speed-test.template.sh`.

2024-04-08 23:30 UTC, Samywamy10 commented on commands/dashboards/iperf-speed-test.sh
I read that, but then I saw [other files](https://canva.enterprise.slack.com/archives/C03LCRN83P1/p1712617473573609) that don't use this naming convention so wasn't sure

2024-04-09 08:53 UTC, unnamedd commented on commands/dashboards/iperf-speed-test.sh
File that demands an extra configuration without `.template` in the name is a mistake, we are going to fix it, thanks for sharing it though.

2024-04-09 08:54 UTC, unnamedd approved these changes
It looks good to me! Thanks for the contribution @Samywamy10!

2024-04-11 07:21 UTC, merged