Script for convert Markdown formatting to Telegram format
raycast/script-commands pull request #936
Opened 2024-05-03 17:26 UTC by borzov

## Description

This script converts Markdown-formatted text into a Telegram-compatible format. It automatically transforms various Markdown formatting elements, such as headers, bold, italic, strikethrough, spoilers, underline, links, and inline code, into their corresponding Telegram formatting tags. The script also adds emojis before different header levels and inserts empty lines between paragraphs to improve readability.

This tool is particularly useful for those who frequently work with Markdown documentation and want to quickly share it on Telegram while preserving most of the original formatting. Instead of manually altering the syntax for each formatting element, users can simply copy their Markdown text, run this script, and have the formatted version ready to paste directly into a Telegram chat, saving time and effort.

## Type of change

- [Х] New script command

## Dependencies / Requirements

The script relies on the following built-in Python libraries for its functionality on macOS:

1. `re`: This library is used for regular expressions, which are essential for searching and replacing Markdown formatting elements with their Telegram counterparts.

2. `subprocess`: This library is used to interact with the macOS clipboard through the `pbpaste` and `pbcopy` command-line utilities. It allows the script to read Markdown text from the clipboard and write the converted text back to the clipboard.

No additional third-party libraries are required, as the script utilizes the built-in `re` and `subprocess` libraries, making it easy to set up and use on macOS systems with Python installed.

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2024-05-06 16:20 UTC, unnamedd requested changes
Hi Maxim (@borzov) 👋,
thanks for your first contribution to our repository!

Really liked your work in this Script Command! 
I've made some really small comments, nothing really big, just to improve even more it.

Please, re-request a view when you address them and then we can give a second round, okay?

2024-05-06 16:20 UTC, unnamedd commented on commands/conversions/markdown-to-telegram.py
> +# @raycast.packageName Content Tools
The `packageName` is normally assigned to the folder where the Script Command is placed, in our current case: "Conversions"

```suggestion
# @raycast.packageName Conversions
```

2024-05-06 16:20 UTC, unnamedd commented on commands/conversions/markdown-to-telegram.py
> +# @raycast.author Maxim Borzov
Let's add your GitHub URL in order to make easier to credit you in the README, shall we 😉?

```suggestion
# @raycast.author Maxim Borzov
# @raycast.authorURL https://github.com/borzov
```

2024-05-06 16:20 UTC, unnamedd commented on commands/conversions/markdown-to-telegram.py
> +
I guess we can extract the `LANG` dictionary and also the encoding from the `copy` and `paste` methods, don't you think? 
Instead of having them duplicated, lets define them outside of the methods and then just call 'em

```suggestion

env_vars = {'LANG': 'en_US.UTF-8'}
encoding = 'utf-8'
```

2024-05-06 16:20 UTC, unnamedd commented on commands/conversions/markdown-to-telegram.py
> +    return subprocess.check_output('pbpaste', env={'LANG': 'en_US.UTF-8'}).decode('utf-8')
```suggestion
    return subprocess.check_output('pbpaste', env=env_vars).decode(encoding)
```

2024-05-06 16:20 UTC, unnamedd commented on commands/conversions/markdown-to-telegram.py
> +    process = subprocess.Popen('pbcopy', env={'LANG': 'en_US.UTF-8'}, stdin=subprocess.PIPE)
```suggestion
    process = subprocess.Popen('pbcopy', env=env_vars, stdin=subprocess.PIPE)
```

2024-05-06 16:20 UTC, unnamedd commented on commands/conversions/markdown-to-telegram.py
> +    process.communicate(text.encode('utf-8'))
```suggestion
    process.communicate(text.encode(encoding))
```

2024-05-07 06:27 UTC, borzov commented
Thank you, I agree with all the edits. Today I will make a new pull request including your comments.

2024-05-07 21:40 UTC, unnamedd approved these changes
Hi Maxim! @borzov 

Really nice changes and code documentation. 
Thanks for caring about it!

It looks very nice!

2024-05-21 08:23 UTC, merged