Hide Application
raycast/script-commands pull request #956
Opened 2024-08-13 04:44 UTC by that70schris

## Description

This command hides the frontmost app .  This is useful if you want to remap the Hide menu command.

## Type of change

- [ ] New script command

## Screenshot

## Dependencies / Requirements

## Checklist

- [ ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2024-08-14 14:26 UTC, unnamedd reviewed
Hi @that70schris, thanks for you contribution.

However, I do think we have two problems.

First, your Script Command assumes the user does have Swift installed and this isn't true (not going to mention that is missing the indication that Swift needs to be installed).

Second, macOS does provide the possibility to hide any frontmost apps just by pressing Command + H, this is system-wide shortcut as you can see in the first screenshot.
Also, still in the second point, Raycast also provides a way to hide an application, give a check in the second screenshot. 

Then, I'd like to raise the question: what would be the benefit of this Script Command you are proposing?

First screenshot
<img width="330" alt="image" src="https://github.com/user-attachments/assets/e5885a19-66ec-4fba-9eae-ac5919cf2d2d">

Second screenshot
<img width="862" alt="image" src="https://github.com/user-attachments/assets/cd0e1a76-b9c0-450b-bccc-c96a4fc85c24">

2024-08-14 14:32 UTC, that70schris commented
@unnamedd ok, I originally had it as an AppleScript so I can revert it back to that.  

to the second point, I am aware that `command + h` is available system wide and in Raycast.  However, there is no way to remap this shortcut system wide as there is with shortcuts for other menu commands.  as I stated in my description, this command is to specifically to allow the remapping of the keyboard shortcut

2024-08-14 14:44 UTC, that70schris commented
Also, as far as needing an indication that swift is required, I'm not sure what you mean.  Looking through other swift commands, I don't see an example of this

2024-08-15 08:01 UTC, unnamedd commented
> Also, as far as needing an indication that swift is required, I'm not sure what you mean. Looking through other swift commands, I don't see an example of this

In the section [Scripts that require installation of runtimes and dependencies](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-runtimes-and-dependencies) of our CONTRIBUTING.md you will be able to see it. 😉

> to the second point, I am aware that command + h is available system wide and in Raycast. However, there is no way to remap this shortcut system wide as there is with shortcuts for other menu commands. As I stated in my description, this command is to specifically to allow the remapping of the keyboard shortcut

It makes sense for you. Maybe it won't make sense for others (myself included), especially because the shortcut is available system-wide, but I am not here to judge; I am here to raise points.

> The way I personally use this is to first turn my `capslock` key into an `esc` key, and then assign `command + esc` to "Hide Application". At least while I'm still in the habit of using `alt + tab` to navigate, this addition makes it really easy to keep my thumb on the `command` key, and just move my pinky from `tab` to `capslock`

Just one thing regarding this remap: Raycast uses Command + ESC to return to the root search. This is very handy when you are deep inside Raycast (extensions, details, more details about something). You can use that shortcut to return instead of just closing Raycast.

Last but not least: it's very interesting that you had it as an Apple Script and then reverted it. This way, there's no need to install anything, making it even easier to use your Script Command.

Thanks for the revert and for the explanations.

2024-08-15 08:06 UTC, unnamedd requested changes

2024-08-15 08:06 UTC, unnamedd commented on commands/navigation/hide-application.applescript
> +# @raycast.author that70schris
```suggestion
# @raycast.author Chris Bailey
```

2024-08-15 08:06 UTC, unnamedd commented on commands/navigation/hide-application.applescript
> +# @raycast.title Hide Application
I guess it can be "Foremost", "Frontmost" or "Current". What do you think?

```suggestion
# @raycast.title Hide Current Application
```

2024-08-15 08:06 UTC, unnamedd commented on commands/navigation/hide-application.applescript
> +
Would be interesting to add a description to your Script Command to make it more beautiful in the Awesome Script Command and also, inside of Raycast.

```suggestion
# @raycast.description Easily hide your foremost application

```

2024-08-15 11:36 UTC, that70schris commented
yea, I was actually trying to find a way to prevent this script from hiding the Raycast prompt, do you know if that's possible?

2024-08-15 12:02 UTC, unnamedd commented
I don't think it will be possible to override it 😔

2024-08-15 12:06 UTC, that70schris commented
Instead of overriding it I was looking for a way to detect that the Raycast prompt was open and to skip "set visible to false"

2024-08-15 14:23 UTC, unnamedd commented
I guess that would only be possible if Raycast had an API for AppleScript, but as far as I know, they do not. I am quite sure that won't be easy to achieve.

2024-08-15 23:02 UTC, that70schris commented
thanks @unnamedd, I've made the updates you suggested

2024-08-16 09:06 UTC, unnamedd approved these changes
@that70schris thanks for the changes and your contribution to our repository.

It looks good to me! ✅

2024-08-30 13:08 UTC, merged