Add script command: Define a word
raycast/script-commands pull request #99
Opened 2020-11-22 13:46 UTC by jesse-c

## Description

It adds a script command for looking up the definition of a word using the macOS dictionary.

## Type of change

Please delete options that are not relevant.

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

<img width="862" alt="Screen Shot 2020-11-22 at 1 43 29 pm" src="https://user-images.githubusercontent.com/1405676/99905477-dabf8d00-2cc8-11eb-89fc-2c24cc90fe8b.png">

## Dependencies / Requirements

N/A
## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

2020-11-22 19:09 UTC, unnamedd requested changes

2020-11-22 19:09 UTC, unnamedd commented on commands/system/define-word.swift
> +}
I suggest you to check if the amount of arguments if you received is greater than 1, then you will ensure that you can ask for the argument in the second position (`[1]`) without receive an `index out of bound` error:

```suggestion
if CommandLine.argc > 1 {
  let argument = CommandLine.arguments[1].lowercased()

  // https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/DictionaryServicesProgGuide/access/access.html#//apple_ref/doc/uid/TP40006152-CH5-SW3
  let result = DCSCopyTextDefinition(nil, argument as CFString, CFRangeMake(0, argument.count))?.takeRetainedValue() as String?

  print(result ?? "No definition found")
} else {
  print("Must pass 1 word to define") 
}
```

2020-11-22 22:18 UTC, jesse-c commented on commands/system/define-word.swift
> +}
That's a fair suggestion! Thanks.

2020-11-22 23:38 UTC, thomaspaulmann approved these changes
Cool one! Just an heads up, we do plan to add support for definitions sooner or later. For now we can keep the script command but this might be replaced by some built-in solution.

2020-11-22 23:38 UTC, thomaspaulmann commented on commands/system/define-word.swift
> +  print("Must pass 1 word to define")
This should never happen 🤞

2020-11-22 23:38 UTC, merged

2020-11-23 00:24 UTC, unnamedd commented on commands/system/define-word.swift
> +  print("Must pass 1 word to define")
It might happen if you execute the script manually via terminal, not via Raycast, but it's never bad to be safer, right?

2020-11-23 00:40 UTC, thomaspaulmann commented on commands/system/define-word.swift
> +  print("Must pass 1 word to define")
Yes, always better to be safe!

2020-11-23 10:34 UTC, jesse-c commented
Happy to see the script removed once there's some built-in functionality!